insert into offers (id, city_from, city_to, cost) values (1, 'Licheng', 'Xukou', 10233);
insert into offers (id, city_from, city_to, cost) values (2, 'Sapu Padidu', 'Central', 7178);
insert into offers (id, city_from, city_to, cost) values (3, 'Yangzizhou', 'Sedinginan', 9231);
insert into offers (id, city_from, city_to, cost) values (4, 'Baghdad', 'Krajan Puru', 16680);
insert into offers (id, city_from, city_to, cost) values (5, 'Tianxing', 'Neópolis', 9693);
insert into offers (id, city_from, city_to, cost) values (6, 'Smidary', 'Vostochnoe Degunino', 13420);
insert into offers (id, city_from, city_to, cost) values (7, 'Ōiso', 'Kuala Lumpur', 16152);
insert into offers (id, city_from, city_to, cost) values (8, 'Fengshan', 'Zhiqing Songduo', 4059);
insert into offers (id, city_from, city_to, cost) values (9, 'Aībak', 'Lavezares', 19451);
insert into offers (id, city_from, city_to, cost) values (10, 'Kuantan', 'Auch', 18418);
insert into offers (id, city_from, city_to, cost) values (11, 'Kawit', 'Jinzao', 2438);
insert into offers (id, city_from, city_to, cost) values (12, 'Falun', 'São Manuel', 21792);
insert into offers (id, city_from, city_to, cost) values (13, 'Balzers', 'Ginatilan', 3447);
insert into offers (id, city_from, city_to, cost) values (14, 'Naukšēni', 'Jihui', 5100);
insert into offers (id, city_from, city_to, cost) values (15, 'Sorochuco', 'Hushan', 3299);
insert into offers (id, city_from, city_to, cost) values (16, 'Polomolok', 'Dodu Dua', 14257);
insert into offers (id, city_from, city_to, cost) values (17, 'Concordia', 'Cholpon-Ata', 20082);
insert into offers (id, city_from, city_to, cost) values (18, 'Hobaramachi', 'Tebluru', 14920);
insert into offers (id, city_from, city_to, cost) values (19, 'Melekeok Village', 'Senador Canedo', 8971);
insert into offers (id, city_from, city_to, cost) values (20, 'Fornos', 'Chazón', 13286);
insert into offers (id, city_from, city_to, cost) values (21, 'Jiyang', 'High Point', 14164);
insert into offers (id, city_from, city_to, cost) values (22, 'Hénin-Beaumont', 'Mamonit', 16988);
insert into offers (id, city_from, city_to, cost) values (23, 'Reshetnikovo', 'Zastron', 5010);
insert into offers (id, city_from, city_to, cost) values (24, 'Embajador Martini', 'Rongcheng', 20765);
insert into offers (id, city_from, city_to, cost) values (25, 'Montpellier', 'Matanzas', 7647);
insert into offers (id, city_from, city_to, cost) values (26, 'Cruces', 'Cimara', 1173);
insert into offers (id, city_from, city_to, cost) values (27, 'Fylí', 'Aiguo', 12001);
insert into offers (id, city_from, city_to, cost) values (28, 'Harper', 'Pinheiro Machado', 10435);
insert into offers (id, city_from, city_to, cost) values (29, 'Rychnov nad Kněžnou', 'Lyubinskiy', 8806);
insert into offers (id, city_from, city_to, cost) values (30, 'Il’ya', 'Évlalo', 19593);
insert into offers (id, city_from, city_to, cost) values (31, 'Qiaotou', 'Savannah', 20852);
insert into offers (id, city_from, city_to, cost) values (32, 'Agudos', 'Soufrière', 6033);
insert into offers (id, city_from, city_to, cost) values (33, 'Atolina', 'Anchorage', 17628);
insert into offers (id, city_from, city_to, cost) values (34, 'Currais Novos', 'Padaimut', 6242);
insert into offers (id, city_from, city_to, cost) values (35, 'Capioví', 'Matão', 6376);
insert into offers (id, city_from, city_to, cost) values (36, 'Gilowice', 'Castlebridge', 18177);
insert into offers (id, city_from, city_to, cost) values (37, 'Thị Trấn Ngan Dừa', 'Yuanqian', 590);
insert into offers (id, city_from, city_to, cost) values (38, 'Lichinga', 'Teixoso', 14677);
insert into offers (id, city_from, city_to, cost) values (39, 'San Jose', 'Mont-Joli', 21472);
insert into offers (id, city_from, city_to, cost) values (40, 'Pasarkayu', 'Taiping', 18317);
insert into offers (id, city_from, city_to, cost) values (41, 'Düsseldorf', 'Zitong', 6180);
insert into offers (id, city_from, city_to, cost) values (42, 'Osogbo', 'Chaiyo', 12095);
insert into offers (id, city_from, city_to, cost) values (43, 'Lautaro', 'Xiantang', 17628);
insert into offers (id, city_from, city_to, cost) values (44, 'Aguaí', 'Fray Bentos', 16394);
insert into offers (id, city_from, city_to, cost) values (45, 'Shangma', 'Camabatela', 3479);
insert into offers (id, city_from, city_to, cost) values (46, 'Burnaby', 'Delgado', 1729);
insert into offers (id, city_from, city_to, cost) values (47, 'Zinder', 'Bela Vista', 3945);
insert into offers (id, city_from, city_to, cost) values (48, 'Lucapa', 'Saint-Étienne', 21818);
insert into offers (id, city_from, city_to, cost) values (49, 'Dhī as Sufāl', 'Ḩadādah', 17754);
insert into offers (id, city_from, city_to, cost) values (50, 'Shiroi', 'Vimmerby', 13886);
insert into offers (id, city_from, city_to, cost) values (51, 'Fujioka', 'Qal‘ah-ye Shāhī', 2417);
insert into offers (id, city_from, city_to, cost) values (52, 'Mayapusi', 'Huangli', 3906);
insert into offers (id, city_from, city_to, cost) values (53, 'Drohiczyn', 'Koilás', 20451);
insert into offers (id, city_from, city_to, cost) values (54, 'Shitun', 'Touying', 10598);
insert into offers (id, city_from, city_to, cost) values (55, 'Marale', 'Peuteuy', 3101);
insert into offers (id, city_from, city_to, cost) values (56, 'Chengguan', 'Blumenau', 6230);
insert into offers (id, city_from, city_to, cost) values (57, 'Cuauhtemoc', 'Bayanaūyl', 5882);
insert into offers (id, city_from, city_to, cost) values (58, 'Mae Chan', 'Iktābah', 5034);
insert into offers (id, city_from, city_to, cost) values (59, 'Majan', 'Palaiochóri', 2043);
insert into offers (id, city_from, city_to, cost) values (60, 'Mīzan Teferī', 'Hrochův Týnec', 1019);
insert into offers (id, city_from, city_to, cost) values (61, 'Hacienda La Calera', 'Mahalapye', 15134);
insert into offers (id, city_from, city_to, cost) values (62, 'Néa Ionía', 'Sagana', 6710);
insert into offers (id, city_from, city_to, cost) values (63, 'Corozal', 'Florida', 16193);
insert into offers (id, city_from, city_to, cost) values (64, 'Gangsha', 'Nuevo Emperador', 16279);
insert into offers (id, city_from, city_to, cost) values (65, 'Uyen Hung', 'Angasmarca', 6732);
insert into offers (id, city_from, city_to, cost) values (66, 'Otyń', 'Reims', 16444);
insert into offers (id, city_from, city_to, cost) values (67, 'Mazowe', 'Kungsbacka', 11924);
insert into offers (id, city_from, city_to, cost) values (68, 'Krông Kmar', 'Tiberias', 23486);
insert into offers (id, city_from, city_to, cost) values (69, 'Echarate', 'Canggou', 16583);
insert into offers (id, city_from, city_to, cost) values (70, 'Lukolela', 'Cotuí', 19386);
insert into offers (id, city_from, city_to, cost) values (71, 'Koupéla', 'Dingle', 22080);
insert into offers (id, city_from, city_to, cost) values (72, 'São Luís de Montes Belos', 'Bolesławiec', 6461);
insert into offers (id, city_from, city_to, cost) values (73, 'Shancheng', 'Matão', 21665);
insert into offers (id, city_from, city_to, cost) values (74, 'Konëvo', 'Valle Grande', 8601);
insert into offers (id, city_from, city_to, cost) values (75, 'Mlowo', 'Ialibu', 15903);
insert into offers (id, city_from, city_to, cost) values (76, 'Serra da Boa Viagem', 'Khomutovo', 4746);
insert into offers (id, city_from, city_to, cost) values (77, 'Parawan', 'Nailung', 904);
insert into offers (id, city_from, city_to, cost) values (78, 'Elaiochóri', 'Wichita', 5211);
insert into offers (id, city_from, city_to, cost) values (79, 'Ketapang', 'Dongsheng', 6801);
insert into offers (id, city_from, city_to, cost) values (80, 'Kadudampit', 'Resistencia', 11948);
insert into offers (id, city_from, city_to, cost) values (81, 'Lilla Edet', 'Kembang', 22044);
insert into offers (id, city_from, city_to, cost) values (82, 'Sainte-Marthe-sur-le-Lac', 'Poděbrady', 22536);
insert into offers (id, city_from, city_to, cost) values (83, 'Manzurka', 'Jinglongqiao', 13424);
insert into offers (id, city_from, city_to, cost) values (84, 'Sindangjati', 'Rennes', 18156);
insert into offers (id, city_from, city_to, cost) values (85, 'Liangyaping', 'Kolbudy', 1287);
insert into offers (id, city_from, city_to, cost) values (86, 'Tokyo', 'Linhares', 23436);
insert into offers (id, city_from, city_to, cost) values (87, 'Biasong', 'Beiyang', 10133);
insert into offers (id, city_from, city_to, cost) values (88, 'Buta Ranquil', 'Heiheba', 7506);
insert into offers (id, city_from, city_to, cost) values (89, 'Biharamulo', 'Avranches', 20017);
insert into offers (id, city_from, city_to, cost) values (90, 'Omaha', 'Bắc Kạn', 8917);
insert into offers (id, city_from, city_to, cost) values (91, 'Salvaleón de Higüey', 'Camacupa', 2366);
insert into offers (id, city_from, city_to, cost) values (92, 'Thị Trấn Mường Khương', 'Jiyang', 9568);
insert into offers (id, city_from, city_to, cost) values (93, 'São Pedro', 'Andou', 4100);
insert into offers (id, city_from, city_to, cost) values (94, 'Rokitno', 'Aparecida de Goiânia', 8856);
insert into offers (id, city_from, city_to, cost) values (95, 'Ágios Athanásios', 'Dobra', 18707);
insert into offers (id, city_from, city_to, cost) values (96, 'Bajawa', 'Sumalig', 11930);
insert into offers (id, city_from, city_to, cost) values (97, 'Rybí', 'Pasvalys', 11769);
insert into offers (id, city_from, city_to, cost) values (98, 'Sobreira', 'Kepel', 12799);
insert into offers (id, city_from, city_to, cost) values (99, 'Blagnac', 'Mitsukaidō', 630);
insert into offers (id, city_from, city_to, cost) values (100, 'Sélibabi', 'Angkimang', 23447);
insert into offers (id, city_from, city_to, cost) values (101, 'Arles', 'Merapit', 19735);
insert into offers (id, city_from, city_to, cost) values (102, 'Fengniancun', 'Negotino', 18426);
insert into offers (id, city_from, city_to, cost) values (103, 'Dalarik', 'Feteira Pequena', 20784);
insert into offers (id, city_from, city_to, cost) values (104, 'Xia’ertai', 'Pisz', 15046);
insert into offers (id, city_from, city_to, cost) values (105, 'Mlalo', 'Piraquara', 4435);
insert into offers (id, city_from, city_to, cost) values (106, 'Inyati', 'Ganjaran', 19764);
insert into offers (id, city_from, city_to, cost) values (107, 'Brněnec', 'Calumpit', 4995);
insert into offers (id, city_from, city_to, cost) values (108, 'Studzionka', 'Usukhchay', 5552);
insert into offers (id, city_from, city_to, cost) values (109, 'Pyhäranta', 'Lápas', 15092);
insert into offers (id, city_from, city_to, cost) values (110, 'Jelbuk', 'Huaxijie', 23068);
insert into offers (id, city_from, city_to, cost) values (111, 'Seattle', 'Banghai', 14509);
insert into offers (id, city_from, city_to, cost) values (112, 'Yan Nawa', 'Dhamār', 22123);
insert into offers (id, city_from, city_to, cost) values (113, 'Évreux', 'Nong Phok', 20038);
insert into offers (id, city_from, city_to, cost) values (114, 'Gelan', 'Saseel', 4146);
insert into offers (id, city_from, city_to, cost) values (115, 'Liangshan', 'Alvarães', 6498);
insert into offers (id, city_from, city_to, cost) values (116, 'Ḩabābah', 'Saint-Ouen', 22664);
insert into offers (id, city_from, city_to, cost) values (117, 'Borne Sulinowo', 'Jianli', 13286);
insert into offers (id, city_from, city_to, cost) values (118, 'Dawan', 'Taixi', 21547);
insert into offers (id, city_from, city_to, cost) values (119, 'Aco', 'Fresnes', 4231);
insert into offers (id, city_from, city_to, cost) values (120, 'Javānrūd', 'Fagersta', 14414);
insert into offers (id, city_from, city_to, cost) values (121, 'Żółkiewka', 'Songbo', 7335);
insert into offers (id, city_from, city_to, cost) values (122, 'Petrivka', 'Somorpenang', 2351);
insert into offers (id, city_from, city_to, cost) values (123, 'Klatovy', 'Acopiara', 12055);
insert into offers (id, city_from, city_to, cost) values (124, 'Chicago', 'Nizhnyaya Salda', 23074);
insert into offers (id, city_from, city_to, cost) values (125, 'Parungjawa', 'Ewarton', 4431);
insert into offers (id, city_from, city_to, cost) values (126, 'Waitakere', 'Le Bourget-du-Lac', 17710);
insert into offers (id, city_from, city_to, cost) values (127, 'Pancol', 'Kunmi Erdi', 13815);
insert into offers (id, city_from, city_to, cost) values (128, 'Vostryakovo', 'Sanhe', 6137);
insert into offers (id, city_from, city_to, cost) values (129, 'Orekhovo-Zuyevo', 'Promna', 4097);
insert into offers (id, city_from, city_to, cost) values (130, 'Sanchang', 'Yanglinshi', 20347);
insert into offers (id, city_from, city_to, cost) values (131, 'Bonsari', 'Orlando', 4934);
insert into offers (id, city_from, city_to, cost) values (132, 'Ufa', 'Dodola', 1542);
insert into offers (id, city_from, city_to, cost) values (133, 'Izbicko', 'Czernikowo', 16989);
insert into offers (id, city_from, city_to, cost) values (134, 'Cho-airong', 'Kharovsk', 11779);
insert into offers (id, city_from, city_to, cost) values (135, 'Huoshaodian', 'Blyznyuky', 10793);
insert into offers (id, city_from, city_to, cost) values (136, 'Seminole', 'Zhireken', 21584);
insert into offers (id, city_from, city_to, cost) values (137, 'Pueblo Nuevo', 'Maun', 957);
insert into offers (id, city_from, city_to, cost) values (138, 'Fatou', 'Armação de Búzios', 22746);
insert into offers (id, city_from, city_to, cost) values (139, 'Qianguo', 'Onueke', 4916);
insert into offers (id, city_from, city_to, cost) values (140, 'Bukowina Tatrzańska', 'Vale de Figueira', 1959);
insert into offers (id, city_from, city_to, cost) values (141, 'Pensacola', 'Gameleira', 17269);
insert into offers (id, city_from, city_to, cost) values (142, 'Barajevo', 'Wukeshu', 22388);
insert into offers (id, city_from, city_to, cost) values (143, 'Gniechowice', 'Los Angeles', 3394);
insert into offers (id, city_from, city_to, cost) values (144, 'Thị Trấn Hà Trung', 'Ashcroft', 19681);
insert into offers (id, city_from, city_to, cost) values (145, 'Deauville', 'Bayanbaogede', 10443);
insert into offers (id, city_from, city_to, cost) values (146, 'Chadi', 'Banjarkemuning', 10777);
insert into offers (id, city_from, city_to, cost) values (147, 'Az Zabadānī', 'Liuhe', 4582);
insert into offers (id, city_from, city_to, cost) values (148, 'Alacaygan', 'Ojos de Agua', 8474);
insert into offers (id, city_from, city_to, cost) values (149, 'Vredendal', 'Heping', 9023);
insert into offers (id, city_from, city_to, cost) values (150, 'Zuénoula', 'Fukuoka-shi', 5629);
insert into offers (id, city_from, city_to, cost) values (151, 'Querecotillo', 'Hobo', 5700);
insert into offers (id, city_from, city_to, cost) values (152, 'Jiḩānah', 'Ruda Śląska', 22758);
insert into offers (id, city_from, city_to, cost) values (153, 'Santo Domingo', 'Huntington', 19416);
insert into offers (id, city_from, city_to, cost) values (154, 'Quartier Militaire', 'Shaheying', 1127);
insert into offers (id, city_from, city_to, cost) values (155, 'Kranjska Gora', 'Voskresenskoye', 22496);
insert into offers (id, city_from, city_to, cost) values (156, 'Ngantru', 'Guaduas', 17145);
insert into offers (id, city_from, city_to, cost) values (157, 'Tabio', 'Kista', 19981);
insert into offers (id, city_from, city_to, cost) values (158, 'Muang Sing', 'Karolino-Buhaz', 5529);
insert into offers (id, city_from, city_to, cost) values (159, 'Buynichy', 'Biasong', 2685);
insert into offers (id, city_from, city_to, cost) values (160, 'Puerto Eldorado', 'Tampocon', 10259);
insert into offers (id, city_from, city_to, cost) values (161, 'Canggang', 'Minbu', 19160);
insert into offers (id, city_from, city_to, cost) values (162, 'Bei’an', 'Cankuzo', 8087);
insert into offers (id, city_from, city_to, cost) values (163, 'Yong’an', 'Sémbé', 11296);
insert into offers (id, city_from, city_to, cost) values (164, 'Tianhekou', 'Aconibe', 18327);
insert into offers (id, city_from, city_to, cost) values (165, 'Daba', 'Rennes', 21947);
insert into offers (id, city_from, city_to, cost) values (166, 'Senhor da Serra', 'Shancheng', 16760);
insert into offers (id, city_from, city_to, cost) values (167, 'Ostrožská Lhota', 'Sezimovo Ústí', 11992);
insert into offers (id, city_from, city_to, cost) values (168, 'Babica', 'Masebewa', 2417);
insert into offers (id, city_from, city_to, cost) values (169, 'Bergen', 'Evansville', 14506);
insert into offers (id, city_from, city_to, cost) values (170, 'Lunéville', 'Hats’avan', 7076);
insert into offers (id, city_from, city_to, cost) values (171, 'Kizil', 'Borzechów', 11472);
insert into offers (id, city_from, city_to, cost) values (172, 'Kampinos', 'Klichaw', 4187);
insert into offers (id, city_from, city_to, cost) values (173, 'Srabah', 'Palmital', 14117);
insert into offers (id, city_from, city_to, cost) values (174, 'Boston', 'Wiązownica', 13115);
insert into offers (id, city_from, city_to, cost) values (175, 'Pensacola', 'Jeffrey’s Bay', 18203);
insert into offers (id, city_from, city_to, cost) values (176, 'Nanyuki', 'Banyutengah', 4406);
insert into offers (id, city_from, city_to, cost) values (177, 'Jiahu', 'Muranovo', 23997);
insert into offers (id, city_from, city_to, cost) values (178, 'Kugluktuk', 'Ţayyibat al Imām', 7696);
insert into offers (id, city_from, city_to, cost) values (179, 'Cileunyi', 'Gobō', 10438);
insert into offers (id, city_from, city_to, cost) values (180, 'Nangang', 'Cam Ranh', 3566);
insert into offers (id, city_from, city_to, cost) values (181, 'Balud', 'Caicó', 10731);
insert into offers (id, city_from, city_to, cost) values (182, 'Sun Kunda', 'Youkaichi', 13941);
insert into offers (id, city_from, city_to, cost) values (183, 'Guarapari', 'Longba', 22050);
insert into offers (id, city_from, city_to, cost) values (184, 'Yuanbao', 'Mała Wieś', 13545);
insert into offers (id, city_from, city_to, cost) values (185, 'Maikawada', 'Mobaye', 14210);
insert into offers (id, city_from, city_to, cost) values (186, 'Tejakalapa', 'Nijiangping', 23384);
insert into offers (id, city_from, city_to, cost) values (187, 'Jiaoba', 'Ash Shaykh Zuwayd', 6393);
insert into offers (id, city_from, city_to, cost) values (188, 'Maple Ridge', 'Liusi', 10986);
insert into offers (id, city_from, city_to, cost) values (189, 'Malakal', 'Banarankrajan', 22589);
insert into offers (id, city_from, city_to, cost) values (190, 'Dinājpur', 'Cibodas', 8627);
insert into offers (id, city_from, city_to, cost) values (191, 'Richibucto', 'Thị Trấn Bình Mỹ', 8404);
insert into offers (id, city_from, city_to, cost) values (192, 'Debre Zeyit', 'Stýpsi', 22050);
insert into offers (id, city_from, city_to, cost) values (193, 'Jinshan', 'Cheongju-si', 14374);
insert into offers (id, city_from, city_to, cost) values (194, 'Sukahening', 'Zerkten', 10662);
insert into offers (id, city_from, city_to, cost) values (195, 'Wewit', 'Naukšēni', 743);
insert into offers (id, city_from, city_to, cost) values (196, 'Ban Phaeo', 'Bzou', 6651);
insert into offers (id, city_from, city_to, cost) values (197, 'Valerianovsk', 'Maji', 21591);
insert into offers (id, city_from, city_to, cost) values (198, 'Lawepakam', 'Paôy Pêt', 13448);
insert into offers (id, city_from, city_to, cost) values (199, 'Bétérou', 'Aldeia de Além', 17351);
insert into offers (id, city_from, city_to, cost) values (200, 'Wuluo', 'Tagoloan', 21753);
insert into offers (id, city_from, city_to, cost) values (201, 'Akron', 'Dunleer', 22067);
insert into offers (id, city_from, city_to, cost) values (202, 'Pszczew', 'Na Khu', 22707);
insert into offers (id, city_from, city_to, cost) values (203, 'Sidi Smaïl', 'Goiânia', 18281);
insert into offers (id, city_from, city_to, cost) values (204, 'Tipitapa', 'Uglyanets', 19279);
insert into offers (id, city_from, city_to, cost) values (205, 'Sukasari', 'Montreuil', 17806);
insert into offers (id, city_from, city_to, cost) values (206, 'Canggou', 'Lisków', 10665);
insert into offers (id, city_from, city_to, cost) values (207, 'Orlovskiy', 'Stenungsund', 20452);
insert into offers (id, city_from, city_to, cost) values (208, 'Kamigyō-ku', 'Dangbigih', 10407);
insert into offers (id, city_from, city_to, cost) values (209, 'Hato Mayor del Rey', 'Saḩab', 4975);
insert into offers (id, city_from, city_to, cost) values (210, 'Schiltigheim', 'Kabir', 8547);
insert into offers (id, city_from, city_to, cost) values (211, 'Severskaya', 'Wangunsari', 19884);
insert into offers (id, city_from, city_to, cost) values (212, 'Matão', 'Muarabadak', 3192);
insert into offers (id, city_from, city_to, cost) values (213, 'Daminggong', 'Kazo', 14423);
insert into offers (id, city_from, city_to, cost) values (214, 'Taozhuang', 'Žulová', 12951);
insert into offers (id, city_from, city_to, cost) values (215, 'Floreşti', 'Kuningan', 20208);
insert into offers (id, city_from, city_to, cost) values (216, 'Santander', 'Cawayan', 21229);
insert into offers (id, city_from, city_to, cost) values (217, 'Bragança', 'Kula', 22046);
insert into offers (id, city_from, city_to, cost) values (218, 'Kibonsod', 'Ngancar', 1297);
insert into offers (id, city_from, city_to, cost) values (219, 'Santa Fe', 'Xin’andu', 11380);
insert into offers (id, city_from, city_to, cost) values (220, 'Xiamao', 'Sūrak', 14148);
insert into offers (id, city_from, city_to, cost) values (221, 'Xiabuji', 'Segong', 14909);
insert into offers (id, city_from, city_to, cost) values (222, 'Zainsk', 'Venustiano Carranza', 15588);
insert into offers (id, city_from, city_to, cost) values (223, 'Kherson', 'Barcelona', 5731);
insert into offers (id, city_from, city_to, cost) values (224, 'Byahoml’', 'Lanipao', 17767);
insert into offers (id, city_from, city_to, cost) values (225, 'Heitan', 'Sarvābād', 5634);
insert into offers (id, city_from, city_to, cost) values (226, 'Bouabout', 'Volosovo', 7928);
insert into offers (id, city_from, city_to, cost) values (227, 'San Antonio', 'Valdosta', 5910);
insert into offers (id, city_from, city_to, cost) values (228, 'Slovenska Bistrica', 'Kosaya Gora', 1072);
insert into offers (id, city_from, city_to, cost) values (229, 'Velká Dobrá', 'Jiading', 471);
insert into offers (id, city_from, city_to, cost) values (230, 'Nogent-le-Rotrou', 'Bandar-e Torkaman', 2528);
insert into offers (id, city_from, city_to, cost) values (231, 'Qincheng', 'Przemków', 8740);
insert into offers (id, city_from, city_to, cost) values (232, 'Dongda', 'Sarirejo Satu', 1555);
insert into offers (id, city_from, city_to, cost) values (233, 'Likhovskoy', 'Mitrópoli', 8121);
insert into offers (id, city_from, city_to, cost) values (234, 'Gatesville', 'Kohila', 5396);
insert into offers (id, city_from, city_to, cost) values (235, 'Futian', 'Ludwigshafen am Rhein', 23721);
insert into offers (id, city_from, city_to, cost) values (236, 'Nîmes', 'Campinas', 10905);
insert into offers (id, city_from, city_to, cost) values (237, 'San Felipe', 'Montgomery', 12062);
insert into offers (id, city_from, city_to, cost) values (238, 'Ardirejo', 'Aş Şafaqayn', 14728);
insert into offers (id, city_from, city_to, cost) values (239, 'Kamenjane', 'Havířov', 20701);
insert into offers (id, city_from, city_to, cost) values (240, 'Gaoyu', 'Belozërsk', 9201);
insert into offers (id, city_from, city_to, cost) values (241, 'Colima', 'Villa del Rosario', 3061);
insert into offers (id, city_from, city_to, cost) values (242, 'Meadow Lake', 'Josefův Důl', 18398);
insert into offers (id, city_from, city_to, cost) values (243, 'Al Jīzah', 'Stockholm', 16503);
insert into offers (id, city_from, city_to, cost) values (244, 'Nanjie', 'Śliwice', 22325);
insert into offers (id, city_from, city_to, cost) values (245, 'Kawage', 'Stubno', 10065);
insert into offers (id, city_from, city_to, cost) values (246, 'Hunkuyi', 'Mizi', 6076);
insert into offers (id, city_from, city_to, cost) values (247, 'Ciawi', 'Komi', 9523);
insert into offers (id, city_from, city_to, cost) values (248, 'Dingjiayao', 'Kedatuan', 13427);
insert into offers (id, city_from, city_to, cost) values (249, 'Villa del Rosario', 'Punata', 5356);
insert into offers (id, city_from, city_to, cost) values (250, 'Ros’', 'Gävle', 7573);
insert into offers (id, city_from, city_to, cost) values (251, 'Skatepark', 'San Jerónimo', 2928);
insert into offers (id, city_from, city_to, cost) values (252, 'Songmuping', 'San Juan', 11155);
insert into offers (id, city_from, city_to, cost) values (253, 'Cesson', 'Jardim da Serra', 23308);
insert into offers (id, city_from, city_to, cost) values (254, 'Leijiadian', 'Marsa Alam', 19372);
insert into offers (id, city_from, city_to, cost) values (255, 'Thành Phố Phủ Lý', 'Ishinomaki', 1040);
insert into offers (id, city_from, city_to, cost) values (256, 'Moutas', 'Lapaz', 9383);
insert into offers (id, city_from, city_to, cost) values (257, 'Lloqan', 'Bayuin', 9619);
insert into offers (id, city_from, city_to, cost) values (258, 'São Miguel do Guamá', 'Ḩarf al Musaytirah', 8643);
insert into offers (id, city_from, city_to, cost) values (259, 'Carandaí', 'Kurnia', 2142);
insert into offers (id, city_from, city_to, cost) values (260, 'Muting', 'Juḩr ad Dīk', 10420);
insert into offers (id, city_from, city_to, cost) values (261, 'Longjing', 'Kilifi', 7032);
insert into offers (id, city_from, city_to, cost) values (262, 'Laoxialu', 'Manturovo', 20273);
insert into offers (id, city_from, city_to, cost) values (263, 'Bécancour', 'Santa Cecília', 7539);
insert into offers (id, city_from, city_to, cost) values (264, 'Alingsås', 'Parychy', 10445);
insert into offers (id, city_from, city_to, cost) values (265, 'Plesná', 'Banjar Sedang', 16638);
insert into offers (id, city_from, city_to, cost) values (266, 'Hawassa', 'Pidigan', 6206);
insert into offers (id, city_from, city_to, cost) values (267, 'Chengnan', 'Sadek', 21109);
insert into offers (id, city_from, city_to, cost) values (268, 'Stockholm', 'Burunday', 23864);
insert into offers (id, city_from, city_to, cost) values (269, 'Preiļi', 'Troyes', 12687);
insert into offers (id, city_from, city_to, cost) values (270, 'Gomel', 'Murtajih', 18780);
insert into offers (id, city_from, city_to, cost) values (271, 'Novalja', 'Xiaxindian', 22497);
insert into offers (id, city_from, city_to, cost) values (272, 'Ajasse Ipo', 'Palapye', 9440);
insert into offers (id, city_from, city_to, cost) values (273, 'El Hatillo', 'Sidi Moussa', 6840);
insert into offers (id, city_from, city_to, cost) values (274, 'Tacuatí', 'Xishui', 19067);
insert into offers (id, city_from, city_to, cost) values (275, 'Medovene', 'Villa del Rosario', 8507);
insert into offers (id, city_from, city_to, cost) values (276, 'Buliwao', 'La Mesa', 1679);
insert into offers (id, city_from, city_to, cost) values (277, 'Beima', 'Pagsanahan Norte', 17261);
insert into offers (id, city_from, city_to, cost) values (278, 'Novo Hamburgo', 'Jiangshan', 11655);
insert into offers (id, city_from, city_to, cost) values (279, 'Souillac', 'Shanxi', 12999);
insert into offers (id, city_from, city_to, cost) values (280, 'Bhalwāl', 'Gotputuk', 12783);
insert into offers (id, city_from, city_to, cost) values (281, 'Garibaldi', 'Żabnica', 16911);
insert into offers (id, city_from, city_to, cost) values (282, 'Kavála', 'Pô', 2783);
insert into offers (id, city_from, city_to, cost) values (283, 'Dolní Libina', 'Rincón', 20048);
insert into offers (id, city_from, city_to, cost) values (284, 'Pirg', 'Dongbang', 8851);
insert into offers (id, city_from, city_to, cost) values (285, 'Xiaxihao', 'Oslo', 7127);
insert into offers (id, city_from, city_to, cost) values (286, 'Sumurgeneng', 'Bandung', 5017);
insert into offers (id, city_from, city_to, cost) values (287, 'Krajan Sale', 'As Saddah', 4965);
insert into offers (id, city_from, city_to, cost) values (288, 'Mobile', 'Aracataca', 9035);
insert into offers (id, city_from, city_to, cost) values (289, 'Medellín', 'Dongjiang Matoukou', 22473);
insert into offers (id, city_from, city_to, cost) values (290, 'Baojiadian', 'Turnišče', 9703);
insert into offers (id, city_from, city_to, cost) values (291, 'Cipaku', 'Thiès Nones', 19891);
insert into offers (id, city_from, city_to, cost) values (292, 'Real', 'Kangping', 658);
insert into offers (id, city_from, city_to, cost) values (293, 'Tanghua', 'Kigoma', 5809);
insert into offers (id, city_from, city_to, cost) values (294, 'Amiens', 'Nantes', 4766);
insert into offers (id, city_from, city_to, cost) values (295, 'Taoyuan', 'Nagrak', 1709);
insert into offers (id, city_from, city_to, cost) values (296, 'Plácido de Castro', 'Stockholm', 12700);
insert into offers (id, city_from, city_to, cost) values (297, 'Sutton', 'Rixi', 11427);
insert into offers (id, city_from, city_to, cost) values (298, 'Lucapon', 'Ban Haet', 18854);
insert into offers (id, city_from, city_to, cost) values (299, 'Kroonstad', 'Lavradio', 7428);
insert into offers (id, city_from, city_to, cost) values (300, 'San Luis', 'Gunziying', 23900);
insert into offers (id, city_from, city_to, cost) values (301, 'Tralee', 'Lisovi Sorochyntsi', 16501);
insert into offers (id, city_from, city_to, cost) values (302, 'Sete Cidades', 'Dalan', 11344);
insert into offers (id, city_from, city_to, cost) values (303, 'Farah', 'Panggungsari', 4948);
insert into offers (id, city_from, city_to, cost) values (304, 'Vynohradiv', 'Mizque', 12564);
insert into offers (id, city_from, city_to, cost) values (305, 'Sande Vila Nova', 'Dolna Banya', 21083);
insert into offers (id, city_from, city_to, cost) values (306, 'Cama Juan', 'Hedi', 10938);
insert into offers (id, city_from, city_to, cost) values (307, 'Kute', 'Muzhijie', 13965);
insert into offers (id, city_from, city_to, cost) values (308, 'Taverny', 'Mukhen', 6911);
insert into offers (id, city_from, city_to, cost) values (309, 'Vila Verde', 'Umeå', 12090);
insert into offers (id, city_from, city_to, cost) values (310, 'Saurama', 'Tomelilla', 1054);
insert into offers (id, city_from, city_to, cost) values (311, 'Aipe', 'Mežica', 10264);
insert into offers (id, city_from, city_to, cost) values (312, 'Toshkivka', 'Khallat Şāliḩ', 4985);
insert into offers (id, city_from, city_to, cost) values (313, 'Betong', 'Oguma', 11374);
insert into offers (id, city_from, city_to, cost) values (314, 'Uberaba', 'Shatou', 19013);
insert into offers (id, city_from, city_to, cost) values (315, 'Akademicheskoe', 'Embu', 18943);
insert into offers (id, city_from, city_to, cost) values (316, 'Lancaster', 'Zhoukoudian', 1749);
insert into offers (id, city_from, city_to, cost) values (317, 'Tongguan', 'Durham', 20905);
insert into offers (id, city_from, city_to, cost) values (318, 'Lappi', 'Barbalha', 18617);
insert into offers (id, city_from, city_to, cost) values (319, 'Bolikhan', 'Itauguá', 22388);
insert into offers (id, city_from, city_to, cost) values (320, 'Anchorage', 'Llazicë', 17440);
insert into offers (id, city_from, city_to, cost) values (321, 'Haizigou', 'Puerto San José', 23240);
insert into offers (id, city_from, city_to, cost) values (322, 'Robatal', 'Klášter', 4244);
insert into offers (id, city_from, city_to, cost) values (323, 'Lélouma', 'Las Matas de Farfán', 16637);
insert into offers (id, city_from, city_to, cost) values (324, 'Freire', 'Villanova', 23881);
insert into offers (id, city_from, city_to, cost) values (325, 'Murzuq', 'Campamento', 20427);
insert into offers (id, city_from, city_to, cost) values (326, 'Macau', 'Genova', 14959);
insert into offers (id, city_from, city_to, cost) values (327, 'Druzhny', 'Kashirskoye', 23492);
insert into offers (id, city_from, city_to, cost) values (328, 'Oropesa', 'Pangian', 21402);
insert into offers (id, city_from, city_to, cost) values (329, 'Bayanhoshuu', 'Arklow', 6118);
insert into offers (id, city_from, city_to, cost) values (330, 'Loma Bonita', 'Três Lagoas', 7751);
insert into offers (id, city_from, city_to, cost) values (331, 'Savran’', 'Hatton', 14580);
insert into offers (id, city_from, city_to, cost) values (332, 'Petushki', 'Lidingö', 20690);
insert into offers (id, city_from, city_to, cost) values (333, 'Dukuhsawah', 'Semampirbarat', 13152);
insert into offers (id, city_from, city_to, cost) values (334, 'Jiangdong', 'Haoguantun', 19238);
insert into offers (id, city_from, city_to, cost) values (335, 'Talca', 'Mbuji-Mayi', 1217);
insert into offers (id, city_from, city_to, cost) values (336, 'Rumilly', 'Taipingguan', 9976);
insert into offers (id, city_from, city_to, cost) values (337, 'Altos', 'Richmond', 1633);
insert into offers (id, city_from, city_to, cost) values (338, 'Safi', 'Qiaotou', 15260);
insert into offers (id, city_from, city_to, cost) values (339, 'Kriel', 'Rawasan', 22849);
insert into offers (id, city_from, city_to, cost) values (340, 'Sovetskiy', 'Líně', 15850);
insert into offers (id, city_from, city_to, cost) values (341, 'Dongyong', 'Miętne', 4275);
insert into offers (id, city_from, city_to, cost) values (342, 'Santa Rosa del Sara', 'Massy', 8139);
insert into offers (id, city_from, city_to, cost) values (343, 'Santa Maria Oliveira', 'Illushi', 14124);
insert into offers (id, city_from, city_to, cost) values (344, 'Tsiatsan', 'Linköping', 5752);
insert into offers (id, city_from, city_to, cost) values (345, 'Wañgan', 'Iznoski', 8741);
insert into offers (id, city_from, city_to, cost) values (346, 'Kosmonosy', 'Ono', 7537);
insert into offers (id, city_from, city_to, cost) values (347, 'Qitan', 'Kourou', 23022);
insert into offers (id, city_from, city_to, cost) values (348, 'Shireet', 'Blainville', 7439);
insert into offers (id, city_from, city_to, cost) values (349, 'Benito Juarez', 'Webuye', 5000);
insert into offers (id, city_from, city_to, cost) values (350, 'Saqqez', 'Villa Hayes', 19194);
insert into offers (id, city_from, city_to, cost) values (351, 'Hulutao', 'Kumberg', 21740);
insert into offers (id, city_from, city_to, cost) values (352, 'Bāglung', 'Salaverry', 17182);
insert into offers (id, city_from, city_to, cost) values (353, 'Lamphun', 'Warung Wetan', 9866);
insert into offers (id, city_from, city_to, cost) values (354, 'Paraisópolis', 'Lydenburg', 22824);
insert into offers (id, city_from, city_to, cost) values (355, 'Ob’', 'Raszków', 1589);
insert into offers (id, city_from, city_to, cost) values (356, 'Margos', 'Arcueil', 16390);
insert into offers (id, city_from, city_to, cost) values (357, 'Buga', 'Jincun', 12041);
insert into offers (id, city_from, city_to, cost) values (358, 'Bojnik', 'Svetlograd', 2723);
insert into offers (id, city_from, city_to, cost) values (359, 'Białośliwie', 'Azogues', 17015);
insert into offers (id, city_from, city_to, cost) values (360, 'Pyzdry', 'Al Funayţīs', 13339);
insert into offers (id, city_from, city_to, cost) values (361, 'Matsena', 'Cortinhas', 7938);
insert into offers (id, city_from, city_to, cost) values (362, 'Tit Mellil', 'Liangguang', 1093);
insert into offers (id, city_from, city_to, cost) values (363, 'Tallbīsah', 'Sumbergebang', 12768);
insert into offers (id, city_from, city_to, cost) values (364, 'Beslan', 'Novotroitsk', 23989);
insert into offers (id, city_from, city_to, cost) values (365, 'Taihu', 'Khŭjand', 19262);
insert into offers (id, city_from, city_to, cost) values (366, 'Fengyi', 'Chuanshan', 18216);
insert into offers (id, city_from, city_to, cost) values (367, 'Nuyno', 'Sioux Falls', 8279);
insert into offers (id, city_from, city_to, cost) values (368, 'Butare', 'Kuandian', 16313);
insert into offers (id, city_from, city_to, cost) values (369, 'Vanderhoof', 'Antang', 11566);
insert into offers (id, city_from, city_to, cost) values (370, 'Tiko', 'Masingbi', 8699);
insert into offers (id, city_from, city_to, cost) values (371, 'Libice nad Cidlinou', 'Puntarenas', 2184);
insert into offers (id, city_from, city_to, cost) values (372, 'Bystré', 'Linköping', 10922);
insert into offers (id, city_from, city_to, cost) values (373, 'Miyakonojō', 'Bistrica pri Tržiču', 8484);
insert into offers (id, city_from, city_to, cost) values (374, 'Fenglai', 'Talin Hiag', 7325);
insert into offers (id, city_from, city_to, cost) values (375, 'Shangsha', 'Buur Gaabo', 10511);
insert into offers (id, city_from, city_to, cost) values (376, 'Xiaogang', 'Patulul', 1564);
insert into offers (id, city_from, city_to, cost) values (377, 'Fontana', 'Gračac', 2006);
insert into offers (id, city_from, city_to, cost) values (378, 'Tatebal', 'Amirabad', 18539);
insert into offers (id, city_from, city_to, cost) values (379, 'Mataguži', 'Kālīganj', 15191);
insert into offers (id, city_from, city_to, cost) values (380, 'Sidi Yahya Ou Saad', 'Tehrān', 20420);
insert into offers (id, city_from, city_to, cost) values (381, 'Taounate', 'Vila Chã de Ourique', 9818);
insert into offers (id, city_from, city_to, cost) values (382, 'Congkar', 'Bato', 3579);
insert into offers (id, city_from, city_to, cost) values (383, 'Sāh', 'Radovitskiy', 8472);
insert into offers (id, city_from, city_to, cost) values (384, 'Guojiaba', 'Xincheng', 9584);
insert into offers (id, city_from, city_to, cost) values (385, 'Burnside', 'Khŭjand', 15080);
insert into offers (id, city_from, city_to, cost) values (386, 'Serednye', 'Novyy Oskol', 20992);
insert into offers (id, city_from, city_to, cost) values (387, 'Chorente', 'Gumdag', 7804);
insert into offers (id, city_from, city_to, cost) values (388, 'Cikaludan', 'Krujë', 9473);
insert into offers (id, city_from, city_to, cost) values (389, 'Sihai', 'Haugesund', 22402);
insert into offers (id, city_from, city_to, cost) values (390, 'Studená', 'Tacna', 18567);
insert into offers (id, city_from, city_to, cost) values (391, 'Hartford', 'Gornje Moštre', 10450);
insert into offers (id, city_from, city_to, cost) values (392, 'Bueng Khong Long', 'Mvuma', 19591);
insert into offers (id, city_from, city_to, cost) values (393, 'Chiguirip', 'Hejiayan', 4469);
insert into offers (id, city_from, city_to, cost) values (394, 'Svoge', 'Chervonoarmiys’k', 426);
insert into offers (id, city_from, city_to, cost) values (395, 'Zaandam', 'Westport', 19950);
insert into offers (id, city_from, city_to, cost) values (396, 'Sanhe', 'Tianzhuang', 21200);
insert into offers (id, city_from, city_to, cost) values (397, 'Wujing', 'Cibanten', 22802);
insert into offers (id, city_from, city_to, cost) values (398, 'Suan Luang', 'Borovichi', 14001);
insert into offers (id, city_from, city_to, cost) values (399, 'Karuri', 'Sabaneta', 7883);
insert into offers (id, city_from, city_to, cost) values (400, 'Katipunan', 'Ujungpangkah', 17939);
insert into offers (id, city_from, city_to, cost) values (401, 'Inriville', 'Del Pilar', 6419);
insert into offers (id, city_from, city_to, cost) values (402, 'Ledenice', 'Gelgaudiškis', 16509);
insert into offers (id, city_from, city_to, cost) values (403, 'Novais', 'Ussel', 5719);
insert into offers (id, city_from, city_to, cost) values (404, 'Savitaipale', 'Miguel Hidalgo', 19503);
insert into offers (id, city_from, city_to, cost) values (405, 'Ibara', 'Karantaba', 21864);
insert into offers (id, city_from, city_to, cost) values (406, 'Nakhon Phanom', 'Jaworzyna Śląska', 14576);
insert into offers (id, city_from, city_to, cost) values (407, 'El Tambo', 'Shicang', 14214);
insert into offers (id, city_from, city_to, cost) values (408, 'Kawangohari', 'Osiek nad Notecią', 5802);
insert into offers (id, city_from, city_to, cost) values (409, 'Zambujal', 'Arrifes', 14941);
insert into offers (id, city_from, city_to, cost) values (410, 'Were', 'Castanheira', 12502);
insert into offers (id, city_from, city_to, cost) values (411, 'Fuerte', 'Taungoo', 14858);
insert into offers (id, city_from, city_to, cost) values (412, 'Maki', 'Macapo', 9090);
insert into offers (id, city_from, city_to, cost) values (413, 'Millerovo', 'Sandefjord', 1751);
insert into offers (id, city_from, city_to, cost) values (414, 'Viga', 'Desnogorsk', 22808);
insert into offers (id, city_from, city_to, cost) values (415, 'Zapolyarnyy', 'Beringinjaya', 12753);
insert into offers (id, city_from, city_to, cost) values (416, 'Camaligan', 'Wola Filipowska', 22546);
insert into offers (id, city_from, city_to, cost) values (417, 'Salgado', 'Babahoyo', 6558);
insert into offers (id, city_from, city_to, cost) values (418, 'Brusyliv', 'Nueva Ocotepeque', 15053);
insert into offers (id, city_from, city_to, cost) values (419, 'Cruz das Almas', 'Alae', 21965);
insert into offers (id, city_from, city_to, cost) values (420, 'Hollola', 'Tartagal', 22310);
insert into offers (id, city_from, city_to, cost) values (421, 'Yaté-Barrage', 'Timur', 2281);
insert into offers (id, city_from, city_to, cost) values (422, 'Stockholm', 'Quince Mil', 21550);
insert into offers (id, city_from, city_to, cost) values (423, 'Medianeira', 'Zel’va', 23229);
insert into offers (id, city_from, city_to, cost) values (424, 'Cicurug', 'Chợ Mới', 21290);
insert into offers (id, city_from, city_to, cost) values (425, 'Herrán', 'Dehī', 5370);
insert into offers (id, city_from, city_to, cost) values (426, 'Thị Trấn Mường Lát', 'Xiapu', 1635);
insert into offers (id, city_from, city_to, cost) values (427, 'Tarfaya', 'Banikoara', 16918);
insert into offers (id, city_from, city_to, cost) values (428, 'Sanxi', 'Monte Francisco', 13264);
insert into offers (id, city_from, city_to, cost) values (429, 'Eg-Uur', 'Mino', 7509);
insert into offers (id, city_from, city_to, cost) values (430, 'Belém', 'Jindong', 6927);
insert into offers (id, city_from, city_to, cost) values (431, 'Yangxi', 'Ōzu', 3560);
insert into offers (id, city_from, city_to, cost) values (432, 'Marseille', 'Montpellier', 5058);
insert into offers (id, city_from, city_to, cost) values (433, 'Norcasia', 'Oke Mesi', 14433);
insert into offers (id, city_from, city_to, cost) values (434, 'Businga', 'Hoit Taria', 10840);
insert into offers (id, city_from, city_to, cost) values (435, 'Ilek', 'Changshengqiao', 23336);
insert into offers (id, city_from, city_to, cost) values (436, 'Dacudao', 'Lille', 22829);
insert into offers (id, city_from, city_to, cost) values (437, 'Lerrnanist', 'Saint Louis', 14868);
insert into offers (id, city_from, city_to, cost) values (438, 'Guantang', 'Steinkjer', 7513);
insert into offers (id, city_from, city_to, cost) values (439, 'Quixeramobim', 'Dajanrurung', 14797);
insert into offers (id, city_from, city_to, cost) values (440, 'Dýšina', 'Bojong', 8799);
insert into offers (id, city_from, city_to, cost) values (441, 'Lingdangge', 'Jixian', 19926);
insert into offers (id, city_from, city_to, cost) values (442, 'Tingzhou', 'Caramanta', 18965);
insert into offers (id, city_from, city_to, cost) values (443, 'Langtad', 'Wulong', 4763);
insert into offers (id, city_from, city_to, cost) values (444, 'Jahāniān Shāh', 'Radamata', 5748);
insert into offers (id, city_from, city_to, cost) values (445, 'Komprachcice', 'Baicaogou', 19522);
insert into offers (id, city_from, city_to, cost) values (446, 'Allealle', 'Montpellier', 21496);
insert into offers (id, city_from, city_to, cost) values (447, 'Insrom', 'Madīnat Ḩamad', 8076);
insert into offers (id, city_from, city_to, cost) values (448, 'Quţūr', 'Comallo', 4321);
insert into offers (id, city_from, city_to, cost) values (449, 'Nantes', 'Calango', 23009);
insert into offers (id, city_from, city_to, cost) values (450, 'Panshi', 'Rontu', 7509);
insert into offers (id, city_from, city_to, cost) values (451, 'Hongqi', 'Taoyuan', 2567);
insert into offers (id, city_from, city_to, cost) values (452, 'Shicheng', 'Dama', 12392);
insert into offers (id, city_from, city_to, cost) values (453, 'Vanves', 'Ixopo', 589);
insert into offers (id, city_from, city_to, cost) values (454, 'Manūjān', 'Irupi', 23712);
insert into offers (id, city_from, city_to, cost) values (455, 'Banga', 'Chowṉêy', 462);
insert into offers (id, city_from, city_to, cost) values (456, 'Santisimo Rosario', 'Färjestaden', 12117);
insert into offers (id, city_from, city_to, cost) values (457, 'Ampasimanolotra', 'Casal de Cambra', 23466);
insert into offers (id, city_from, city_to, cost) values (458, 'Sumenep', 'Bingawan', 6707);
insert into offers (id, city_from, city_to, cost) values (459, 'Yanhe', 'Flying Fish Cove', 22684);
insert into offers (id, city_from, city_to, cost) values (460, 'Cilangkap', 'Andres Bonifacio', 16291);
insert into offers (id, city_from, city_to, cost) values (461, 'Liboro', 'Agra', 5575);
insert into offers (id, city_from, city_to, cost) values (462, 'Saint Hubert', 'Clarin', 20934);
insert into offers (id, city_from, city_to, cost) values (463, 'Pacanga', 'Ḩajjah', 17749);
insert into offers (id, city_from, city_to, cost) values (464, 'Nangxian', 'Laxey', 11063);
insert into offers (id, city_from, city_to, cost) values (465, 'Peace River', 'Chernomorets', 16997);
insert into offers (id, city_from, city_to, cost) values (466, 'Ängelholm', 'Notranje Gorice', 13861);
insert into offers (id, city_from, city_to, cost) values (467, 'Zürich', 'Bombardopolis', 6330);
insert into offers (id, city_from, city_to, cost) values (468, 'Amagbagan', 'Mir', 14881);
insert into offers (id, city_from, city_to, cost) values (469, 'Tres Arroyos', 'Mohelnice', 14858);
insert into offers (id, city_from, city_to, cost) values (470, 'Jahāniān Shāh', 'Huangpo', 16819);
insert into offers (id, city_from, city_to, cost) values (471, 'Kataba', 'Bobai', 5324);
insert into offers (id, city_from, city_to, cost) values (472, 'Vedène', 'Lagdo', 7752);
insert into offers (id, city_from, city_to, cost) values (473, 'Pedreira', 'Baturyn', 12074);
insert into offers (id, city_from, city_to, cost) values (474, 'Soloneshnoye', 'Dobrich', 3288);
insert into offers (id, city_from, city_to, cost) values (475, 'Dawe', 'Rizal', 1496);
insert into offers (id, city_from, city_to, cost) values (476, 'Wedoro', 'Åkersberga', 4425);
insert into offers (id, city_from, city_to, cost) values (477, 'Laya', 'Nagrog', 6530);
insert into offers (id, city_from, city_to, cost) values (478, 'Tiechanggou', 'Manturovo', 7732);
insert into offers (id, city_from, city_to, cost) values (479, 'Minuwangoda', 'Köln', 23574);
insert into offers (id, city_from, city_to, cost) values (480, 'Mancos', 'Ucuncha', 1304);
insert into offers (id, city_from, city_to, cost) values (481, 'Sogcho', 'Arţās', 9515);
insert into offers (id, city_from, city_to, cost) values (482, 'Novi Karlovci', 'Neresnytsya', 14067);
insert into offers (id, city_from, city_to, cost) values (483, 'Mesa', 'Machico', 3139);
insert into offers (id, city_from, city_to, cost) values (484, 'Kentau', 'Kaiyuan', 12177);
insert into offers (id, city_from, city_to, cost) values (485, 'Marcara', 'Taipingying', 4899);
insert into offers (id, city_from, city_to, cost) values (486, 'Oele', 'Xinpu', 23640);
insert into offers (id, city_from, city_to, cost) values (487, 'Krajan Menggare', 'Kabuynan', 18972);
insert into offers (id, city_from, city_to, cost) values (488, 'Sosnovka', 'Blyznyuky', 21708);
insert into offers (id, city_from, city_to, cost) values (489, 'Andkhōy', 'Prata', 6410);
insert into offers (id, city_from, city_to, cost) values (490, 'Guniushan', 'Ōmiya', 10663);
insert into offers (id, city_from, city_to, cost) values (491, 'Sovetskaya', 'Banatsko Karađorđevo', 14029);
insert into offers (id, city_from, city_to, cost) values (492, 'Qujing', 'Carmen', 8984);
insert into offers (id, city_from, city_to, cost) values (493, 'Birmingham', 'Santa Cruz de Barahona', 22244);
insert into offers (id, city_from, city_to, cost) values (494, 'Jiuhe', 'Pokrovskoye-Streshnëvo', 459);
insert into offers (id, city_from, city_to, cost) values (495, 'Barbosa', 'Baranoa', 11031);
insert into offers (id, city_from, city_to, cost) values (496, 'Manadhoo', 'Tiwi', 9884);
insert into offers (id, city_from, city_to, cost) values (497, 'Bayeux', 'Xianyi', 15120);
insert into offers (id, city_from, city_to, cost) values (498, 'Mazyr', 'Qiaoyi', 3099);
insert into offers (id, city_from, city_to, cost) values (499, 'Emalgolin Mongolzuxiang', 'Tiadiaye', 11326);
insert into offers (id, city_from, city_to, cost) values (500, 'Morropón', 'Älvsjö', 7937);
insert into offers (id, city_from, city_to, cost) values (501, 'Nogueira', 'Yanac', 20427);
insert into offers (id, city_from, city_to, cost) values (502, 'Pongkor', 'Hồ Xá', 3563);
insert into offers (id, city_from, city_to, cost) values (503, 'Sumberpitu', 'Kafr Sawm', 14140);
insert into offers (id, city_from, city_to, cost) values (504, 'Gon’ba', 'Meaux', 14470);
insert into offers (id, city_from, city_to, cost) values (505, 'Longqiao', 'Yonghe', 20756);
insert into offers (id, city_from, city_to, cost) values (506, 'Barcin', 'Marapanim', 14155);
insert into offers (id, city_from, city_to, cost) values (507, 'Ciénaga de Oro', 'Almeirim', 14852);
insert into offers (id, city_from, city_to, cost) values (508, 'Radiměř', 'Manquiring', 10821);
insert into offers (id, city_from, city_to, cost) values (509, 'Greytown', 'Falun', 13029);
insert into offers (id, city_from, city_to, cost) values (510, 'Roma', 'Paoua', 4009);
insert into offers (id, city_from, city_to, cost) values (511, 'Rio Branco do Sul', 'Hayama', 21454);
insert into offers (id, city_from, city_to, cost) values (512, 'Picton', 'Ishqoshim', 17300);
insert into offers (id, city_from, city_to, cost) values (513, 'Pazin', 'Gaobu', 14003);
insert into offers (id, city_from, city_to, cost) values (514, 'Oslo', 'Pereira Barreto', 5579);
insert into offers (id, city_from, city_to, cost) values (515, 'Sơn Tịnh', 'Kulykiv', 23618);
insert into offers (id, city_from, city_to, cost) values (516, 'Phù Cát', 'Tielong', 2259);
insert into offers (id, city_from, city_to, cost) values (517, 'Živinice', 'Cabimas', 5342);
insert into offers (id, city_from, city_to, cost) values (518, 'Budapest', 'Madrid', 4368);
insert into offers (id, city_from, city_to, cost) values (519, 'Taposan', 'Yajiang', 10613);
insert into offers (id, city_from, city_to, cost) values (520, 'Umeå', 'Pelasgía', 15926);
insert into offers (id, city_from, city_to, cost) values (521, 'Iktābah', 'San Rafael Arriba', 17663);
insert into offers (id, city_from, city_to, cost) values (522, 'Ciudad Nueva', 'Bantar', 494);
insert into offers (id, city_from, city_to, cost) values (523, 'El Viejo', 'Jiḩānah', 12522);
insert into offers (id, city_from, city_to, cost) values (524, 'Aguachica', 'Xinglongjie', 13828);
insert into offers (id, city_from, city_to, cost) values (525, 'Marseille', 'Přibyslav', 8375);
insert into offers (id, city_from, city_to, cost) values (526, 'Hafrsfjord', 'Banepa', 13916);
insert into offers (id, city_from, city_to, cost) values (527, 'Nesovice', 'Córdoba', 6302);
insert into offers (id, city_from, city_to, cost) values (528, 'Limoges', 'Tvŭrditsa', 14868);
insert into offers (id, city_from, city_to, cost) values (529, 'Baykonyr', 'Čair', 9325);
insert into offers (id, city_from, city_to, cost) values (530, 'Kofelē', 'Starobelokurikha', 12525);
insert into offers (id, city_from, city_to, cost) values (531, 'Tarauacá', 'Lobitos', 9104);
insert into offers (id, city_from, city_to, cost) values (532, 'Göteborg', 'Cibodas', 5465);
insert into offers (id, city_from, city_to, cost) values (533, 'Kurchaloy', 'Kambove', 14766);
insert into offers (id, city_from, city_to, cost) values (534, 'Wonorejo', 'Trà Vinh', 6559);
insert into offers (id, city_from, city_to, cost) values (535, 'Caocun', 'Rust’avi', 21678);
insert into offers (id, city_from, city_to, cost) values (536, 'Natu', 'Jinqu', 17143);
insert into offers (id, city_from, city_to, cost) values (537, 'Malonty', 'Marttila', 7525);
insert into offers (id, city_from, city_to, cost) values (538, 'Paulba', 'Osorno', 18650);
insert into offers (id, city_from, city_to, cost) values (539, 'Betong', 'Sapouy', 13118);
insert into offers (id, city_from, city_to, cost) values (540, 'Balaklava', 'Santa Cruz del Quiché', 3809);
insert into offers (id, city_from, city_to, cost) values (541, 'Bogorame', 'New Orleans', 20880);
insert into offers (id, city_from, city_to, cost) values (542, 'Hetou', 'Téra', 2867);
insert into offers (id, city_from, city_to, cost) values (543, 'Bagou', 'Basel', 23150);
insert into offers (id, city_from, city_to, cost) values (544, 'Xushuguan', 'Káto Miliá', 22938);
insert into offers (id, city_from, city_to, cost) values (545, 'Heqing', 'Kortowo', 13405);
insert into offers (id, city_from, city_to, cost) values (546, 'Al Ḩusayn', 'Osilnica', 16115);
insert into offers (id, city_from, city_to, cost) values (547, 'Santa Ana', 'Nîmes', 8357);
insert into offers (id, city_from, city_to, cost) values (548, 'Pompéu', 'Sangju', 1524);
insert into offers (id, city_from, city_to, cost) values (549, 'Amper', 'Phong Điền', 11941);
insert into offers (id, city_from, city_to, cost) values (550, 'Las Vegas', 'Münster', 22236);
insert into offers (id, city_from, city_to, cost) values (551, 'Abucayan', 'Iporã', 1224);
insert into offers (id, city_from, city_to, cost) values (552, 'Jinqiao', 'Kampungraja', 22341);
insert into offers (id, city_from, city_to, cost) values (553, 'Göteborg', 'Porto Real', 20459);
insert into offers (id, city_from, city_to, cost) values (554, 'Leiden', 'Andkhōy', 6423);
insert into offers (id, city_from, city_to, cost) values (555, 'Dali', 'Barinitas', 23229);
insert into offers (id, city_from, city_to, cost) values (556, 'Jamundí', 'Wuqiao', 15753);
insert into offers (id, city_from, city_to, cost) values (557, 'Seget', 'Xingou', 5968);
insert into offers (id, city_from, city_to, cost) values (558, 'Tarica', 'Nampera', 22305);
insert into offers (id, city_from, city_to, cost) values (559, 'Dazaifu', 'Limache', 10796);
insert into offers (id, city_from, city_to, cost) values (560, 'Zhenkou', 'Pregradnaya', 21773);
insert into offers (id, city_from, city_to, cost) values (561, 'Obernai', 'Kotkot', 14127);
insert into offers (id, city_from, city_to, cost) values (562, 'Santa Lucía Cotzumalguapa', 'Leiguan', 6532);
insert into offers (id, city_from, city_to, cost) values (563, 'Zhongshu', 'Rupe', 7703);
insert into offers (id, city_from, city_to, cost) values (564, 'Łomianki', 'Quintães', 3333);
insert into offers (id, city_from, city_to, cost) values (565, 'Stockholm', 'Petaling Jaya', 7304);
insert into offers (id, city_from, city_to, cost) values (566, 'Xingguo', 'Göteborg', 19011);
insert into offers (id, city_from, city_to, cost) values (567, 'Bankeryd', 'Bintulu', 11156);
insert into offers (id, city_from, city_to, cost) values (568, 'Battaramulla South', 'Estância', 18554);
insert into offers (id, city_from, city_to, cost) values (569, 'Ágios Stéfanos', 'Sanxi', 9317);
insert into offers (id, city_from, city_to, cost) values (570, 'A dos Cunhados', 'Ta’ Xbiex', 10715);
insert into offers (id, city_from, city_to, cost) values (571, 'Impalutao', 'Pālang', 1791);
insert into offers (id, city_from, city_to, cost) values (572, 'Riosucio', 'Jatiraya', 22751);
insert into offers (id, city_from, city_to, cost) values (573, 'Grande Prairie', 'Karanganyar', 20769);
insert into offers (id, city_from, city_to, cost) values (574, 'Tianfu', 'Sawo', 11159);
insert into offers (id, city_from, city_to, cost) values (575, 'Castlebellingham', 'Mancagahar', 5550);
insert into offers (id, city_from, city_to, cost) values (576, 'Broska', 'Sitovo', 4364);
insert into offers (id, city_from, city_to, cost) values (577, 'Borås', 'Jianxin', 20704);
insert into offers (id, city_from, city_to, cost) values (578, 'Strezhevoy', 'Aomori Shi', 6320);
insert into offers (id, city_from, city_to, cost) values (579, 'Luzhany', 'North Cowichan', 10543);
insert into offers (id, city_from, city_to, cost) values (580, 'Kihniö', 'Cool űrhajó', 2869);
insert into offers (id, city_from, city_to, cost) values (581, 'Chase', 'Nantes', 19355);
insert into offers (id, city_from, city_to, cost) values (582, 'Liusi', 'Oumé', 11559);
insert into offers (id, city_from, city_to, cost) values (583, 'Libacao', 'Xiaohebian', 16207);
insert into offers (id, city_from, city_to, cost) values (584, 'Petrovskoye', 'Trondheim', 13637);
insert into offers (id, city_from, city_to, cost) values (585, 'Strängnäs', 'Xiaogang', 19317);
insert into offers (id, city_from, city_to, cost) values (586, 'Navegantes', 'Tigbaw', 18274);
insert into offers (id, city_from, city_to, cost) values (587, 'Milton', 'Lescar', 17251);
insert into offers (id, city_from, city_to, cost) values (588, 'Chelopech', 'Kanshan', 3812);
insert into offers (id, city_from, city_to, cost) values (589, 'Jianjun', 'Baisha', 18377);
insert into offers (id, city_from, city_to, cost) values (590, 'Makarov', 'Maofan', 23273);
insert into offers (id, city_from, city_to, cost) values (591, 'Hushi', 'Vysokogornyy', 15797);
insert into offers (id, city_from, city_to, cost) values (592, 'Majur', 'Yufa', 13381);
insert into offers (id, city_from, city_to, cost) values (593, 'Fengyan', 'Luzern', 13850);
insert into offers (id, city_from, city_to, cost) values (594, 'Schœlcher', 'Liurenba', 6719);
insert into offers (id, city_from, city_to, cost) values (595, 'Guantouzui', 'Yufrus', 19070);
insert into offers (id, city_from, city_to, cost) values (596, 'Anqing', 'Kozje', 1210);
insert into offers (id, city_from, city_to, cost) values (597, 'Évosmos', 'Noemuti', 19268);
insert into offers (id, city_from, city_to, cost) values (598, 'Hutou', 'Neundeut', 4313);
insert into offers (id, city_from, city_to, cost) values (599, 'Manganitu', 'Duwe', 5386);
insert into offers (id, city_from, city_to, cost) values (600, 'Sudzha', 'Bègles', 10767);
insert into offers (id, city_from, city_to, cost) values (601, 'Lutowiska', 'Cibebek', 4336);
insert into offers (id, city_from, city_to, cost) values (602, 'Maiyema', 'Gaoliang', 17487);
insert into offers (id, city_from, city_to, cost) values (603, 'Changbu', 'Kwakoa', 11295);
insert into offers (id, city_from, city_to, cost) values (604, 'Zolotkovo', 'Wangying', 22235);
insert into offers (id, city_from, city_to, cost) values (605, 'Ipil', 'Villa La Angostura', 6853);
insert into offers (id, city_from, city_to, cost) values (606, 'Wysoka', 'Ciwidara', 12336);
insert into offers (id, city_from, city_to, cost) values (607, 'Solok Timur', 'Tongchuan', 5403);
insert into offers (id, city_from, city_to, cost) values (608, 'Argentan', 'Portela', 23596);
insert into offers (id, city_from, city_to, cost) values (609, 'Seremban', 'Villasis', 15264);
insert into offers (id, city_from, city_to, cost) values (610, 'Quỳ Châu', 'Muzambinho', 2712);
insert into offers (id, city_from, city_to, cost) values (611, 'Choszczno', 'Grand Rapids', 22230);
insert into offers (id, city_from, city_to, cost) values (612, 'Malasiqui', 'Limatambo', 10354);
insert into offers (id, city_from, city_to, cost) values (613, 'Homagama', 'Buriwutung', 3341);
insert into offers (id, city_from, city_to, cost) values (614, 'El Bauga', 'Mingelchaur', 21931);
insert into offers (id, city_from, city_to, cost) values (615, 'Springbok', 'Arlöv', 22400);
insert into offers (id, city_from, city_to, cost) values (616, 'Little Baguio', 'Mikun’', 21896);
insert into offers (id, city_from, city_to, cost) values (617, 'Karangampel', 'Batusangkar', 20884);
insert into offers (id, city_from, city_to, cost) values (618, 'Mouhijärvi', 'Yuyangguan', 11761);
insert into offers (id, city_from, city_to, cost) values (619, 'Urrô', 'Barang', 20069);
insert into offers (id, city_from, city_to, cost) values (620, 'Tân Châu', 'Bromma', 1504);
insert into offers (id, city_from, city_to, cost) values (621, 'Tisul’', 'Shanxia', 5783);
insert into offers (id, city_from, city_to, cost) values (622, 'São Roque', 'Santiago', 12021);
insert into offers (id, city_from, city_to, cost) values (623, 'Horní Čermná', 'Leticia', 16484);
insert into offers (id, city_from, city_to, cost) values (624, 'Viçosa do Ceará', 'Ndeaboh', 811);
insert into offers (id, city_from, city_to, cost) values (625, 'Sombor', 'El Alto', 5408);
insert into offers (id, city_from, city_to, cost) values (626, 'Trzciana', 'Nariño', 12018);
insert into offers (id, city_from, city_to, cost) values (627, 'Shanxiahu', 'Evxinoúpolis', 4608);
insert into offers (id, city_from, city_to, cost) values (628, 'Utabi', 'Waajid', 1114);
insert into offers (id, city_from, city_to, cost) values (629, 'Dadeldhurā', 'Altunemil', 21640);
insert into offers (id, city_from, city_to, cost) values (630, 'Jambangan', 'Pingfeng', 5853);
insert into offers (id, city_from, city_to, cost) values (631, 'Fatikchari', 'Uritsk', 14271);
insert into offers (id, city_from, city_to, cost) values (632, 'Abū Ghaush', 'Świdnica', 13032);
insert into offers (id, city_from, city_to, cost) values (633, 'Shache', 'Sanjiazi', 12825);
insert into offers (id, city_from, city_to, cost) values (634, 'Zhaoyuan', 'Babice', 17827);
insert into offers (id, city_from, city_to, cost) values (635, 'Enonkoski', 'Pingyi', 19031);
insert into offers (id, city_from, city_to, cost) values (636, 'Situ', 'Huaping', 9537);
insert into offers (id, city_from, city_to, cost) values (637, 'Zhongzhai', 'Lakinsk', 15235);
insert into offers (id, city_from, city_to, cost) values (638, 'Plumtree', 'Kisumu', 22197);
insert into offers (id, city_from, city_to, cost) values (639, 'Silao', 'Cipinang', 5451);
insert into offers (id, city_from, city_to, cost) values (640, 'Bartsrashen', 'Ulimonong', 6626);
insert into offers (id, city_from, city_to, cost) values (641, 'Ceres', 'Tangpu', 411);
insert into offers (id, city_from, city_to, cost) values (642, 'Lobuk', 'Oemanu', 5928);
insert into offers (id, city_from, city_to, cost) values (643, 'Sendung', 'Huanghuatan', 8451);
insert into offers (id, city_from, city_to, cost) values (644, 'Gandra', 'Xiangyangpu', 19251);
insert into offers (id, city_from, city_to, cost) values (645, 'Bengga', 'Dupnitsa', 5470);
insert into offers (id, city_from, city_to, cost) values (646, 'Dobrzyca', 'Melun', 9436);
insert into offers (id, city_from, city_to, cost) values (647, 'Pamiątkowo', 'Lalig', 18795);
insert into offers (id, city_from, city_to, cost) values (648, 'Pinheiro', 'Farah', 19751);
insert into offers (id, city_from, city_to, cost) values (649, 'Tambo', 'Picoto', 21983);
insert into offers (id, city_from, city_to, cost) values (650, 'Drakino', 'Shanxi', 11810);
insert into offers (id, city_from, city_to, cost) values (651, 'Ruukki', 'Wenling', 10361);
insert into offers (id, city_from, city_to, cost) values (652, 'Água de Pau', 'Baisha', 16759);
insert into offers (id, city_from, city_to, cost) values (653, 'Sathon', 'Kabacan', 3563);
insert into offers (id, city_from, city_to, cost) values (654, 'Akriní', 'Tombu', 3131);
insert into offers (id, city_from, city_to, cost) values (655, 'Novaya Usman’', 'Angan', 19632);
insert into offers (id, city_from, city_to, cost) values (656, 'Rennes', 'Yangchun', 11611);
insert into offers (id, city_from, city_to, cost) values (657, 'Formosa', 'General Alvear', 3577);
insert into offers (id, city_from, city_to, cost) values (658, 'Parchowo', 'Göteborg', 13378);
insert into offers (id, city_from, city_to, cost) values (659, 'Chuqui Chuqui', 'Obertyn', 13876);
insert into offers (id, city_from, city_to, cost) values (660, 'Lyuban’', 'Saint-Malo', 6850);
insert into offers (id, city_from, city_to, cost) values (661, 'Solna', 'Hamburg Harvestehude', 16478);
insert into offers (id, city_from, city_to, cost) values (662, 'Leeuwarden', 'Vila Velha', 21518);
insert into offers (id, city_from, city_to, cost) values (663, 'Semikarakorsk', 'Prusice', 16521);
insert into offers (id, city_from, city_to, cost) values (664, 'Yefimovskiy', 'Tujing', 8186);
insert into offers (id, city_from, city_to, cost) values (665, 'Warung Wetan', 'Luxi', 9473);
insert into offers (id, city_from, city_to, cost) values (666, 'Zlechov', 'Henggang', 21482);
insert into offers (id, city_from, city_to, cost) values (667, 'Cavan', 'Ōta', 17862);
insert into offers (id, city_from, city_to, cost) values (668, 'El Limon', 'Slobodka', 18031);
insert into offers (id, city_from, city_to, cost) values (669, 'Cabouco', 'Qianchuan', 5375);
insert into offers (id, city_from, city_to, cost) values (670, 'Subusub', 'Jinping', 5492);
insert into offers (id, city_from, city_to, cost) values (671, 'Hot', 'Valcheta', 18354);
insert into offers (id, city_from, city_to, cost) values (672, 'Lebedinovka', 'Huohua', 23797);
insert into offers (id, city_from, city_to, cost) values (673, 'Kovářská', 'Bucaramanga', 19678);
insert into offers (id, city_from, city_to, cost) values (674, 'Josefina', 'Jevišovice', 6080);
insert into offers (id, city_from, city_to, cost) values (675, 'Trenton', 'Presnenskiy', 1608);
insert into offers (id, city_from, city_to, cost) values (676, 'Bromma', 'Mikołów', 21779);
insert into offers (id, city_from, city_to, cost) values (677, 'Jia’an', 'Sungai Raya', 5094);
insert into offers (id, city_from, city_to, cost) values (678, 'Wąbrzeźno', 'Yanqul', 6287);
insert into offers (id, city_from, city_to, cost) values (679, 'Malāyer', 'Sidrolândia', 10223);
insert into offers (id, city_from, city_to, cost) values (680, 'Dingshan', 'Jundian', 8265);
insert into offers (id, city_from, city_to, cost) values (681, 'Arapiraca', 'Drajak', 14734);
insert into offers (id, city_from, city_to, cost) values (682, 'Giado', 'Elverum', 3011);
insert into offers (id, city_from, city_to, cost) values (683, 'Tarikolot', 'Pakis', 23927);
insert into offers (id, city_from, city_to, cost) values (684, 'Tanggungrejo', 'Sarilhos Grandes', 10532);
insert into offers (id, city_from, city_to, cost) values (685, 'Vacaria', 'Langchi', 13271);
insert into offers (id, city_from, city_to, cost) values (686, 'Ketawang', 'Mīr Bachah Kōṯ', 17837);
insert into offers (id, city_from, city_to, cost) values (687, 'Youhao', 'Compiègne', 8461);
insert into offers (id, city_from, city_to, cost) values (688, 'Kwangmyŏng', 'Kŭlob', 2633);
insert into offers (id, city_from, city_to, cost) values (689, 'Borås', 'Gunungmenang', 23093);
insert into offers (id, city_from, city_to, cost) values (690, 'Wangshi', 'Tarrafal de São Nicolau', 22224);
insert into offers (id, city_from, city_to, cost) values (691, 'San Jose', 'Caetité', 13326);
insert into offers (id, city_from, city_to, cost) values (692, 'Kalodu', 'Valença', 6104);
insert into offers (id, city_from, city_to, cost) values (693, 'Lào Cai', 'Placetas', 22431);
insert into offers (id, city_from, city_to, cost) values (694, 'San Miguel', 'Al Muwayh', 9806);
insert into offers (id, city_from, city_to, cost) values (695, 'Nagbacalan', 'Rybatskoye', 8965);
insert into offers (id, city_from, city_to, cost) values (696, 'Watangan', 'Aygek', 17302);
insert into offers (id, city_from, city_to, cost) values (697, 'Jamaica', 'Flagstaff', 18560);
insert into offers (id, city_from, city_to, cost) values (698, 'Kos', 'Witzenhausen', 14194);
insert into offers (id, city_from, city_to, cost) values (699, 'Jarošov nad Nežárkou', 'Mandal', 1193);
insert into offers (id, city_from, city_to, cost) values (700, 'San Francisco', 'Dallas', 19409);
insert into offers (id, city_from, city_to, cost) values (701, 'Algeciras', 'Imbituva', 1689);
insert into offers (id, city_from, city_to, cost) values (702, 'Huaqiao', 'Armavir', 7841);
insert into offers (id, city_from, city_to, cost) values (703, 'Dampol', 'Nacka', 8159);
insert into offers (id, city_from, city_to, cost) values (704, 'Registro', 'Wangqingtuo', 1589);
insert into offers (id, city_from, city_to, cost) values (705, 'Pyskowice', 'Guanmiao', 23754);
insert into offers (id, city_from, city_to, cost) values (706, 'Dabou', 'Suvorovo', 9076);
insert into offers (id, city_from, city_to, cost) values (707, 'Zhongshan', 'Sagbayan', 9566);
insert into offers (id, city_from, city_to, cost) values (708, 'Parrita', 'Mlanggeng', 13460);
insert into offers (id, city_from, city_to, cost) values (709, 'Tuplice', 'Ifanadiana', 13265);
insert into offers (id, city_from, city_to, cost) values (710, 'Vinkkilä', 'Banzhong', 20838);
insert into offers (id, city_from, city_to, cost) values (711, 'Priyutovo', 'Budapest', 20931);
insert into offers (id, city_from, city_to, cost) values (712, 'Huangdu', 'Persen', 561);
insert into offers (id, city_from, city_to, cost) values (713, 'Barcin', 'Värmdö', 955);
insert into offers (id, city_from, city_to, cost) values (714, 'Wissembourg', 'Ikalamavony', 2677);
insert into offers (id, city_from, city_to, cost) values (715, 'Coronel Martínez', 'Severo-Zadonsk', 20256);
insert into offers (id, city_from, city_to, cost) values (716, 'Tanxi', 'Foluo', 8165);
insert into offers (id, city_from, city_to, cost) values (717, 'Deep River', 'Thị Trấn Phước Bửu', 7196);
insert into offers (id, city_from, city_to, cost) values (718, 'Daban', 'Nangxian', 4390);
insert into offers (id, city_from, city_to, cost) values (719, 'Carabayllo', 'Foz Giraldo', 6057);
insert into offers (id, city_from, city_to, cost) values (720, 'Äänekoski', 'Providencia', 23538);
insert into offers (id, city_from, city_to, cost) values (721, 'Lysekil', 'Batasan Bata', 20148);
insert into offers (id, city_from, city_to, cost) values (722, 'Providencia', 'Sātkania', 22704);
insert into offers (id, city_from, city_to, cost) values (723, 'Arauquita', 'Kangxung', 7268);
insert into offers (id, city_from, city_to, cost) values (724, 'Feni', 'Zhonghe', 4989);
insert into offers (id, city_from, city_to, cost) values (725, 'Villa Ángela', 'Santyoku', 20269);
insert into offers (id, city_from, city_to, cost) values (726, 'Babakanloa', 'Jialu', 5213);
insert into offers (id, city_from, city_to, cost) values (727, 'Godziszów Pierwszy', 'San Luis del Palmar', 927);
insert into offers (id, city_from, city_to, cost) values (728, 'Landskrona', 'Riangbao', 6777);
insert into offers (id, city_from, city_to, cost) values (729, 'Itabira', 'Iperó', 7840);
insert into offers (id, city_from, city_to, cost) values (730, 'Jinan-gun', 'Andrijevica', 6142);
insert into offers (id, city_from, city_to, cost) values (731, 'Novotitarovskaya', 'Svenljunga', 17489);
insert into offers (id, city_from, city_to, cost) values (732, 'Marseille', 'Saint Helier', 14521);
insert into offers (id, city_from, city_to, cost) values (733, 'Xinzhai', 'Falun', 6999);
insert into offers (id, city_from, city_to, cost) values (734, 'Fëdorovskoye', 'Tuanjie', 985);
insert into offers (id, city_from, city_to, cost) values (735, 'Yihe', 'Kertosari', 8736);
insert into offers (id, city_from, city_to, cost) values (736, 'Zhoupi', 'Chambéry', 12933);
insert into offers (id, city_from, city_to, cost) values (737, 'Blaye', 'Kalajoki', 16322);
insert into offers (id, city_from, city_to, cost) values (738, 'Smokvica', 'Krajan Ngrambingan', 14224);
insert into offers (id, city_from, city_to, cost) values (739, 'Straszydle', 'Yitang', 14414);
insert into offers (id, city_from, city_to, cost) values (740, 'Qingyang', 'Xinquansi', 4147);
insert into offers (id, city_from, city_to, cost) values (741, 'Longvic', 'Santo Tomas', 1147);
insert into offers (id, city_from, city_to, cost) values (742, 'Puyuan', 'Maragogi', 13335);
insert into offers (id, city_from, city_to, cost) values (743, 'Chimen', 'Itapevi', 2197);
insert into offers (id, city_from, city_to, cost) values (744, 'Aubergenville', 'Putinci', 17432);
insert into offers (id, city_from, city_to, cost) values (745, 'Xiaotao', 'Nazaré', 6133);
insert into offers (id, city_from, city_to, cost) values (746, 'Guiuan', 'Yelenendorf', 10886);
insert into offers (id, city_from, city_to, cost) values (747, 'Ribamar', 'Anliang', 20274);
insert into offers (id, city_from, city_to, cost) values (748, 'Karangranjong', 'São João del Rei', 2394);
insert into offers (id, city_from, city_to, cost) values (749, 'Monticello', 'Eustaquio Lopez', 16431);
insert into offers (id, city_from, city_to, cost) values (750, 'Porto Salvo', 'Rambatan', 17119);
insert into offers (id, city_from, city_to, cost) values (751, 'Užice', 'Citundun', 18031);
insert into offers (id, city_from, city_to, cost) values (752, 'Bengga', 'Wufeng', 13433);
insert into offers (id, city_from, city_to, cost) values (753, 'Sanxi', 'Zhufo', 14524);
insert into offers (id, city_from, city_to, cost) values (754, 'Huasahuasi', 'Buyant', 9214);
insert into offers (id, city_from, city_to, cost) values (755, 'Xishanzui', 'Bolekhiv', 5128);
insert into offers (id, city_from, city_to, cost) values (756, 'Agpangi', 'Cortes', 21484);
insert into offers (id, city_from, city_to, cost) values (757, 'Smithers', 'Mantang', 18225);
insert into offers (id, city_from, city_to, cost) values (758, 'Dongtundu', 'Leer', 12009);
insert into offers (id, city_from, city_to, cost) values (759, 'Kurnāz', 'Talcahuano', 21845);
insert into offers (id, city_from, city_to, cost) values (760, 'Maiwal', 'Tha Luang', 5783);
insert into offers (id, city_from, city_to, cost) values (761, 'Kuwayris Sharqī', 'Banjar Anyar', 10178);
insert into offers (id, city_from, city_to, cost) values (762, 'Turku', 'Placencia', 8070);
insert into offers (id, city_from, city_to, cost) values (763, 'Chuncheon', 'San Julian', 1154);
insert into offers (id, city_from, city_to, cost) values (764, 'Bershet’', 'Załuski', 5892);
insert into offers (id, city_from, city_to, cost) values (765, 'Mao’ershan', 'Khemisset', 18494);
insert into offers (id, city_from, city_to, cost) values (766, 'Rodhítsa', 'Monte Santo de Minas', 13837);
insert into offers (id, city_from, city_to, cost) values (767, 'Daguo', 'Keelung', 5502);
insert into offers (id, city_from, city_to, cost) values (768, 'Sirari', 'Eustaquio Lopez', 13579);
insert into offers (id, city_from, city_to, cost) values (769, 'Dolores', 'Longquan', 18224);
insert into offers (id, city_from, city_to, cost) values (770, 'Rakhmanovo', 'Mesker-Yurt', 12430);
insert into offers (id, city_from, city_to, cost) values (771, 'Pruzhany', 'Hisings Kärra', 8176);
insert into offers (id, city_from, city_to, cost) values (772, 'Velké Němčice', 'Cabañas', 3239);
insert into offers (id, city_from, city_to, cost) values (773, 'Kuanfatu', 'Itabira', 6725);
insert into offers (id, city_from, city_to, cost) values (774, 'Shibetsu', 'São Lourenço da Mata', 6376);
insert into offers (id, city_from, city_to, cost) values (775, 'Muslyumovo', 'Kobayashi', 12085);
insert into offers (id, city_from, city_to, cost) values (776, 'Hokor', 'Hongshi', 5328);
insert into offers (id, city_from, city_to, cost) values (777, 'Nanterre', 'Barcelona', 5951);
insert into offers (id, city_from, city_to, cost) values (778, 'Qalyūb', 'Changzhi', 5795);
insert into offers (id, city_from, city_to, cost) values (779, 'Kovilj', 'Vila Chã do Monte', 9672);
insert into offers (id, city_from, city_to, cost) values (780, 'Ippy', 'La Vega', 12553);
insert into offers (id, city_from, city_to, cost) values (781, 'Haihui', 'Italó', 20548);
insert into offers (id, city_from, city_to, cost) values (782, 'Lincheng', 'Maţāy', 13930);
insert into offers (id, city_from, city_to, cost) values (783, 'Abakan', 'Przemków', 4446);
insert into offers (id, city_from, city_to, cost) values (784, 'Independencia', 'Pasuruan', 4281);
insert into offers (id, city_from, city_to, cost) values (785, 'Fonseca', 'Patos', 20991);
insert into offers (id, city_from, city_to, cost) values (786, 'Zhongshi', 'Bacacay', 5680);
insert into offers (id, city_from, city_to, cost) values (787, 'Suka Makmue', 'Czerniejewo', 3707);
insert into offers (id, city_from, city_to, cost) values (788, 'La Guadalupe', 'Qinjia', 22447);
insert into offers (id, city_from, city_to, cost) values (789, 'Jasienica', 'Hualgayoc', 6222);
insert into offers (id, city_from, city_to, cost) values (790, 'Nova Petrópolis', 'Empangeni', 5061);
insert into offers (id, city_from, city_to, cost) values (791, 'Thị Trấn Mỹ Lộc', 'Huanshan', 8834);
insert into offers (id, city_from, city_to, cost) values (792, 'Simão Dias', 'Semiluki', 20481);
insert into offers (id, city_from, city_to, cost) values (793, 'Taza', 'Yunxi', 18120);
insert into offers (id, city_from, city_to, cost) values (794, 'Encañada', 'Muravlenko', 23554);
insert into offers (id, city_from, city_to, cost) values (795, 'Las Flores', 'Wang Yang', 2148);
insert into offers (id, city_from, city_to, cost) values (796, 'Kalá Déndra', 'Anyu', 8713);
insert into offers (id, city_from, city_to, cost) values (797, 'Yushikalasu', 'Salto', 5947);
insert into offers (id, city_from, city_to, cost) values (798, 'Wołczyn', 'Guanshan', 6001);
insert into offers (id, city_from, city_to, cost) values (799, 'Morteros', 'Caoxi', 20497);
insert into offers (id, city_from, city_to, cost) values (800, 'Landskrona', 'Pacatuba', 17928);
insert into offers (id, city_from, city_to, cost) values (801, 'Marka', 'Saint-Flour', 16320);
insert into offers (id, city_from, city_to, cost) values (802, 'Algeciras', 'Ed', 8439);
insert into offers (id, city_from, city_to, cost) values (803, 'Nāḩiyat Alī ash Sharqī', 'Berëzovskiy', 14355);
insert into offers (id, city_from, city_to, cost) values (804, 'Istaravshan', 'Gavião', 4266);
insert into offers (id, city_from, city_to, cost) values (805, 'Miasskoye', 'Abaetetuba', 3881);
insert into offers (id, city_from, city_to, cost) values (806, 'Cibodas', 'Bubullimë', 22341);
insert into offers (id, city_from, city_to, cost) values (807, 'Limulan', 'San Marcos', 1146);
insert into offers (id, city_from, city_to, cost) values (808, 'Selemadeg Kelod', 'Tanxi', 637);
insert into offers (id, city_from, city_to, cost) values (809, 'Trinidad', 'Kujama', 11663);
insert into offers (id, city_from, city_to, cost) values (810, 'Lezhu', 'Igoumenítsa', 12915);
insert into offers (id, city_from, city_to, cost) values (811, 'Göteborg', 'As Sukhnah', 8394);
insert into offers (id, city_from, city_to, cost) values (812, 'Clermont-Ferrand', 'Huanchillas', 15259);
insert into offers (id, city_from, city_to, cost) values (813, 'Takahata', 'Mella', 5777);
insert into offers (id, city_from, city_to, cost) values (814, 'Nezamyslice', 'Mislak', 21041);
insert into offers (id, city_from, city_to, cost) values (815, 'Banjar Medura', 'Tabou', 5922);
insert into offers (id, city_from, city_to, cost) values (816, 'Bajram Curri', 'Aragua de Barcelona', 22400);
insert into offers (id, city_from, city_to, cost) values (817, 'Świętajno', 'Dukou', 2674);
insert into offers (id, city_from, city_to, cost) values (818, 'Bulacan', 'Shadili', 438);
insert into offers (id, city_from, city_to, cost) values (819, 'Mardakyany', 'Pasongsongan', 728);
insert into offers (id, city_from, city_to, cost) values (820, 'Qinā', 'Nice', 18925);
insert into offers (id, city_from, city_to, cost) values (821, 'Annopol', 'Semibratovo', 15170);
insert into offers (id, city_from, city_to, cost) values (822, 'Daveluyville', 'Spånga', 10754);
insert into offers (id, city_from, city_to, cost) values (823, 'Lazaro Cardenas', 'Carusucan', 3704);
insert into offers (id, city_from, city_to, cost) values (824, 'Manisi', 'Yanda Bayo', 15687);
insert into offers (id, city_from, city_to, cost) values (825, 'Changfeng', 'Wasior', 8120);
insert into offers (id, city_from, city_to, cost) values (826, 'Maradabangga', 'København', 19651);
insert into offers (id, city_from, city_to, cost) values (827, 'Losino-Petrovskiy', 'George Town', 14565);
insert into offers (id, city_from, city_to, cost) values (828, 'Hexi', 'Kutamandarakan', 13022);
insert into offers (id, city_from, city_to, cost) values (829, 'Kastav', 'El Cobre', 19764);
insert into offers (id, city_from, city_to, cost) values (830, 'Notre-Dame-de-l''Île-Perrot', 'Baz', 8940);
insert into offers (id, city_from, city_to, cost) values (831, 'Huaranchal', 'Melissochóri', 6426);
insert into offers (id, city_from, city_to, cost) values (832, 'Nangang', 'Jenzan', 20493);
insert into offers (id, city_from, city_to, cost) values (833, 'Macroom', 'Nanxing', 19714);
insert into offers (id, city_from, city_to, cost) values (834, 'Shiniu', 'Xianghu', 7945);
insert into offers (id, city_from, city_to, cost) values (835, 'Mogi Mirim', 'Pilcaniyeu', 23868);
insert into offers (id, city_from, city_to, cost) values (836, 'Comillas Norte', 'Messina', 3877);
insert into offers (id, city_from, city_to, cost) values (837, 'Rueil-Malmaison', 'Ambato', 2550);
insert into offers (id, city_from, city_to, cost) values (838, 'Tanjung', 'Miasteczko Śląskie', 9029);
insert into offers (id, city_from, city_to, cost) values (839, 'Skoroszyce', 'Siayan', 19343);
insert into offers (id, city_from, city_to, cost) values (840, 'Al Jubayhah', 'Pasembon', 12678);
insert into offers (id, city_from, city_to, cost) values (841, 'Benniu', 'Quchomo', 18683);
insert into offers (id, city_from, city_to, cost) values (842, 'Guanta', 'Charikar', 9331);
insert into offers (id, city_from, city_to, cost) values (843, 'Manacapuru', 'Kadubera', 5224);
insert into offers (id, city_from, city_to, cost) values (844, 'Tudela', 'Nefta', 14297);
insert into offers (id, city_from, city_to, cost) values (845, 'Ngunguru', 'Świnna', 18017);
insert into offers (id, city_from, city_to, cost) values (846, 'Balengbeng', 'Osilnica', 3801);
insert into offers (id, city_from, city_to, cost) values (847, 'Jianshan', 'Domaniewice', 21952);
insert into offers (id, city_from, city_to, cost) values (848, 'Xiachu', 'Klos', 5935);
insert into offers (id, city_from, city_to, cost) values (849, 'Kýthnos', 'Cholpon-Ata', 17350);
insert into offers (id, city_from, city_to, cost) values (850, 'Zerok-Alakadari', 'Sherbrooke', 16685);
insert into offers (id, city_from, city_to, cost) values (851, 'Pakxé', 'Joconal', 21874);
insert into offers (id, city_from, city_to, cost) values (852, 'Corrego Grande', 'Robertsfors', 11235);
insert into offers (id, city_from, city_to, cost) values (853, 'Mūdīyah', 'Zhangdian', 6549);
insert into offers (id, city_from, city_to, cost) values (854, 'Dumalneg', 'Pangkungparuk', 5887);
insert into offers (id, city_from, city_to, cost) values (855, 'Pābna', 'Dianfang', 14019);
insert into offers (id, city_from, city_to, cost) values (856, 'Kubangsari', 'Jingping', 19156);
insert into offers (id, city_from, city_to, cost) values (857, 'Jiefang', 'Konispol', 2048);
insert into offers (id, city_from, city_to, cost) values (858, 'Krugersdorp', 'Videm pri Ptuju', 8821);
insert into offers (id, city_from, city_to, cost) values (859, 'Nakhodka', 'Shiquanhe', 16685);
insert into offers (id, city_from, city_to, cost) values (860, 'Samphanthawong', 'Dongfu', 1373);
insert into offers (id, city_from, city_to, cost) values (861, 'Mindyak', 'Thanatpin', 17799);
insert into offers (id, city_from, city_to, cost) values (862, 'Magog', 'Buliran Segundo', 2527);
insert into offers (id, city_from, city_to, cost) values (863, 'Xinlong', 'Vom', 19851);
insert into offers (id, city_from, city_to, cost) values (864, 'Mont-de-Marsan', 'Kárystos', 4298);
insert into offers (id, city_from, city_to, cost) values (865, 'Shymkent', 'San Pedro Carchá', 7100);
insert into offers (id, city_from, city_to, cost) values (866, 'Polomolok', 'Paterson', 23072);
insert into offers (id, city_from, city_to, cost) values (867, 'Izumiōtsu', 'Lianghekou', 18518);
insert into offers (id, city_from, city_to, cost) values (868, 'Corona', 'Kavajë', 4510);
insert into offers (id, city_from, city_to, cost) values (869, 'Puncaksari', 'Mundri', 17123);
insert into offers (id, city_from, city_to, cost) values (870, 'Mangarine', 'Bassar', 10120);
insert into offers (id, city_from, city_to, cost) values (871, 'San Isidro', 'Longjin', 17422);
insert into offers (id, city_from, city_to, cost) values (872, 'Valvedditturai', 'Letlhakane', 2382);
insert into offers (id, city_from, city_to, cost) values (873, 'Sepulu', 'Fagersta', 13068);
insert into offers (id, city_from, city_to, cost) values (874, 'São Bento do Sul', 'Tha Maka', 479);
insert into offers (id, city_from, city_to, cost) values (875, 'Mospyne', 'Real', 4082);
insert into offers (id, city_from, city_to, cost) values (876, 'Shengrenjian', 'Pingsha', 1064);
insert into offers (id, city_from, city_to, cost) values (877, 'Köln', 'Aragarças', 10409);
insert into offers (id, city_from, city_to, cost) values (878, 'Zernograd', 'Khabarovsk', 5137);
insert into offers (id, city_from, city_to, cost) values (879, 'Bassano', 'Bearna', 10863);
insert into offers (id, city_from, city_to, cost) values (880, 'Songgai', 'Tuanjie', 17577);
insert into offers (id, city_from, city_to, cost) values (881, 'Bolhos', 'Anchorage', 6450);
insert into offers (id, city_from, city_to, cost) values (882, 'Longtian', 'Ust-Maya', 16583);
insert into offers (id, city_from, city_to, cost) values (883, 'Bang Lamung', 'Khorixas', 18039);
insert into offers (id, city_from, city_to, cost) values (884, 'Martensville', 'Nogliki', 18807);
insert into offers (id, city_from, city_to, cost) values (885, 'Blumenau', 'Casablanca', 20281);
insert into offers (id, city_from, city_to, cost) values (886, 'Lucé', 'Viljakkala', 21365);
insert into offers (id, city_from, city_to, cost) values (887, 'Borås', 'Litein', 14846);
insert into offers (id, city_from, city_to, cost) values (888, 'Jiaoxiyakou', 'Youludu Sibage', 17337);
insert into offers (id, city_from, city_to, cost) values (889, 'Pakembangan', 'Mentougou', 5178);
insert into offers (id, city_from, city_to, cost) values (890, 'Ballylinan', 'Hongsipu', 11218);
insert into offers (id, city_from, city_to, cost) values (891, 'Darnah', 'Kalá Déndra', 21764);
insert into offers (id, city_from, city_to, cost) values (892, 'Tungi', 'Nelazskoye', 22252);
insert into offers (id, city_from, city_to, cost) values (893, 'København', 'Chiquimulilla', 9270);
insert into offers (id, city_from, city_to, cost) values (894, 'Sundbyberg', 'Kadugedong', 15093);
insert into offers (id, city_from, city_to, cost) values (895, 'Lorica', 'Yamen', 11657);
insert into offers (id, city_from, city_to, cost) values (896, 'Cimanggu Girang', 'Aliwal North', 15728);
insert into offers (id, city_from, city_to, cost) values (897, 'Los Mangos', 'São Martinho do Campo', 13846);
insert into offers (id, city_from, city_to, cost) values (898, 'Sulahan', 'Jundian', 9603);
insert into offers (id, city_from, city_to, cost) values (899, 'Santa Rita', 'Dongjia', 16017);
insert into offers (id, city_from, city_to, cost) values (900, 'Zipárion', 'Dolna Banya', 12251);
insert into offers (id, city_from, city_to, cost) values (901, 'São Brás de Alportel', 'Lomme', 2863);
insert into offers (id, city_from, city_to, cost) values (902, 'Tegalgede', 'Yongxing', 17054);
insert into offers (id, city_from, city_to, cost) values (903, 'Yasnogorsk', 'Nankāna Sāhib', 570);
insert into offers (id, city_from, city_to, cost) values (904, 'Breia', 'Zhongtang', 6593);
insert into offers (id, city_from, city_to, cost) values (905, 'Old Shinyanga', 'Nova Olímpia', 1263);
insert into offers (id, city_from, city_to, cost) values (906, 'Paulínia', 'Miragaia', 16912);
insert into offers (id, city_from, city_to, cost) values (907, 'Ningtang', 'Bentar', 6988);
insert into offers (id, city_from, city_to, cost) values (908, 'Cimrutu', 'Honglu', 11015);
insert into offers (id, city_from, city_to, cost) values (909, 'Hyesan-dong', 'Mikhaylov', 2442);
insert into offers (id, city_from, city_to, cost) values (910, 'Domanín', 'Pinara', 13268);
insert into offers (id, city_from, city_to, cost) values (911, 'Bintulu', 'Sembungin', 23104);
insert into offers (id, city_from, city_to, cost) values (912, 'Zlataritsa', 'Fengting', 16263);
insert into offers (id, city_from, city_to, cost) values (913, 'Gómez', 'Breia', 7853);
insert into offers (id, city_from, city_to, cost) values (914, 'Artesianón', 'Chōfugaoka', 21454);
insert into offers (id, city_from, city_to, cost) values (915, 'De la Paz', 'Puyehue', 14304);
insert into offers (id, city_from, city_to, cost) values (916, 'Irecê', 'Imsil', 3438);
insert into offers (id, city_from, city_to, cost) values (917, 'São José dos Campos', 'Angeghakot’', 22841);
insert into offers (id, city_from, city_to, cost) values (918, 'Miaoling', 'Alurbulu', 14279);
insert into offers (id, city_from, city_to, cost) values (919, 'Australia Square', 'Xilin', 18833);
insert into offers (id, city_from, city_to, cost) values (920, 'Romilly-sur-Seine', 'Klimavichy', 22493);
insert into offers (id, city_from, city_to, cost) values (921, 'Zapatero', 'Bankaw', 13310);
insert into offers (id, city_from, city_to, cost) values (922, 'Devon', 'Cete', 1113);
insert into offers (id, city_from, city_to, cost) values (923, 'Rízoma', 'Milano', 22994);
insert into offers (id, city_from, city_to, cost) values (924, 'Boden', 'Marolambo', 17641);
insert into offers (id, city_from, city_to, cost) values (925, 'Castlerea', 'Zhukeng', 10961);
insert into offers (id, city_from, city_to, cost) values (926, 'Moutas', 'Kourou', 15757);
insert into offers (id, city_from, city_to, cost) values (927, 'Phrae', 'Athabasca', 1585);
insert into offers (id, city_from, city_to, cost) values (928, 'Maayong Tubig', 'Tuburan', 18514);
insert into offers (id, city_from, city_to, cost) values (929, 'Brak', 'Tegalgunung', 12445);
insert into offers (id, city_from, city_to, cost) values (930, 'Tuopu', 'Liulin', 2373);
insert into offers (id, city_from, city_to, cost) values (931, 'Baguim do Monte', 'Bov', 22189);
insert into offers (id, city_from, city_to, cost) values (932, 'Notsé', 'Xiaozhen', 22653);
insert into offers (id, city_from, city_to, cost) values (933, 'Aoyang', 'Burbank', 12957);
insert into offers (id, city_from, city_to, cost) values (934, 'Podivín', 'Campo Grande', 15486);
insert into offers (id, city_from, city_to, cost) values (935, 'Lazurne', 'Richard-Toll', 6971);
insert into offers (id, city_from, city_to, cost) values (936, 'Kawaguchi', 'Lyon', 14181);
insert into offers (id, city_from, city_to, cost) values (937, 'Pokrovka', 'Puan', 14386);
insert into offers (id, city_from, city_to, cost) values (938, 'Ziketan', 'Yudong', 23772);
insert into offers (id, city_from, city_to, cost) values (939, 'Heyou', 'Almeirim', 9147);
insert into offers (id, city_from, city_to, cost) values (940, 'Embarcación', 'Kuala Lumpur', 18195);
insert into offers (id, city_from, city_to, cost) values (941, 'Kuala Terengganu', 'Potoci', 22065);
insert into offers (id, city_from, city_to, cost) values (942, 'Oebaki', 'Prata', 5571);
insert into offers (id, city_from, city_to, cost) values (943, 'Kozhanka', 'Kalnibolotskaya', 614);
insert into offers (id, city_from, city_to, cost) values (944, 'Murom', 'Ostrogozhsk', 6258);
insert into offers (id, city_from, city_to, cost) values (945, 'Glamoč', 'Dingbu', 14788);
insert into offers (id, city_from, city_to, cost) values (946, 'Paarl', 'Kaum', 8516);
insert into offers (id, city_from, city_to, cost) values (947, 'Christiana', 'Ludishan', 13423);
insert into offers (id, city_from, city_to, cost) values (948, 'Tanjungbahagia', 'Mesker-Yurt', 4139);
insert into offers (id, city_from, city_to, cost) values (949, 'Denton', 'Shypyntsi', 12911);
insert into offers (id, city_from, city_to, cost) values (950, 'Abakan', 'Xiaxi', 8616);
insert into offers (id, city_from, city_to, cost) values (951, 'Příšovice', 'Al Burayqah', 23473);
insert into offers (id, city_from, city_to, cost) values (952, 'Bečej', 'Cotahuasi', 17340);
insert into offers (id, city_from, city_to, cost) values (953, 'Tunjë', 'Ånge', 4054);
insert into offers (id, city_from, city_to, cost) values (954, 'Sapotskin', 'Huancapi', 5538);
insert into offers (id, city_from, city_to, cost) values (955, 'Timrå', 'Krajan Winong', 8329);
insert into offers (id, city_from, city_to, cost) values (956, 'Blagaj', 'Hihyā', 22224);
insert into offers (id, city_from, city_to, cost) values (957, 'Constanza', 'Shicong', 16856);
insert into offers (id, city_from, city_to, cost) values (958, 'Vukatanë', 'Camaquã', 7664);
insert into offers (id, city_from, city_to, cost) values (959, 'Grand Rapids', 'Bueng Sam Phan', 8525);
insert into offers (id, city_from, city_to, cost) values (960, 'Megati Kelod', 'Dolní Kounice', 20127);
insert into offers (id, city_from, city_to, cost) values (961, 'Minusinsk', 'Tabuadelo', 20626);
insert into offers (id, city_from, city_to, cost) values (962, 'Anren', 'Orsay', 5035);
insert into offers (id, city_from, city_to, cost) values (963, 'Budva', 'Konëvo', 6006);
insert into offers (id, city_from, city_to, cost) values (964, 'Shin’ichi', 'Cabiguan', 1551);
insert into offers (id, city_from, city_to, cost) values (965, 'Matagami', 'Nanlin', 10741);
insert into offers (id, city_from, city_to, cost) values (966, 'Hualongyan', 'H̱olon', 19469);
insert into offers (id, city_from, city_to, cost) values (967, 'Uarini', 'Лабуништа', 13168);
insert into offers (id, city_from, city_to, cost) values (968, 'Longgao', 'La Cumbre', 8469);
insert into offers (id, city_from, city_to, cost) values (969, 'Sauri', 'La Concepcion', 11115);
insert into offers (id, city_from, city_to, cost) values (970, 'Babakansari', 'Tangguhang', 16845);
insert into offers (id, city_from, city_to, cost) values (971, 'Claye-Souilly', 'Yimnón', 14222);
insert into offers (id, city_from, city_to, cost) values (972, 'Hiji', 'Guadalupe', 23080);
insert into offers (id, city_from, city_to, cost) values (973, 'Kayu Agung', 'Biruinţa', 6924);
insert into offers (id, city_from, city_to, cost) values (974, 'Krajan Dukuhseti', 'San Pedro', 14018);
insert into offers (id, city_from, city_to, cost) values (975, 'Casillas', 'Pelópion', 3257);
insert into offers (id, city_from, city_to, cost) values (976, 'Beicheng', 'Beidao', 962);
insert into offers (id, city_from, city_to, cost) values (977, 'Ardirejo', 'Sikonge', 12969);
insert into offers (id, city_from, city_to, cost) values (978, 'Wang Nam Yen', 'Morelos', 11173);
insert into offers (id, city_from, city_to, cost) values (979, 'San Antonio', 'Khairpur', 5343);
insert into offers (id, city_from, city_to, cost) values (980, 'Huangtian', 'Kota Bharu', 5599);
insert into offers (id, city_from, city_to, cost) values (981, 'Taibao', 'Ferreñafe', 8213);
insert into offers (id, city_from, city_to, cost) values (982, 'Asímion', 'Pereleshino', 16991);
insert into offers (id, city_from, city_to, cost) values (983, 'Chak', 'Kazaure', 14824);
insert into offers (id, city_from, city_to, cost) values (984, 'Ocho Rios', 'Tuohua', 1978);
insert into offers (id, city_from, city_to, cost) values (985, 'Uppsala', 'Świlcza', 13688);
insert into offers (id, city_from, city_to, cost) values (986, 'Karema', 'Longquan', 21018);
insert into offers (id, city_from, city_to, cost) values (987, 'Sirāhā', 'Antioquia', 11902);
insert into offers (id, city_from, city_to, cost) values (988, 'Zhongling', 'Ladário', 15364);
insert into offers (id, city_from, city_to, cost) values (989, 'Dordrecht', 'Daijiaba', 9444);
insert into offers (id, city_from, city_to, cost) values (990, 'Marly-le-Roi', 'Ljungby', 14092);
insert into offers (id, city_from, city_to, cost) values (991, 'Teculután', 'Bayt Ūmmar', 7995);
insert into offers (id, city_from, city_to, cost) values (992, 'Siva', 'Blama', 5040);
insert into offers (id, city_from, city_to, cost) values (993, 'Ulaandel', 'Bogatynia', 10345);
insert into offers (id, city_from, city_to, cost) values (994, 'Cerkvenjak', 'Molave', 16917);
insert into offers (id, city_from, city_to, cost) values (995, 'Lajinha', 'Ambatolampy', 16417);
insert into offers (id, city_from, city_to, cost) values (996, 'Severnyy', 'Yuyao', 17743);
insert into offers (id, city_from, city_to, cost) values (997, 'Thomassique', 'Sidi Slimane', 19229);
insert into offers (id, city_from, city_to, cost) values (998, 'Starcevica', 'Kwangyang', 14087);
insert into offers (id, city_from, city_to, cost) values (999, 'Guangyubao', 'Łubnice', 12968);
insert into offers (id, city_from, city_to, cost) values (1000, 'Dandu', 'Tasböget', 23326);
