insert into offers (city_from, city_to, cost) values ('Khafizan', 'Škofljica', 3672);
insert into offers (city_from, city_to, cost) values ('Nakasongola', 'Matanzas', 16736);
insert into offers (city_from, city_to, cost) values ('Zimmi', 'Ciudad Bolívar', 11209);
insert into offers (city_from, city_to, cost) values ('Qiagai', 'Qabaqçöl', 17110);
insert into offers (city_from, city_to, cost) values ('Hanyuan', 'Jönköping', 7533);
insert into offers (city_from, city_to, cost) values ('Lakkíon', 'Kyurdarmir', 1204);
insert into offers (city_from, city_to, cost) values ('Philipsburg', 'Bira', 12763);
insert into offers (city_from, city_to, cost) values ('Mabasa', 'Banqiao', 14203);
insert into offers (city_from, city_to, cost) values ('Sambirobyong', 'Gulou', 22611);
insert into offers (city_from, city_to, cost) values ('Viñales', 'Jichang', 18971);
insert into offers (city_from, city_to, cost) values ('Lakkha Nëvre', 'Mantingantengah', 18941);
insert into offers (city_from, city_to, cost) values ('Zhouxi', 'Profítis Ilías', 21894);
insert into offers (city_from, city_to, cost) values ('Pentaplátano', 'Mafeng', 3549);
insert into offers (city_from, city_to, cost) values ('Palermo', 'Leiria', 686);
insert into offers (city_from, city_to, cost) values ('Cajolá', 'Beni Khiar', 5057);
insert into offers (city_from, city_to, cost) values ('København', 'Sharjah', 12600);
insert into offers (city_from, city_to, cost) values ('Dinalongan', 'Westonaria', 12304);
insert into offers (city_from, city_to, cost) values ('Toledo', 'Antalaha', 10756);
insert into offers (city_from, city_to, cost) values ('Jianguo', 'Qiping', 10325);
insert into offers (city_from, city_to, cost) values ('Heyan', 'Pokrovskoye-Streshnëvo', 6672);
insert into offers (city_from, city_to, cost) values ('Khe Tre', 'Kŭrdzhali', 18173);
insert into offers (city_from, city_to, cost) values ('Nartkala', 'Guimarei', 10026);
insert into offers (city_from, city_to, cost) values ('Cajamarca', 'Gersikputih Tengah', 16872);
insert into offers (city_from, city_to, cost) values ('Shipka', 'Souto', 9847);
insert into offers (city_from, city_to, cost) values ('Gakem', 'Lidköping', 13701);
insert into offers (city_from, city_to, cost) values ('Sungaigerong', 'Mella', 18969);
insert into offers (city_from, city_to, cost) values ('Lagawe', 'Kaoshan', 5907);
insert into offers (city_from, city_to, cost) values ('Koper', 'Tegalsari', 20910);
insert into offers (city_from, city_to, cost) values ('Al Ḩashwah', 'Carania', 6369);
insert into offers (city_from, city_to, cost) values ('Lukavec', 'Sinjil', 21319);
insert into offers (city_from, city_to, cost) values ('Nam Sách', 'Saratamata', 4041);
insert into offers (city_from, city_to, cost) values ('Jardim', 'San Luis del Palmar', 20145);
insert into offers (city_from, city_to, cost) values ('Hořice', 'Uzlovaya', 20515);
insert into offers (city_from, city_to, cost) values ('Eucaliptus', 'Ndano', 9775);
insert into offers (city_from, city_to, cost) values ('Kovářská', 'Nazarje', 15887);
insert into offers (city_from, city_to, cost) values ('Marigot', 'Artur Nogueira', 1583);
insert into offers (city_from, city_to, cost) values ('San Juan de Planes', 'Gebre Guracha', 17478);
insert into offers (city_from, city_to, cost) values ('Princeville', 'Maji', 11629);
insert into offers (city_from, city_to, cost) values ('Jūybār', 'Winter Haven', 10640);
insert into offers (city_from, city_to, cost) values ('Cartagena', 'Fatuulan', 1361);
insert into offers (city_from, city_to, cost) values ('Longxing', 'Ramotswa', 12038);
insert into offers (city_from, city_to, cost) values ('Tsurugi-asahimachi', 'Rubio', 5565);
insert into offers (city_from, city_to, cost) values ('Pasirhuni', 'Montalvão', 501);
insert into offers (city_from, city_to, cost) values ('Mangunjaya', 'Banī Khaddāsh', 18519);
insert into offers (city_from, city_to, cost) values ('Cagmanaba', 'Degerfors', 1585);
insert into offers (city_from, city_to, cost) values ('Xiaojian', 'Jin’e', 9297);
insert into offers (city_from, city_to, cost) values ('San Carlos de Bariloche', 'Qiaonan', 22406);
insert into offers (city_from, city_to, cost) values ('Muliang', 'Monteiro', 8439);
insert into offers (city_from, city_to, cost) values ('Obesi', 'Runan', 11096);
insert into offers (city_from, city_to, cost) values ('Qinnan', 'Batarasa', 22090);
insert into offers (city_from, city_to, cost) values ('Sobienie Jeziory', 'Neuquén', 13258);
insert into offers (city_from, city_to, cost) values ('Aourir', 'Sarpang', 4440);
insert into offers (city_from, city_to, cost) values ('Magaozhuang', 'Salām Khēl', 5219);
insert into offers (city_from, city_to, cost) values ('Inhambane', 'San Antonio', 13373);
insert into offers (city_from, city_to, cost) values ('Cabaiguán', 'Tocha', 3184);
insert into offers (city_from, city_to, cost) values ('Nuoxizhi', 'Selishche', 6074);
insert into offers (city_from, city_to, cost) values ('Alajuelita', 'San Joaquin', 23982);
insert into offers (city_from, city_to, cost) values ('Huntington', 'Petaling Jaya', 5595);
insert into offers (city_from, city_to, cost) values ('Tandou', 'San Esteban', 9449);
insert into offers (city_from, city_to, cost) values ('Caibarién', 'Kazlų Rūda', 22533);
insert into offers (city_from, city_to, cost) values ('Crespo', 'La Argentina', 1793);
insert into offers (city_from, city_to, cost) values ('Haveli', 'Gataivai', 13000);
insert into offers (city_from, city_to, cost) values ('Calarcá', 'Tilmi', 19618);
insert into offers (city_from, city_to, cost) values ('Jagong', 'Polje', 6631);
insert into offers (city_from, city_to, cost) values ('Bykivka', 'Laocheng', 5606);
insert into offers (city_from, city_to, cost) values ('Knysna', 'Batán', 15440);
insert into offers (city_from, city_to, cost) values ('Paris 19', 'Kobrinskoye', 8944);
insert into offers (city_from, city_to, cost) values ('Saint-Étienne', 'Morelos', 11199);
insert into offers (city_from, city_to, cost) values ('Xianbao', 'Shuitou', 12372);
insert into offers (city_from, city_to, cost) values ('Sinop', 'Kąty Wrocławskie', 12161);
insert into offers (city_from, city_to, cost) values ('Sabaneta', 'Pępowo', 4409);
insert into offers (city_from, city_to, cost) values ('Gyigang', 'Katipunan', 5598);
insert into offers (city_from, city_to, cost) values ('Tía Juana', 'Xiejiaya', 2969);
insert into offers (city_from, city_to, cost) values ('Socabaya', 'Chinchaypujio', 2849);
insert into offers (city_from, city_to, cost) values ('He’an', 'Oakville', 7813);
insert into offers (city_from, city_to, cost) values ('Smedjebacken', 'Itabaiana', 6768);
insert into offers (city_from, city_to, cost) values ('Rora Timur', 'Aba', 23746);
insert into offers (city_from, city_to, cost) values ('Galaz', 'Injīl', 8683);
insert into offers (city_from, city_to, cost) values ('Monte Mor', 'Kalvola', 14130);
insert into offers (city_from, city_to, cost) values ('Parapat', 'Oslo', 19969);
insert into offers (city_from, city_to, cost) values ('Naples', 'Västerhaninge', 15786);
insert into offers (city_from, city_to, cost) values ('Yeroẖam', 'Campo de la Cruz', 10570);
insert into offers (city_from, city_to, cost) values ('Haeju', 'Otjimbingwe', 16077);
insert into offers (city_from, city_to, cost) values ('Bom Jesus do Itabapoana', 'Longmenfan', 11246);
insert into offers (city_from, city_to, cost) values ('Pasaje', 'Fāqūs', 20865);
insert into offers (city_from, city_to, cost) values ('Shaba', 'Bhakkar', 22792);
insert into offers (city_from, city_to, cost) values ('Niutian', 'Amirdzhan', 3973);
insert into offers (city_from, city_to, cost) values ('Kansas City', 'Żabno', 1173);
insert into offers (city_from, city_to, cost) values ('Ignalina', 'Ouaoula', 22837);
insert into offers (city_from, city_to, cost) values ('Taungdwingyi', 'Nanton', 4326);
insert into offers (city_from, city_to, cost) values ('Kawambwa', 'Macaíba', 18352);
insert into offers (city_from, city_to, cost) values ('Nikolayevskaya', 'Syamzha', 3855);
insert into offers (city_from, city_to, cost) values ('Tyoply Stan', 'Quintã', 8866);
insert into offers (city_from, city_to, cost) values ('Holoubkov', 'Qingzhou', 5296);
insert into offers (city_from, city_to, cost) values ('Pereiras', 'Aipe', 1147);
insert into offers (city_from, city_to, cost) values ('Waiwejak', 'Shimen', 906);
insert into offers (city_from, city_to, cost) values ('Mayang', 'Tomohon', 11628);
insert into offers (city_from, city_to, cost) values ('Ruukki', 'Orerokpe', 17625);
insert into offers (city_from, city_to, cost) values ('Kawangu', 'Yogyakarta', 4641);
insert into offers (city_from, city_to, cost) values ('Ciechanów', 'Charlottenberg', 14579);
insert into offers (city_from, city_to, cost) values ('Chengxi', 'Buyende', 1554);
insert into offers (city_from, city_to, cost) values ('Itbayat', 'Psary', 7994);
insert into offers (city_from, city_to, cost) values ('Guanzhuang', 'Pereiras', 13533);
insert into offers (city_from, city_to, cost) values ('Norrköping', 'Panoongan', 16133);
insert into offers (city_from, city_to, cost) values ('Grand Forks', 'Sacramento', 1070);
insert into offers (city_from, city_to, cost) values ('Lingshan', 'Meia Via', 16386);
insert into offers (city_from, city_to, cost) values ('Bluefields', 'Anjani Barat', 20492);
insert into offers (city_from, city_to, cost) values ('At Tibnī', 'São Mateus do Maranhão', 23070);
insert into offers (city_from, city_to, cost) values ('Stylída', 'Krajan Kinanti', 22968);
insert into offers (city_from, city_to, cost) values ('Voyutychi', 'Taipingying', 1734);
insert into offers (city_from, city_to, cost) values ('Iradan', 'Ishqoshim', 21922);
insert into offers (city_from, city_to, cost) values ('Yaotian', 'Spas', 8169);
insert into offers (city_from, city_to, cost) values ('Sengkerang Tiga', 'Garwolin', 14572);
insert into offers (city_from, city_to, cost) values ('Lesozavodsk', 'Štitar', 12255);
insert into offers (city_from, city_to, cost) values ('Kéfalos', 'Stockholm', 20159);
insert into offers (city_from, city_to, cost) values ('Shiquan', 'Zhetang', 6369);
insert into offers (city_from, city_to, cost) values ('Tiblawan', 'Outeiro de Polima', 1091);
insert into offers (city_from, city_to, cost) values ('Telhado', 'Marigot', 22150);
insert into offers (city_from, city_to, cost) values ('Ruteng', 'Mubi', 2716);
insert into offers (city_from, city_to, cost) values ('Pisaras', 'Jājarm', 4880);
insert into offers (city_from, city_to, cost) values ('Sidaurip', 'Manyava', 4125);
insert into offers (city_from, city_to, cost) values ('Santa Ana', 'Beichan', 22597);
insert into offers (city_from, city_to, cost) values ('Oygon', 'Charras', 5906);
insert into offers (city_from, city_to, cost) values ('Hadyach', 'San Joaquin', 22527);
insert into offers (city_from, city_to, cost) values ('Qiawan', 'Balyqshy', 2742);
insert into offers (city_from, city_to, cost) values ('Basiong', 'Combapata', 21862);
insert into offers (city_from, city_to, cost) values ('Ushi', 'Saint-Étienne', 3856);
insert into offers (city_from, city_to, cost) values ('Chābahār', 'Vuokatti', 16598);
insert into offers (city_from, city_to, cost) values ('Gorjani', 'Lohong', 15272);
insert into offers (city_from, city_to, cost) values ('Louredo', 'Wrząsowice', 10651);
insert into offers (city_from, city_to, cost) values ('Metallostroy', 'Tuohua', 3197);
insert into offers (city_from, city_to, cost) values ('Reguengos de Monsaraz', 'Tayabo', 16351);
insert into offers (city_from, city_to, cost) values ('Calde', 'Dasht-e Archī', 13573);
insert into offers (city_from, city_to, cost) values ('Zhoukou', 'Kotakan Selatan', 12278);
insert into offers (city_from, city_to, cost) values ('Baixo Guandu', 'Stari Grad', 7855);
insert into offers (city_from, city_to, cost) values ('Chikeng', 'Zgornje Gorje', 2244);
insert into offers (city_from, city_to, cost) values ('Castro Daire', 'Xingfu', 9226);
insert into offers (city_from, city_to, cost) values ('Antiguo Cuscatlán', 'Saint-Jérôme', 4668);
insert into offers (city_from, city_to, cost) values ('Estancia', 'Chicago', 11238);
insert into offers (city_from, city_to, cost) values ('Sotíra', 'Barili', 5718);
insert into offers (city_from, city_to, cost) values ('Jastrowie', 'Garbolovo', 9848);
insert into offers (city_from, city_to, cost) values ('Dzaoudzi', 'San Francisco', 12167);
insert into offers (city_from, city_to, cost) values ('Solidaridad', 'Zubrzyca Dolna', 20186);
insert into offers (city_from, city_to, cost) values ('Karelichy', 'Laranjeiras', 1879);
insert into offers (city_from, city_to, cost) values ('Minusinsk', 'Valle de La Pascua', 10522);
insert into offers (city_from, city_to, cost) values ('Guanmian', 'Miaoshou', 2534);
insert into offers (city_from, city_to, cost) values ('Urachiche', 'Igbo-Ukwu', 3116);
insert into offers (city_from, city_to, cost) values ('Wichita', 'Bīleh Savār', 21920);
insert into offers (city_from, city_to, cost) values ('Abashiri', 'Khust', 9765);
insert into offers (city_from, city_to, cost) values ('Zyryanovsk', 'Yunguyo', 10567);
insert into offers (city_from, city_to, cost) values ('Österbybruk', 'Vesoul', 4560);
insert into offers (city_from, city_to, cost) values ('Malysheva', 'Sindangan', 15683);
insert into offers (city_from, city_to, cost) values ('Malabar', 'Kŭlob', 18815);
insert into offers (city_from, city_to, cost) values ('Anuling', 'Xiaocheng', 22961);
insert into offers (city_from, city_to, cost) values ('Słotowa', 'Samaro', 19025);
insert into offers (city_from, city_to, cost) values ('Arlington', 'Naushahro Fīroz', 13826);
insert into offers (city_from, city_to, cost) values ('Patique', 'Xiadu', 9925);
insert into offers (city_from, city_to, cost) values ('Essen', 'Viga', 5812);
insert into offers (city_from, city_to, cost) values ('Xinchang', 'Huancheng', 4224);
insert into offers (city_from, city_to, cost) values ('Lensk', 'Cuiabá', 12092);
insert into offers (city_from, city_to, cost) values ('Taipalsaari', 'Macheng', 16358);
insert into offers (city_from, city_to, cost) values ('Huancheng', 'Mae Wang', 20647);
insert into offers (city_from, city_to, cost) values ('Kakan', 'Sumurgung', 7364);
insert into offers (city_from, city_to, cost) values ('Busalangga', 'Ozorków', 10363);
insert into offers (city_from, city_to, cost) values ('Leonárisso', 'Kapenguria', 5318);
insert into offers (city_from, city_to, cost) values ('Labelle', 'Řečany nad Labem', 14891);
insert into offers (city_from, city_to, cost) values ('Okinawa Número Uno', 'Xiashihao', 23757);
insert into offers (city_from, city_to, cost) values ('Tsimlyansk', 'Xiangrong', 22331);
insert into offers (city_from, city_to, cost) values ('Bogale', 'Heshengbao', 15943);
insert into offers (city_from, city_to, cost) values ('Marseille', 'Jambulang', 889);
insert into offers (city_from, city_to, cost) values ('West End', 'Nova Venécia', 16882);
insert into offers (city_from, city_to, cost) values ('Longtanping', 'Istres', 22075);
insert into offers (city_from, city_to, cost) values ('Öjebyn', 'Binawara', 13803);
insert into offers (city_from, city_to, cost) values ('Nezamyslice', 'San Ramón', 10566);
insert into offers (city_from, city_to, cost) values ('Aného', 'Khao Wong', 3715);
insert into offers (city_from, city_to, cost) values ('Albergaria', 'Carrigaline', 6643);
insert into offers (city_from, city_to, cost) values ('Dunyāpur', 'Xiaheqing', 18199);
insert into offers (city_from, city_to, cost) values ('Shangtian', 'Iwase', 16414);
insert into offers (city_from, city_to, cost) values ('Södertälje', 'Bungo-Takada-shi', 19838);
insert into offers (city_from, city_to, cost) values ('Xhafzotaj', 'Solntsevo', 8308);
insert into offers (city_from, city_to, cost) values ('Chayek', 'Akademgorodok', 17360);
insert into offers (city_from, city_to, cost) values ('Ban Phan Don', 'Rudy', 7983);
insert into offers (city_from, city_to, cost) values ('Yanggan', 'A dos Cunhados', 22376);
insert into offers (city_from, city_to, cost) values ('Ḩalāwah', 'Klapagading', 4270);
insert into offers (city_from, city_to, cost) values ('Yangchengzhuang', 'Jiangwakou', 23632);
insert into offers (city_from, city_to, cost) values ('Albuquerque', 'Zhangdian', 6974);
insert into offers (city_from, city_to, cost) values ('Nanyang', 'Nambak Tengah', 19969);
insert into offers (city_from, city_to, cost) values ('Jianggang', 'Desakolot', 11668);
insert into offers (city_from, city_to, cost) values ('Trujillo', 'Coayllo', 9433);
insert into offers (city_from, city_to, cost) values ('Anjiang', 'Oslo', 4142);
insert into offers (city_from, city_to, cost) values ('Ciklapa', 'Novokubansk', 7242);
insert into offers (city_from, city_to, cost) values ('Xingou', 'Cagbang', 13309);
insert into offers (city_from, city_to, cost) values ('Bagenalstown', 'Cola', 21980);
insert into offers (city_from, city_to, cost) values ('Krathum Baen', 'Sinegorskiy', 22788);
insert into offers (city_from, city_to, cost) values ('Yangchun', 'Gerdu', 13124);
insert into offers (city_from, city_to, cost) values ('Jabat', 'Sävedalen', 11618);
insert into offers (city_from, city_to, cost) values ('Garbolovo', 'Beja', 22653);
insert into offers (city_from, city_to, cost) values ('Sadahayu', 'Neofbaun', 13024);
insert into offers (city_from, city_to, cost) values ('São Pedro Gafanhoeira', 'Klek', 8448);
insert into offers (city_from, city_to, cost) values ('Taiping', 'Artémida', 13384);
insert into offers (city_from, city_to, cost) values ('Valença do Douro', 'Ongkharak', 18011);
insert into offers (city_from, city_to, cost) values ('Kasreman', 'Samut Sakhon', 6844);
insert into offers (city_from, city_to, cost) values ('Qinghua', 'Bei’an', 14737);
insert into offers (city_from, city_to, cost) values ('Turpay', 'San Lorenzo', 13504);
insert into offers (city_from, city_to, cost) values ('Fenyan', 'Hezuoqiao', 15330);
insert into offers (city_from, city_to, cost) values ('Lipa City', 'Zaoshi', 7885);
insert into offers (city_from, city_to, cost) values ('Urazovo', 'Timashëvsk', 21811);
insert into offers (city_from, city_to, cost) values ('Mumen', 'San Miguel del Padrón', 13911);
insert into offers (city_from, city_to, cost) values ('Gorē', 'Pasar', 10395);
insert into offers (city_from, city_to, cost) values ('Niaohe', 'Angochi', 14591);
insert into offers (city_from, city_to, cost) values ('Margita', 'Louny', 17818);
insert into offers (city_from, city_to, cost) values ('São Martinho de Árvore', 'Sarandi', 22453);
insert into offers (city_from, city_to, cost) values ('Xique Xique', 'Uchkeken', 7621);
insert into offers (city_from, city_to, cost) values ('Carvalhal', 'Cangshi', 5671);
insert into offers (city_from, city_to, cost) values ('Enshi', 'Krasnyy Lyman', 3637);
insert into offers (city_from, city_to, cost) values ('Essen', 'Okayama-shi', 10587);
insert into offers (city_from, city_to, cost) values ('Chichibu', 'Novosemeykino', 2629);
insert into offers (city_from, city_to, cost) values ('Taoyuan', 'Smederevo', 4087);
insert into offers (city_from, city_to, cost) values ('Ārān Bīdgol', 'Shimen', 5105);
insert into offers (city_from, city_to, cost) values ('Sala', 'Huangmei', 3521);
insert into offers (city_from, city_to, cost) values ('Dongzhaogezhuang', 'Prosyana', 1574);
insert into offers (city_from, city_to, cost) values ('Huangcun', 'Peyima', 19515);
insert into offers (city_from, city_to, cost) values ('Cachipay', 'Krzeszów', 9921);
insert into offers (city_from, city_to, cost) values ('Taclobo', 'Mariara', 12602);
insert into offers (city_from, city_to, cost) values ('Zaandam', 'Atakpamé', 4654);
insert into offers (city_from, city_to, cost) values ('Kościerzyna', 'Puhechang', 23694);
insert into offers (city_from, city_to, cost) values ('Kihangara', 'Serh', 8538);
insert into offers (city_from, city_to, cost) values ('Bhalil', 'San Cosme y Damián', 5755);
insert into offers (city_from, city_to, cost) values ('Gagarin', 'Ushibuka', 7392);
insert into offers (city_from, city_to, cost) values ('Sukamenak', 'Jaen', 12827);
insert into offers (city_from, city_to, cost) values ('Bacabal', 'Shuigou', 21417);
insert into offers (city_from, city_to, cost) values ('Dioila', 'Lefortovo', 16619);
insert into offers (city_from, city_to, cost) values ('Kuantan', 'Pácora', 22924);
insert into offers (city_from, city_to, cost) values ('San Antonio de Los Altos', 'Argasari', 6459);
insert into offers (city_from, city_to, cost) values ('Washington', 'Szeged', 23827);
insert into offers (city_from, city_to, cost) values ('Lào Cai', 'Tambawel', 2495);
insert into offers (city_from, city_to, cost) values ('Shataping', 'Paiçandu', 6267);
insert into offers (city_from, city_to, cost) values ('São Félix do Xingu', 'Zhangatas', 7718);
insert into offers (city_from, city_to, cost) values ('Qianjia', 'Kokkinóchoma', 9009);
insert into offers (city_from, city_to, cost) values ('Xinjiang', 'Yangon', 8251);
insert into offers (city_from, city_to, cost) values ('Cintra', 'Oranjestad', 18140);
insert into offers (city_from, city_to, cost) values ('Debre Zeyit', 'Huangrangping', 19698);
insert into offers (city_from, city_to, cost) values ('Dongtian', 'Camgyai', 22060);
insert into offers (city_from, city_to, cost) values ('Nouâdhibou', 'Likiep', 2425);
insert into offers (city_from, city_to, cost) values ('Luleå', 'Aguazul', 7279);
insert into offers (city_from, city_to, cost) values ('Caohezhang', 'Zaliztsi', 23433);
insert into offers (city_from, city_to, cost) values ('Lille', 'Chengbei', 5007);
insert into offers (city_from, city_to, cost) values ('Braunschweig', 'Panalo-on', 6445);
insert into offers (city_from, city_to, cost) values ('Cầu Giát', 'Simeykyne', 10527);
insert into offers (city_from, city_to, cost) values ('El Paso', 'Jinka', 15811);
insert into offers (city_from, city_to, cost) values ('Xiaojiang', 'Milwaukee', 20696);
insert into offers (city_from, city_to, cost) values ('Palma Gil', 'Nubma', 14097);
insert into offers (city_from, city_to, cost) values ('Sakado', 'Cogreg Wetan', 13243);
insert into offers (city_from, city_to, cost) values ('Tenkodogo', 'Shibajiazi', 8055);
insert into offers (city_from, city_to, cost) values ('Falköping', 'Valparaíso', 7009);
insert into offers (city_from, city_to, cost) values ('Kemlya', 'Kayan', 8943);
insert into offers (city_from, city_to, cost) values ('Dongxiang', 'Sri Jayewardenepura Kotte', 15135);
insert into offers (city_from, city_to, cost) values ('Imulolong', 'Sakaraha', 3806);
insert into offers (city_from, city_to, cost) values ('Metsovo', 'Suruhwadang', 4757);
insert into offers (city_from, city_to, cost) values ('Querecotillo', 'Nenotes', 14360);
insert into offers (city_from, city_to, cost) values ('Marseille', 'Bungursari', 13205);
insert into offers (city_from, city_to, cost) values ('Liangwangzhuang', 'Kokologo', 4052);
insert into offers (city_from, city_to, cost) values ('Guaimaca', 'Thị Trấn Việt Quang', 18241);
insert into offers (city_from, city_to, cost) values ('Velikiye Borki', 'Mont-Laurier', 890);
insert into offers (city_from, city_to, cost) values ('Rájec-Jestřebí', 'Vårdö', 866);
insert into offers (city_from, city_to, cost) values ('Meishan', 'Karangampel', 17173);
insert into offers (city_from, city_to, cost) values ('Centurion', 'Dongbatu', 23206);
insert into offers (city_from, city_to, cost) values ('Ngrowo', 'Nipawin', 2264);
insert into offers (city_from, city_to, cost) values ('Mashan', 'Kadugadung', 12235);
insert into offers (city_from, city_to, cost) values ('Bukui', 'Houxixi', 23452);
insert into offers (city_from, city_to, cost) values ('Kongtian', 'El Corpus', 22378);
insert into offers (city_from, city_to, cost) values ('Mikhaylovka', 'Chornobay', 13610);
insert into offers (city_from, city_to, cost) values ('Alingsås', 'Dos Quebradas', 7790);
insert into offers (city_from, city_to, cost) values ('Kimry', 'Oslo', 2735);
insert into offers (city_from, city_to, cost) values ('Kinkala', 'Yuankeng', 8073);
insert into offers (city_from, city_to, cost) values ('Miragaia', 'Gaomiaoji', 6047);
insert into offers (city_from, city_to, cost) values ('Nanqiao', 'Mizhuang', 1200);
insert into offers (city_from, city_to, cost) values ('Biaoshan', 'Soutinho', 17200);
insert into offers (city_from, city_to, cost) values ('Pailles', 'Ciladaeun', 9615);
insert into offers (city_from, city_to, cost) values ('Kota Kinabalu', 'Wangliao', 22110);
insert into offers (city_from, city_to, cost) values ('Gaoua', 'Saint Louis', 23129);
insert into offers (city_from, city_to, cost) values ('Galutu', 'Bang Rakam', 14226);
insert into offers (city_from, city_to, cost) values ('Xingyi', 'Miguel Hidalgo', 20752);
insert into offers (city_from, city_to, cost) values ('Ciorescu', 'Banjarsari', 8642);
insert into offers (city_from, city_to, cost) values ('Rogowo', 'Bang Krathum', 593);
insert into offers (city_from, city_to, cost) values ('Kavajë', 'Błaszki', 13182);
insert into offers (city_from, city_to, cost) values ('Tammela', 'Wang Chan', 7523);
insert into offers (city_from, city_to, cost) values ('Węgliniec', 'Sentani', 22682);
insert into offers (city_from, city_to, cost) values ('Tanjungpecinan Utara', 'Watuka', 15737);
insert into offers (city_from, city_to, cost) values ('Tandahimba', 'Oenopu', 889);
insert into offers (city_from, city_to, cost) values ('Khotynets', 'Qingzhou', 10712);
insert into offers (city_from, city_to, cost) values ('Zhongchao', 'Chervonopartyzans’k', 17264);
insert into offers (city_from, city_to, cost) values ('Pocrí', 'Nusajaya', 9235);
insert into offers (city_from, city_to, cost) values ('Baleber', 'Ermelo', 22974);
insert into offers (city_from, city_to, cost) values ('Cikembar', 'Songkan', 11508);
insert into offers (city_from, city_to, cost) values ('Yuqi', 'Campoalegre', 20714);
insert into offers (city_from, city_to, cost) values ('Jutrosin', 'Krasnorechenskiy', 13421);
insert into offers (city_from, city_to, cost) values ('Mae Chan', 'Jatibonico', 21797);
insert into offers (city_from, city_to, cost) values ('Chocianów', 'North Shore', 22076);
insert into offers (city_from, city_to, cost) values ('Bonneuil-sur-Marne', 'Chengmen', 21083);
insert into offers (city_from, city_to, cost) values ('Xiongji', 'San Miguel', 12182);
insert into offers (city_from, city_to, cost) values ('Parachinar', 'Pribrezhnyy', 8373);
insert into offers (city_from, city_to, cost) values ('Wubao', 'Komyshany', 22573);
insert into offers (city_from, city_to, cost) values ('Huangchuan', 'Linmansangan', 23040);
insert into offers (city_from, city_to, cost) values ('Zlatoust', 'Taphan Hin', 10079);
insert into offers (city_from, city_to, cost) values ('Yangkang', 'Benito Juarez', 500);
insert into offers (city_from, city_to, cost) values ('Kuzhorskaya', 'Zhuanqiang', 6051);
insert into offers (city_from, city_to, cost) values ('Pacaraos', 'Laem Sing', 17598);
insert into offers (city_from, city_to, cost) values ('Amsterdam Noord west', 'Ulbroka', 17327);
insert into offers (city_from, city_to, cost) values ('Karaidel’', 'Zhangcaizhuang', 3766);
insert into offers (city_from, city_to, cost) values ('Rybnoye', 'Kraton', 20039);
insert into offers (city_from, city_to, cost) values ('Navais', 'Polevskoy', 21148);
insert into offers (city_from, city_to, cost) values ('Huaihua', 'Cireundang', 9050);
insert into offers (city_from, city_to, cost) values ('Kristinehamn', 'Brodnica', 16856);
insert into offers (city_from, city_to, cost) values ('Devnya', 'Qingliu', 20675);
insert into offers (city_from, city_to, cost) values ('Mora', 'Resende', 21578);
insert into offers (city_from, city_to, cost) values ('Bicas', 'Baibu', 15772);
insert into offers (city_from, city_to, cost) values ('Kuncen', 'Lasiana', 6278);
insert into offers (city_from, city_to, cost) values ('Longtian', 'Ylihärmä', 13513);
insert into offers (city_from, city_to, cost) values ('Ordzhonikidzevskiy', 'Rodolívos', 13466);
insert into offers (city_from, city_to, cost) values ('Halmstad', 'Ipameri', 12777);
insert into offers (city_from, city_to, cost) values ('Penedono', 'Zhougao', 12603);
insert into offers (city_from, city_to, cost) values ('Susiec', 'Bantarpanjang', 23580);
insert into offers (city_from, city_to, cost) values ('Pampanito', 'Petřvald', 9676);
insert into offers (city_from, city_to, cost) values ('Sumberrojokrajan', 'Pore', 17118);
insert into offers (city_from, city_to, cost) values ('Starobaltachevo', 'Évreux', 9521);
insert into offers (city_from, city_to, cost) values ('Xinglong', 'Udi', 3090);
insert into offers (city_from, city_to, cost) values ('Kadubadak', 'Ōdate', 730);
insert into offers (city_from, city_to, cost) values ('Itaguaí', 'Raczki', 9488);
insert into offers (city_from, city_to, cost) values ('Prochowice', 'Mosteiros', 22614);
insert into offers (city_from, city_to, cost) values ('Kaliska', 'Turbaco', 6389);
insert into offers (city_from, city_to, cost) values ('Kidangbang', 'Canis', 6203);
insert into offers (city_from, city_to, cost) values ('Huajie', 'Khlong Hat', 16376);
insert into offers (city_from, city_to, cost) values ('Árta', 'Wukang', 10005);
insert into offers (city_from, city_to, cost) values ('Sidi Smaïl', 'Talok', 1850);
insert into offers (city_from, city_to, cost) values ('Al Khamīs', 'Trincomalee', 1064);
insert into offers (city_from, city_to, cost) values ('Labansari', 'Alcaria da Serra', 22078);
insert into offers (city_from, city_to, cost) values ('Columbus', 'Cachoeirinha', 15686);
insert into offers (city_from, city_to, cost) values ('Changshan', 'Karangsari', 5969);
insert into offers (city_from, city_to, cost) values ('Kotingnatagete', 'Ilhéus', 16631);
insert into offers (city_from, city_to, cost) values ('Nusajaya', 'Parista', 21331);
insert into offers (city_from, city_to, cost) values ('Chachoengsao', 'Spytkowice', 23267);
insert into offers (city_from, city_to, cost) values ('Kuala Terengganu', 'Pavlovskaya', 2637);
insert into offers (city_from, city_to, cost) values ('El Porvenir', 'Ertai', 19118);
insert into offers (city_from, city_to, cost) values ('Regente Feijó', 'Kaiyuan', 20520);
insert into offers (city_from, city_to, cost) values ('Jackson', 'Uyovu', 1065);
insert into offers (city_from, city_to, cost) values ('Monastyrshchina', 'Catanduva', 19570);
insert into offers (city_from, city_to, cost) values ('Mateus Leme', 'Tyszowce', 23696);
insert into offers (city_from, city_to, cost) values ('Wanzhi', 'Carcassonne', 11883);
insert into offers (city_from, city_to, cost) values ('Texistepeque', 'Baiima', 8375);
insert into offers (city_from, city_to, cost) values ('Kilingi-Nõmme', 'Pawonków', 11688);
insert into offers (city_from, city_to, cost) values ('As Saddah', 'Pilcaniyeu', 18974);
insert into offers (city_from, city_to, cost) values ('Sölvesborg', 'Anmore', 8404);
insert into offers (city_from, city_to, cost) values ('Tuzhu', 'Jämsänkoski', 3277);
insert into offers (city_from, city_to, cost) values ('Buchlovice', 'Kowary', 8509);
insert into offers (city_from, city_to, cost) values ('Jiangkou', 'Namling', 3161);
insert into offers (city_from, city_to, cost) values ('Shanghe', 'Alvaiázere', 17802);
insert into offers (city_from, city_to, cost) values ('Guangping', 'Marttila', 2347);
insert into offers (city_from, city_to, cost) values ('Yueyang', 'Çobansığnaq', 4184);
insert into offers (city_from, city_to, cost) values ('Sovetskaya', 'Viamão', 15706);
insert into offers (city_from, city_to, cost) values ('Pule', 'Hōjō', 21259);
insert into offers (city_from, city_to, cost) values ('Pretana', 'Skála', 18159);
insert into offers (city_from, city_to, cost) values ('Abangay', 'Olympia', 8713);
insert into offers (city_from, city_to, cost) values ('Mobile', 'Puger', 5568);
insert into offers (city_from, city_to, cost) values ('Kolmården', 'Bianxiong', 721);
insert into offers (city_from, city_to, cost) values ('Mākū', 'Jinzhuang', 6393);
insert into offers (city_from, city_to, cost) values ('Aricagua', 'Maputsoe', 1278);
insert into offers (city_from, city_to, cost) values ('Ibirama', 'Cirangga Kidul', 23761);
insert into offers (city_from, city_to, cost) values ('Fort-de-France', 'Shijing', 5753);
insert into offers (city_from, city_to, cost) values ('Moita', 'Březová nad Svitavou', 21691);
insert into offers (city_from, city_to, cost) values ('Gråbo', 'Wangtai', 2948);
insert into offers (city_from, city_to, cost) values ('Milltown', 'Manhan', 15861);
insert into offers (city_from, city_to, cost) values ('Jaguarão', 'Shangmofang', 20275);
insert into offers (city_from, city_to, cost) values ('Obong', 'Minneapolis', 16485);
insert into offers (city_from, city_to, cost) values ('Port-Vila', 'Marseille', 14823);
insert into offers (city_from, city_to, cost) values ('Zhumadian', 'Cereté', 3500);
insert into offers (city_from, city_to, cost) values ('Granada', 'Neglasari', 13724);
insert into offers (city_from, city_to, cost) values ('Placer', 'Ozherel’ye', 10695);
insert into offers (city_from, city_to, cost) values ('Bukowiec', 'Villanova', 2505);
insert into offers (city_from, city_to, cost) values ('Machalí', 'Ourentã', 20759);
insert into offers (city_from, city_to, cost) values ('Santai', 'Valladolid', 18430);
insert into offers (city_from, city_to, cost) values ('Kiuteta', 'San Miguel', 14646);
insert into offers (city_from, city_to, cost) values ('Pingyin', 'Obrera', 12820);
insert into offers (city_from, city_to, cost) values ('Mainri', 'Maqia', 12714);
insert into offers (city_from, city_to, cost) values ('Gengwan', 'Pasto', 7166);
insert into offers (city_from, city_to, cost) values ('Załuski', 'Dąbie', 16173);
insert into offers (city_from, city_to, cost) values ('Şabbūrah', 'Karangsari', 23318);
insert into offers (city_from, city_to, cost) values ('Qal‘ah-ye Shāhī', 'Kuncen', 10512);
insert into offers (city_from, city_to, cost) values ('Diébougou', 'Irapa', 1618);
insert into offers (city_from, city_to, cost) values ('Limen', 'Cértegui', 12514);
insert into offers (city_from, city_to, cost) values ('Épinal', 'Kadusirung Hilir', 21220);
insert into offers (city_from, city_to, cost) values ('Thanatpin', 'Marseille', 2092);
insert into offers (city_from, city_to, cost) values ('Seixas do Douro', 'Xujiahe', 956);
insert into offers (city_from, city_to, cost) values ('Pandangan Kulon', 'Marseille', 23027);
insert into offers (city_from, city_to, cost) values ('Limassol', 'Borlänge', 10257);
insert into offers (city_from, city_to, cost) values ('Jargalant', 'Karamat', 9753);
insert into offers (city_from, city_to, cost) values ('Saransk', 'Borås', 1314);
insert into offers (city_from, city_to, cost) values ('Kapitanivka', 'Pieksämäki', 16354);
insert into offers (city_from, city_to, cost) values ('Vilhena', 'Kebonagung', 23175);
insert into offers (city_from, city_to, cost) values ('Jacksonville', 'Xiaojiezi', 1121);
insert into offers (city_from, city_to, cost) values ('Bettendorf', 'Dongchen', 13610);
insert into offers (city_from, city_to, cost) values ('Pajapita', 'Lysogorskaya', 1012);
insert into offers (city_from, city_to, cost) values ('Rakhiv', 'Krasnogvardeyets', 10653);
insert into offers (city_from, city_to, cost) values ('Salingogan', 'João Alfredo', 16421);
insert into offers (city_from, city_to, cost) values ('Melun', 'Catalina', 8719);
insert into offers (city_from, city_to, cost) values ('Mudon', 'Longkou', 14164);
insert into offers (city_from, city_to, cost) values ('Faleula', 'Monte Patria', 23734);
insert into offers (city_from, city_to, cost) values ('Lugulu', 'Al ‘Aqabah', 898);
insert into offers (city_from, city_to, cost) values ('Zhucun', 'Boston', 6002);
insert into offers (city_from, city_to, cost) values ('Marcq-en-Barœul', 'Iyo', 5379);
insert into offers (city_from, city_to, cost) values ('Bobigny', 'Aquitania', 14162);
insert into offers (city_from, city_to, cost) values ('Bamusso', 'Hanfeng', 18131);
insert into offers (city_from, city_to, cost) values ('La Cesira', 'Na Chaluai', 18284);
insert into offers (city_from, city_to, cost) values ('Huasahuasi', 'Sanguanzhai', 12730);
insert into offers (city_from, city_to, cost) values ('Tsotsin-Yurt', 'Refojos de Riba de Ave', 6431);
insert into offers (city_from, city_to, cost) values ('Bordeaux', 'Mooirivier', 6609);
insert into offers (city_from, city_to, cost) values ('Vrilissia', 'Puerto Guzmán', 19238);
insert into offers (city_from, city_to, cost) values ('Huochang', 'Mikhaylovka', 14503);
insert into offers (city_from, city_to, cost) values ('New Orleans', 'Eci', 1489);
insert into offers (city_from, city_to, cost) values ('Xuefeng', 'Fangbu', 13104);
insert into offers (city_from, city_to, cost) values ('Dukuhtengah', 'Popova', 21522);
insert into offers (city_from, city_to, cost) values ('Pantai Ceuremen', 'Bancak Wetan', 3974);
insert into offers (city_from, city_to, cost) values ('Sua', 'Tarariras', 11224);
insert into offers (city_from, city_to, cost) values ('Linan', 'Dū Qal‘ah', 22473);
insert into offers (city_from, city_to, cost) values ('Launceston', 'Caja', 22525);
insert into offers (city_from, city_to, cost) values ('Xintun', 'Futang', 21726);
insert into offers (city_from, city_to, cost) values ('Thap Than', 'Póvoa', 20931);
insert into offers (city_from, city_to, cost) values ('Kalimati', 'Temblador', 14284);
insert into offers (city_from, city_to, cost) values ('Wanagiri', 'San Agustín', 5519);
insert into offers (city_from, city_to, cost) values ('Malambo', 'Pop Shahri', 16870);
insert into offers (city_from, city_to, cost) values ('Umeå', 'Przecław', 3257);
insert into offers (city_from, city_to, cost) values ('Blendis', 'Baiyanghe', 6724);
insert into offers (city_from, city_to, cost) values ('Nishio', 'Magalalag', 7346);
insert into offers (city_from, city_to, cost) values ('Liulang', 'Abakan', 978);
insert into offers (city_from, city_to, cost) values ('Chlumčany', 'Pasiragung', 12412);
insert into offers (city_from, city_to, cost) values ('Lloqan', 'Okazaki', 10731);
insert into offers (city_from, city_to, cost) values ('Kudinovo', 'Santa Rosa de Aguán', 22160);
insert into offers (city_from, city_to, cost) values ('Bandeirantes', 'Peroguarda', 23389);
insert into offers (city_from, city_to, cost) values ('Palana', 'Zomba', 12918);
insert into offers (city_from, city_to, cost) values ('Khorosheve', 'Örebro', 11188);
insert into offers (city_from, city_to, cost) values ('Saint-Quentin', 'Moch', 3513);
insert into offers (city_from, city_to, cost) values ('Ngancar', 'Sarkanjut', 9358);
insert into offers (city_from, city_to, cost) values ('Horní Jelení', 'Tuguan', 15125);
insert into offers (city_from, city_to, cost) values ('Ballyboden', 'Blois', 4185);
insert into offers (city_from, city_to, cost) values ('Buan', 'Pamoyanan', 6832);
insert into offers (city_from, city_to, cost) values ('Arrentela', 'Sainte-Sophie', 10227);
insert into offers (city_from, city_to, cost) values ('Potlot', 'Plácido de Castro', 20488);
insert into offers (city_from, city_to, cost) values ('Ménaka', 'Marília', 18925);
insert into offers (city_from, city_to, cost) values ('Xiaoqi', 'Hammarö', 14228);
insert into offers (city_from, city_to, cost) values ('Hedong', 'Kaduengang', 796);
insert into offers (city_from, city_to, cost) values ('Västerås', 'Barreiros', 7622);
insert into offers (city_from, city_to, cost) values ('Huangyang', 'Martingança-Gare', 2526);
insert into offers (city_from, city_to, cost) values ('Jatirogo', 'Tournon-sur-Rhône', 22744);
insert into offers (city_from, city_to, cost) values ('Mobai', 'Aulnay-sous-Bois', 21108);
insert into offers (city_from, city_to, cost) values ('Gaza', 'Bolorejo', 5438);
insert into offers (city_from, city_to, cost) values ('Ludza', 'Budënnovsk', 15164);
insert into offers (city_from, city_to, cost) values ('Göteborg', 'Puerto Quellón', 6759);
insert into offers (city_from, city_to, cost) values ('Santiago', 'Yanwukou', 10958);
insert into offers (city_from, city_to, cost) values ('Lela', 'Teluk Pinang', 3863);
insert into offers (city_from, city_to, cost) values ('Bakhmach', 'Jishigang', 17979);
insert into offers (city_from, city_to, cost) values ('San Buenaventura', 'Dob', 2697);
insert into offers (city_from, city_to, cost) values ('Sokoto', 'San Jerónimo', 12250);
insert into offers (city_from, city_to, cost) values ('Taesal-li', 'Todorovo', 18750);
insert into offers (city_from, city_to, cost) values ('Maroantsetra', 'Jiaodai', 8478);
insert into offers (city_from, city_to, cost) values ('Masparrito', 'Aachen', 830);
insert into offers (city_from, city_to, cost) values ('Ḥurfeish', 'Lanxi', 18073);
insert into offers (city_from, city_to, cost) values ('Sanjiao', 'Belfast', 5967);
insert into offers (city_from, city_to, cost) values ('Varva', 'Linjiang', 16164);
insert into offers (city_from, city_to, cost) values ('Chat Trakan', 'Mirovice', 15976);
insert into offers (city_from, city_to, cost) values ('New York City', 'Alor Setar', 1554);
insert into offers (city_from, city_to, cost) values ('Sala', 'Kolonia Town', 23575);
insert into offers (city_from, city_to, cost) values ('Gizo', 'Évry', 22798);
insert into offers (city_from, city_to, cost) values ('Sātkania', 'Girang', 16370);
insert into offers (city_from, city_to, cost) values ('Fécamp', 'Kiten', 4215);
insert into offers (city_from, city_to, cost) values ('Khulo', 'Simpangpasir', 15392);
insert into offers (city_from, city_to, cost) values ('Porteirinha', 'Västervik', 16045);
insert into offers (city_from, city_to, cost) values ('Gushan', 'Hanfeng', 15216);
insert into offers (city_from, city_to, cost) values ('Ouro Branco', 'Doumuhu', 11751);
insert into offers (city_from, city_to, cost) values ('La Cocha', 'Losino-Petrovskiy', 5066);
insert into offers (city_from, city_to, cost) values ('Tarrafal', 'Qalyūb', 19205);
insert into offers (city_from, city_to, cost) values ('Pasaco', 'Poshnje', 5286);
insert into offers (city_from, city_to, cost) values ('Yangpu', 'Divnomorskoye', 20774);
insert into offers (city_from, city_to, cost) values ('Il’inskiy Pogost', 'Viljandi', 9833);
insert into offers (city_from, city_to, cost) values ('Yuhuazhai', 'Madīnat ash Shamāl', 18234);
insert into offers (city_from, city_to, cost) values ('El Copé', 'Amadora', 20618);
insert into offers (city_from, city_to, cost) values ('Grubišno Polje', 'Fómeque', 21791);
insert into offers (city_from, city_to, cost) values ('Jami', 'Washington', 5249);
insert into offers (city_from, city_to, cost) values ('Maqia', 'Bol’shaya Setun’', 14611);
insert into offers (city_from, city_to, cost) values ('Quinta', 'Beopwon', 4837);
insert into offers (city_from, city_to, cost) values ('Kolochava', 'Würzburg', 8049);
insert into offers (city_from, city_to, cost) values ('Volkhov', 'Lesnoy', 18614);
insert into offers (city_from, city_to, cost) values ('Noebesa', 'Manicahan', 23731);
insert into offers (city_from, city_to, cost) values ('Podgórzyn', 'Cuba', 6632);
insert into offers (city_from, city_to, cost) values ('Kungshamn', 'Lille', 16671);
insert into offers (city_from, city_to, cost) values ('Panao', 'Banjar Pedawa', 22893);
insert into offers (city_from, city_to, cost) values ('Kudinovo', 'Beicheng', 8907);
insert into offers (city_from, city_to, cost) values ('Bánica', 'Bonavista', 10373);
insert into offers (city_from, city_to, cost) values ('Tanjung Kidul', 'Presa', 22457);
insert into offers (city_from, city_to, cost) values ('Tofa', 'Zhentou', 2636);
insert into offers (city_from, city_to, cost) values ('Osorno', 'Carregado', 20729);
insert into offers (city_from, city_to, cost) values ('Cabano', 'Cordeiro', 7277);
insert into offers (city_from, city_to, cost) values ('Kapatagan', 'Hargeysa', 11819);
insert into offers (city_from, city_to, cost) values ('Saint-Jean-de-Monts', 'Ad Dujayl', 12674);
insert into offers (city_from, city_to, cost) values ('Jiangna', 'Lyon', 16419);
insert into offers (city_from, city_to, cost) values ('Cajamar', 'Dālbandīn', 10361);
insert into offers (city_from, city_to, cost) values ('Baimi', 'Chantepie', 9412);
insert into offers (city_from, city_to, cost) values ('Villefranche-sur-Mer', 'Brodnica', 23297);
insert into offers (city_from, city_to, cost) values ('Van Nuys', 'Looc', 6494);
insert into offers (city_from, city_to, cost) values ('Boshof', 'Guansheng', 11070);
insert into offers (city_from, city_to, cost) values ('Graz', 'Kotakaya Dua', 18854);
insert into offers (city_from, city_to, cost) values ('Sanyi', 'Darungan', 20235);
insert into offers (city_from, city_to, cost) values ('Cachan', 'Khotiv', 7714);
insert into offers (city_from, city_to, cost) values ('Yilan', 'Zavet', 20727);
insert into offers (city_from, city_to, cost) values ('Dobri Dol', 'Gapuk', 3394);
insert into offers (city_from, city_to, cost) values ('Mielec', 'Sá', 22113);
insert into offers (city_from, city_to, cost) values ('Al Ḩarf', 'Myitkyina', 23862);
insert into offers (city_from, city_to, cost) values ('Altavista', 'Pandan', 12311);
insert into offers (city_from, city_to, cost) values ('Dhahab', 'Pakembangan', 3065);
insert into offers (city_from, city_to, cost) values ('Ust’-Labinsk', 'Osias', 17969);
insert into offers (city_from, city_to, cost) values ('Stockholm', 'Huimin', 1085);
insert into offers (city_from, city_to, cost) values ('Bayt Qād', 'Konice', 5818);
insert into offers (city_from, city_to, cost) values ('Santi Suk', 'Boudinar', 2621);
insert into offers (city_from, city_to, cost) values ('Alebtong', 'Radišići', 22866);
insert into offers (city_from, city_to, cost) values ('Shushicë', 'Doljevac', 10048);
insert into offers (city_from, city_to, cost) values ('Kusak', 'Detupia', 23496);
insert into offers (city_from, city_to, cost) values ('Otjimbingwe', 'Petit Valley', 5480);
insert into offers (city_from, city_to, cost) values ('Mingjing', 'Kamalasai', 5697);
insert into offers (city_from, city_to, cost) values ('Quatro Barras', 'Rongcheng', 527);
insert into offers (city_from, city_to, cost) values ('Bello', 'Shen’ao', 18156);
insert into offers (city_from, city_to, cost) values ('Piedras', 'Trzin', 23837);
insert into offers (city_from, city_to, cost) values ('Lluidas Vale', 'Shanghang', 21910);
insert into offers (city_from, city_to, cost) values ('Malya', 'Atengmelang', 5954);
insert into offers (city_from, city_to, cost) values ('Prang Ku', 'Yixing', 16596);
insert into offers (city_from, city_to, cost) values ('Bezlyudivka', 'Caen', 8634);
insert into offers (city_from, city_to, cost) values ('Samouco', 'Shahbā', 14915);
insert into offers (city_from, city_to, cost) values ('Tanda', 'Kan’onjichō', 15432);
insert into offers (city_from, city_to, cost) values ('Drummondville', 'Anju', 19894);
insert into offers (city_from, city_to, cost) values ('Kende', 'El Retorno', 12688);
insert into offers (city_from, city_to, cost) values ('Segbwema', 'Muroran', 1050);
insert into offers (city_from, city_to, cost) values ('Yaozhanzi', 'Bueng Kan', 11021);
insert into offers (city_from, city_to, cost) values ('Ipoh', 'Satuek', 17543);
insert into offers (city_from, city_to, cost) values ('Heling', 'Manggu', 4882);
insert into offers (city_from, city_to, cost) values ('Qiaodong', 'Brandfort', 12119);
insert into offers (city_from, city_to, cost) values ('Enköping', 'Pueblo Nuevo Viñas', 12334);
insert into offers (city_from, city_to, cost) values ('Tambak', 'Hưng Nguyên', 1821);
insert into offers (city_from, city_to, cost) values ('Radeče', 'Liminka', 19807);
insert into offers (city_from, city_to, cost) values ('Iñapari', 'Xiazhai', 21852);
insert into offers (city_from, city_to, cost) values ('Khorol', 'Rennes', 12582);
insert into offers (city_from, city_to, cost) values ('Täby', 'Shimen', 23307);
insert into offers (city_from, city_to, cost) values ('Newton', 'Markaz al Marīr', 20654);
insert into offers (city_from, city_to, cost) values ('Zhujiang', 'San Luis', 12337);
insert into offers (city_from, city_to, cost) values ('Bohai', 'Jagodnjak', 21950);
insert into offers (city_from, city_to, cost) values ('Heihe', 'Daxin', 629);
insert into offers (city_from, city_to, cost) values ('Biguo', 'Varberg', 7454);
insert into offers (city_from, city_to, cost) values ('Laholm', 'Muñoz East', 22241);
insert into offers (city_from, city_to, cost) values ('Pandan', 'Kwangmyŏng', 677);
insert into offers (city_from, city_to, cost) values ('Al Maşlūb', 'Saint-Dié-des-Vosges', 6035);
insert into offers (city_from, city_to, cost) values ('Sukabatu', 'Pocohuanca', 22440);
insert into offers (city_from, city_to, cost) values ('Dabu', 'Coro', 22182);
insert into offers (city_from, city_to, cost) values ('Žrnovo', 'El Pino', 18619);
insert into offers (city_from, city_to, cost) values ('Ključ', 'Dourbali', 10797);
insert into offers (city_from, city_to, cost) values ('El Peñol', 'Jiufeng', 13287);
insert into offers (city_from, city_to, cost) values ('Zubūbah', 'Nayoro', 15971);
insert into offers (city_from, city_to, cost) values ('Volot', 'Hongshan', 19068);
insert into offers (city_from, city_to, cost) values ('Nunmanu', 'Kalajoki', 4571);
insert into offers (city_from, city_to, cost) values ('Aquin', 'Zhangshi', 8268);
insert into offers (city_from, city_to, cost) values ('Ol Kalou', 'Trondheim', 22110);
insert into offers (city_from, city_to, cost) values ('Lucban', 'Gampola', 4979);
insert into offers (city_from, city_to, cost) values ('Atlanta', 'Zheyuan', 4167);
insert into offers (city_from, city_to, cost) values ('Lyon', 'Bourges', 714);
insert into offers (city_from, city_to, cost) values ('Peachland', 'Kokubu-matsuki', 18052);
insert into offers (city_from, city_to, cost) values ('Semarang', 'Sucun', 17196);
insert into offers (city_from, city_to, cost) values ('Nashville', 'Kota Kinabalu', 11983);
insert into offers (city_from, city_to, cost) values ('Manoel Urbano', 'Proença-a-Nova', 9391);
insert into offers (city_from, city_to, cost) values ('Las Yaras', 'Ciorescu', 13316);
insert into offers (city_from, city_to, cost) values ('Trinidad', 'Agrínio', 6142);
insert into offers (city_from, city_to, cost) values ('Värnamo', 'Chixi', 16725);
insert into offers (city_from, city_to, cost) values ('Złoty Stok', 'Sandviken', 5863);
insert into offers (city_from, city_to, cost) values ('Komsomolsk-on-Amur', 'Guider', 11709);
insert into offers (city_from, city_to, cost) values ('Melaka', 'Huaquirca', 20736);
insert into offers (city_from, city_to, cost) values ('Aráchova', 'Xianhe', 9396);
insert into offers (city_from, city_to, cost) values ('Turets-Bayary', 'Belyye Stolby', 18144);
insert into offers (city_from, city_to, cost) values ('Wang Noi', 'Solingen', 17916);
insert into offers (city_from, city_to, cost) values ('Avdzaga', 'Tembayangan Barat', 854);
insert into offers (city_from, city_to, cost) values ('Cipadung', 'Jatiprahu', 13622);
insert into offers (city_from, city_to, cost) values ('Calhetas', 'Shlissel’burg', 11813);
insert into offers (city_from, city_to, cost) values ('Federal', 'Valvedditturai', 12670);
insert into offers (city_from, city_to, cost) values ('That Phanom', 'Desa Borogojol', 20938);
insert into offers (city_from, city_to, cost) values ('Niemodlin', 'San Isidro', 11591);
insert into offers (city_from, city_to, cost) values ('Changsheng', 'Tours', 11741);
insert into offers (city_from, city_to, cost) values ('Drybin', 'Odawara', 19827);
insert into offers (city_from, city_to, cost) values ('Beaune', 'Florianópolis', 819);
insert into offers (city_from, city_to, cost) values ('Pointe-à-Pitre', 'Cowansville', 14521);
insert into offers (city_from, city_to, cost) values ('Parigi', 'Krasnodar', 23339);
insert into offers (city_from, city_to, cost) values ('Sindangjati', 'La Mesa', 23270);
insert into offers (city_from, city_to, cost) values ('Neuilly-sur-Seine', 'Khānewāl', 15827);
insert into offers (city_from, city_to, cost) values ('Vanadzor', 'Pertunmaa', 20135);
insert into offers (city_from, city_to, cost) values ('Sanshandao', 'Huxingshan', 15211);
insert into offers (city_from, city_to, cost) values ('Muikamachi', 'Chitagá', 4896);
insert into offers (city_from, city_to, cost) values ('Xiashu', 'George Hill', 15834);
insert into offers (city_from, city_to, cost) values ('Hongguang', 'Kolokani', 13275);
insert into offers (city_from, city_to, cost) values ('Hīsh', 'Mosal’sk', 11103);
insert into offers (city_from, city_to, cost) values ('Guandi', 'Radenka', 20306);
insert into offers (city_from, city_to, cost) values ('Tanabe', 'Telsiai', 14450);
insert into offers (city_from, city_to, cost) values ('Capiíbary', 'Camargo', 1081);
insert into offers (city_from, city_to, cost) values ('Embarcación', 'Göteborg', 3853);
insert into offers (city_from, city_to, cost) values ('Ciechocin', 'Blimbing', 22830);
insert into offers (city_from, city_to, cost) values ('Ujae', 'Wonorejo Dua', 21337);
insert into offers (city_from, city_to, cost) values ('Cibingbin', 'Sarapul', 7415);
insert into offers (city_from, city_to, cost) values ('Sergio Osmeña Sr', 'Farah', 22873);
insert into offers (city_from, city_to, cost) values ('Mayong', 'Balinad', 15150);
insert into offers (city_from, city_to, cost) values ('Magisterial', 'Strasbourg', 12573);
insert into offers (city_from, city_to, cost) values ('Laraos', 'Dzhankoy', 3825);
insert into offers (city_from, city_to, cost) values ('Vitim', 'Quilmaná', 9940);
insert into offers (city_from, city_to, cost) values ('Dazhou', 'Katuli', 9133);
insert into offers (city_from, city_to, cost) values ('Maglaj', 'Cimanggu Girang', 6298);
insert into offers (city_from, city_to, cost) values ('Sanghan', 'Fontainhas', 15812);
insert into offers (city_from, city_to, cost) values ('Göteborg', 'Jarocin', 16552);
insert into offers (city_from, city_to, cost) values ('Leiwang', 'Kigoma', 9382);
insert into offers (city_from, city_to, cost) values ('Alaghsas', 'Vista Alegre', 3716);
insert into offers (city_from, city_to, cost) values ('Māmu Kānjan', 'Khulo', 11907);
insert into offers (city_from, city_to, cost) values ('Sabana Grande de Boyá', 'Rublëvo', 5539);
insert into offers (city_from, city_to, cost) values ('Geshan', 'Ayorou', 705);
insert into offers (city_from, city_to, cost) values ('Sinait', 'Angra dos Reis', 1373);
insert into offers (city_from, city_to, cost) values ('Jedung', 'Zhendong', 11001);
insert into offers (city_from, city_to, cost) values ('Francisco Sarabia', 'Vårgårda', 23186);
insert into offers (city_from, city_to, cost) values ('Longgang', 'Dallas', 13888);
insert into offers (city_from, city_to, cost) values ('Rio Novo do Sul', 'Caotang', 11346);
insert into offers (city_from, city_to, cost) values ('Igreja', 'Futaleufú', 23647);
insert into offers (city_from, city_to, cost) values ('Diriamba', 'Huolianpo', 18100);
insert into offers (city_from, city_to, cost) values ('Hengelo', 'San Jose', 17897);
insert into offers (city_from, city_to, cost) values ('Kurumkan', 'Cuihuangkou', 9161);
insert into offers (city_from, city_to, cost) values ('Al Ḩammāmāt', 'Pittsburgh', 7554);
insert into offers (city_from, city_to, cost) values ('Pamanukan', 'San Juan de Dios', 8821);
insert into offers (city_from, city_to, cost) values ('Duisburg', 'Vitry-sur-Seine', 7902);
insert into offers (city_from, city_to, cost) values ('Khadan Khāk', 'Garajati', 23336);
insert into offers (city_from, city_to, cost) values ('Tõrva', 'Xiaojiangba', 13656);
insert into offers (city_from, city_to, cost) values ('Drumcondra', 'Zhongxing', 5107);
insert into offers (city_from, city_to, cost) values ('Atar', 'Chiguirip', 10207);
insert into offers (city_from, city_to, cost) values ('La Palma', 'Cololaca', 16576);
insert into offers (city_from, city_to, cost) values ('Toyonaka', 'Changling', 1695);
insert into offers (city_from, city_to, cost) values ('Shanjeev Home', 'Marks', 16889);
insert into offers (city_from, city_to, cost) values ('Przeworsk', 'Belfast', 22296);
insert into offers (city_from, city_to, cost) values ('Klippan', 'Härnösand', 7043);
insert into offers (city_from, city_to, cost) values ('Seulimeum', 'Těšany', 18077);
insert into offers (city_from, city_to, cost) values ('Shanxia', 'Uchaly', 14796);
insert into offers (city_from, city_to, cost) values ('Lijiaping', 'Kariya', 17694);
insert into offers (city_from, city_to, cost) values ('Lins', 'Cochadas', 2954);
insert into offers (city_from, city_to, cost) values ('Kallithéa', 'Xylókastro', 19617);
insert into offers (city_from, city_to, cost) values ('Nsanje', 'Gardēz', 7845);
insert into offers (city_from, city_to, cost) values ('Denver', 'Lukunor', 14476);
insert into offers (city_from, city_to, cost) values ('Sumberpitu', 'Marína', 17032);
insert into offers (city_from, city_to, cost) values ('Struga', 'Tanashichō', 15406);
insert into offers (city_from, city_to, cost) values ('Courtaboeuf', 'Balitai', 14575);
insert into offers (city_from, city_to, cost) values ('Rosário do Sul', 'Bang Ban', 11906);
insert into offers (city_from, city_to, cost) values ('Jiangwan', 'Kultayevo', 4645);
insert into offers (city_from, city_to, cost) values ('Ulimonong', 'Kurumoch', 7827);
insert into offers (city_from, city_to, cost) values ('Fada', 'António Enes', 4511);
insert into offers (city_from, city_to, cost) values ('Zarasai', 'Rājbirāj', 13195);
insert into offers (city_from, city_to, cost) values ('Nagornyy', 'Sidonganti', 20761);
insert into offers (city_from, city_to, cost) values ('Vermil', 'Beringovskiy', 22248);
insert into offers (city_from, city_to, cost) values ('Privodino', 'Oranjestad', 14456);
insert into offers (city_from, city_to, cost) values ('Ayacucho', 'Leones', 19349);
insert into offers (city_from, city_to, cost) values ('Quillabamba', 'Gempol', 13908);
insert into offers (city_from, city_to, cost) values ('Poykovskiy', 'Yashalta', 17407);
insert into offers (city_from, city_to, cost) values ('Kukur', 'Rožaje', 21605);
insert into offers (city_from, city_to, cost) values ('Xiongjia', 'Nong Phok', 4386);
insert into offers (city_from, city_to, cost) values ('Manutapen', 'Springfield', 5608);
insert into offers (city_from, city_to, cost) values ('Los Algarrobos', 'La Laguna', 5554);
insert into offers (city_from, city_to, cost) values ('Iizuka', 'Jelat', 4244);
insert into offers (city_from, city_to, cost) values ('Perstorp', 'Sumpur Kudus', 16959);
insert into offers (city_from, city_to, cost) values ('Gujō', 'Sanhe', 11933);
insert into offers (city_from, city_to, cost) values ('Ruda Maleniecka', 'Guantang', 10840);
insert into offers (city_from, city_to, cost) values ('Kota Kinabalu', 'Beigong', 23766);
insert into offers (city_from, city_to, cost) values ('Linfen', 'Kericho', 4176);
insert into offers (city_from, city_to, cost) values ('Umeå', 'Inazawa', 17555);
insert into offers (city_from, city_to, cost) values ('Hatsukaichi', 'Blučina', 15091);
insert into offers (city_from, city_to, cost) values ('Nakovo', 'Turtas', 21697);
insert into offers (city_from, city_to, cost) values ('Nueva Imperial', 'Banjar Jabejero', 22046);
insert into offers (city_from, city_to, cost) values ('Acul du Nord', 'Belogorskīy', 8770);
insert into offers (city_from, city_to, cost) values ('Santo Amaro', 'Dongjian', 14043);
insert into offers (city_from, city_to, cost) values ('Tartu', 'Sernancelhe', 1838);
insert into offers (city_from, city_to, cost) values ('Norrköping', 'Itapema', 17160);
insert into offers (city_from, city_to, cost) values ('Taibai', 'Asnières-sur-Seine', 6665);
insert into offers (city_from, city_to, cost) values ('Wufeng', 'Alaverdi', 12276);
insert into offers (city_from, city_to, cost) values ('Lohong', 'Nioro', 9966);
insert into offers (city_from, city_to, cost) values ('Kutloanong', 'Nalbandyan', 3912);
insert into offers (city_from, city_to, cost) values ('San Jose', 'Trà Vinh', 3870);
insert into offers (city_from, city_to, cost) values ('Ngilengan', 'Chaiyaphum', 14694);
insert into offers (city_from, city_to, cost) values ('Shuangxiqiao', 'Kharkiv', 20572);
insert into offers (city_from, city_to, cost) values ('Banjar Kelodan', 'Knoxville', 16341);
insert into offers (city_from, city_to, cost) values ('Zhireken', 'Gävle', 8292);
insert into offers (city_from, city_to, cost) values ('Pau', 'Xiaolukou', 6052);
insert into offers (city_from, city_to, cost) values ('Mattaldi', 'Sanpai', 548);
insert into offers (city_from, city_to, cost) values ('Maha Sarakham', 'Ligang', 2043);
insert into offers (city_from, city_to, cost) values ('Radojevo', 'Colosó', 21159);
insert into offers (city_from, city_to, cost) values ('Tanjung Palas', 'Stryszawa', 19824);
insert into offers (city_from, city_to, cost) values ('Paola', 'Santiago de los Caballeros', 431);
insert into offers (city_from, city_to, cost) values ('Limanancong', 'Witihama', 14366);
insert into offers (city_from, city_to, cost) values ('Frederiksberg', 'Shazi', 7177);
insert into offers (city_from, city_to, cost) values ('''s-Hertogenbosch', 'Chrást', 8937);
insert into offers (city_from, city_to, cost) values ('Novopokrovka', 'Ohrid', 22588);
insert into offers (city_from, city_to, cost) values ('Kertabumi', 'Baler Baleagung', 16421);
insert into offers (city_from, city_to, cost) values ('Chřibská', 'Gunungangka', 7947);
insert into offers (city_from, city_to, cost) values ('Zborovice', 'Göteborg', 16105);
insert into offers (city_from, city_to, cost) values ('Šmarje pri Jelšah', 'Miguel Hidalgo', 16204);
insert into offers (city_from, city_to, cost) values ('Baisha', 'Potoni', 15211);
insert into offers (city_from, city_to, cost) values ('Ngrejo', 'Dolulolong', 6190);
insert into offers (city_from, city_to, cost) values ('Baiguo', 'Paris 19', 6848);
insert into offers (city_from, city_to, cost) values ('Cikalaces', 'Libertad', 13815);
insert into offers (city_from, city_to, cost) values ('Huarong', 'Solţānābād', 7844);
insert into offers (city_from, city_to, cost) values ('Stockholm', 'Czarna Białostocka', 17213);
insert into offers (city_from, city_to, cost) values ('Quzi', 'Labo', 9140);
insert into offers (city_from, city_to, cost) values ('Xiaoguwei', 'Nueva Imperial', 9639);
insert into offers (city_from, city_to, cost) values ('Olsztyn', 'Liangwangzhuang', 21507);
insert into offers (city_from, city_to, cost) values ('Ol’gino', 'Pokachi', 15812);
insert into offers (city_from, city_to, cost) values ('Oesapa', 'Santo Amaro', 4090);
insert into offers (city_from, city_to, cost) values ('La Bélgica', 'Mouquim', 21403);
insert into offers (city_from, city_to, cost) values ('Lautoka', 'Clarin', 15327);
insert into offers (city_from, city_to, cost) values ('Veiros', 'Mastung', 17863);
insert into offers (city_from, city_to, cost) values ('Mitú', 'Ikeja', 3530);
insert into offers (city_from, city_to, cost) values ('Imbituva', 'Qingxi', 5332);
insert into offers (city_from, city_to, cost) values ('Dourados', 'Farīdpur', 12594);
insert into offers (city_from, city_to, cost) values ('Jianping', 'Xinxian', 6829);
insert into offers (city_from, city_to, cost) values ('Hongsi', 'Jimsar', 7616);
insert into offers (city_from, city_to, cost) values ('Luleå', 'Garisul', 10542);
insert into offers (city_from, city_to, cost) values ('Andovoranto', 'Burgos', 13928);
insert into offers (city_from, city_to, cost) values ('Rumilly', 'Champaign', 15508);
insert into offers (city_from, city_to, cost) values ('Santyoku', 'Mzuzu', 14039);
insert into offers (city_from, city_to, cost) values ('Jaba‘', 'Gotse Delchev', 6276);
insert into offers (city_from, city_to, cost) values ('Buíque', 'Minante Segundo', 12914);
insert into offers (city_from, city_to, cost) values ('Xinqiao', 'Esteio', 23227);
insert into offers (city_from, city_to, cost) values ('Dahao', 'Novohrad-Volyns’kyy', 19603);
insert into offers (city_from, city_to, cost) values ('Phú Khương', 'Peñarrubia', 20503);
insert into offers (city_from, city_to, cost) values ('Heshui', 'Gamay', 3833);
insert into offers (city_from, city_to, cost) values ('Lobuk', 'Velké Němčice', 6015);
insert into offers (city_from, city_to, cost) values ('Xiaochi', 'Beauvais', 561);
insert into offers (city_from, city_to, cost) values ('Thị Trấn Thanh Lưu', 'Yangqiao', 5947);
insert into offers (city_from, city_to, cost) values ('Hejiabao', 'Florestópolis', 4924);
insert into offers (city_from, city_to, cost) values ('Sann', 'Songdong', 2285);
insert into offers (city_from, city_to, cost) values ('Tiehe', 'Brejo Santo', 9962);
insert into offers (city_from, city_to, cost) values ('Daykitin', 'Mulino', 2047);
insert into offers (city_from, city_to, cost) values ('Lidingö', 'Mutengene', 23677);
insert into offers (city_from, city_to, cost) values ('Berlin', 'Chinhoyi', 745);
insert into offers (city_from, city_to, cost) values ('Örebro', 'Karangpaningal', 5687);
insert into offers (city_from, city_to, cost) values ('Fengjiang', 'Yangjiaqiao', 20308);
insert into offers (city_from, city_to, cost) values ('Jingxiyuan', 'Kamensk-Shakhtinskiy', 22509);
insert into offers (city_from, city_to, cost) values ('Liopétri', 'Sarlat-la-Canéda', 7518);
insert into offers (city_from, city_to, cost) values ('Pegongan', 'Consolacion', 461);
insert into offers (city_from, city_to, cost) values ('Tamianglayang', 'Nyurba', 20230);
insert into offers (city_from, city_to, cost) values ('Načeradec', 'Zall-Herr', 19558);
insert into offers (city_from, city_to, cost) values ('Goshogawara', 'Tapada das Mercês', 13541);
insert into offers (city_from, city_to, cost) values ('Jiebu', 'Barguzin', 7175);
insert into offers (city_from, city_to, cost) values ('Ouanaminthe', 'Hongjiaguan', 17080);
insert into offers (city_from, city_to, cost) values ('Winburg', 'Staten Island', 4915);
insert into offers (city_from, city_to, cost) values ('Cahabón', 'Martanesh', 5464);
insert into offers (city_from, city_to, cost) values ('Ratnapura', 'Negara', 18730);
insert into offers (city_from, city_to, cost) values ('León', 'Krajan Sumberanget', 20502);
insert into offers (city_from, city_to, cost) values ('Zhulin', 'Panguipulli', 22092);
insert into offers (city_from, city_to, cost) values ('Jingguan', 'Khemisset', 22665);
insert into offers (city_from, city_to, cost) values ('Chaloem Phra Kiat', 'Darenzhuang', 4845);
insert into offers (city_from, city_to, cost) values ('Debre Tabor', 'Jiawu', 18672);
insert into offers (city_from, city_to, cost) values ('Vrdy', 'Il’ichëvo', 6969);
insert into offers (city_from, city_to, cost) values ('Paranaíba', 'Angadanan', 17295);
insert into offers (city_from, city_to, cost) values ('Silab', 'Juazeiro do Norte', 10970);
insert into offers (city_from, city_to, cost) values ('Lagunillas', 'Baisha', 3110);
insert into offers (city_from, city_to, cost) values ('Solna', 'Nagai', 18659);
insert into offers (city_from, city_to, cost) values ('Lanús', 'Fangxi', 521);
insert into offers (city_from, city_to, cost) values ('Muting', 'Dalang', 5445);
insert into offers (city_from, city_to, cost) values ('Benito Juarez', 'Liuji', 6925);
insert into offers (city_from, city_to, cost) values ('Sokol', 'Makui', 16704);
insert into offers (city_from, city_to, cost) values ('Bankaw', 'Alvarães', 2567);
insert into offers (city_from, city_to, cost) values ('Debre Tabor', 'Basel', 4015);
insert into offers (city_from, city_to, cost) values ('Kuala Lumpur', 'Bambang', 23599);
insert into offers (city_from, city_to, cost) values ('Cerquilho', 'Göteborg', 23019);
insert into offers (city_from, city_to, cost) values ('Gaoshan', 'Maying', 2504);
insert into offers (city_from, city_to, cost) values ('Thị Trấn Hùng Quốc', 'Chiguayante', 6294);
insert into offers (city_from, city_to, cost) values ('Kankara', 'Chigang', 2798);
insert into offers (city_from, city_to, cost) values ('Paris La Défense', 'Koubia', 2561);
insert into offers (city_from, city_to, cost) values ('Rettikhovka', 'Accha', 20642);
insert into offers (city_from, city_to, cost) values ('Round Rock', 'Sidi Slimane', 9798);
insert into offers (city_from, city_to, cost) values ('Sadská', 'Narew', 18294);
insert into offers (city_from, city_to, cost) values ('Yamaga', 'eMbalenhle', 22677);
insert into offers (city_from, city_to, cost) values ('Bicos', 'Bilozerka', 10356);
insert into offers (city_from, city_to, cost) values ('Orlando', 'Shuijiang', 16368);
insert into offers (city_from, city_to, cost) values ('Dorval', 'São Gabriel da Cachoeira', 14359);
insert into offers (city_from, city_to, cost) values ('Horní Cerekev', 'Salaza', 22882);
insert into offers (city_from, city_to, cost) values ('Enschede', 'Longwood', 5703);
insert into offers (city_from, city_to, cost) values ('Palayan City', 'Wolanów', 20844);
insert into offers (city_from, city_to, cost) values ('Dachun', 'Estrada', 15418);
insert into offers (city_from, city_to, cost) values ('Bañga', 'Watari', 6341);
insert into offers (city_from, city_to, cost) values ('Töysä', 'Makīnsk', 9479);
insert into offers (city_from, city_to, cost) values ('Trzebunia', 'Qarāwul', 13756);
insert into offers (city_from, city_to, cost) values ('Huoxian', 'Yousheng', 7392);
insert into offers (city_from, city_to, cost) values ('Atakpamé', 'Warungsugan', 6252);
insert into offers (city_from, city_to, cost) values ('Chiquinquirá', 'Carrazeda de Ansiães', 8221);
insert into offers (city_from, city_to, cost) values ('Krapina', 'Koga', 15268);
insert into offers (city_from, city_to, cost) values ('Diourbel', 'Hinigaran', 6409);
insert into offers (city_from, city_to, cost) values ('Tibiri', 'Topdac', 17319);
insert into offers (city_from, city_to, cost) values ('Qabqir', 'Ural', 9781);
insert into offers (city_from, city_to, cost) values ('Tha Yang', 'Saint Cloud', 16982);
insert into offers (city_from, city_to, cost) values ('Damiku', 'Patrocínio', 20681);
insert into offers (city_from, city_to, cost) values ('Tanbuqiao', 'Kristiansand S', 1844);
insert into offers (city_from, city_to, cost) values ('Chengji', 'Tanggan', 15366);
insert into offers (city_from, city_to, cost) values ('Brdów', 'Soavinandriana', 13878);
insert into offers (city_from, city_to, cost) values ('Xinkai', 'Huangshi', 4130);
insert into offers (city_from, city_to, cost) values ('Mora', 'Dzhiginka', 3448);
insert into offers (city_from, city_to, cost) values ('Yang Chum Noi', 'Domoni', 21051);
insert into offers (city_from, city_to, cost) values ('Charleville-Mézières', 'Las Palmas', 16379);
insert into offers (city_from, city_to, cost) values ('Littleton', 'Alikalia', 6992);
insert into offers (city_from, city_to, cost) values ('Liukou', 'Shigu', 22412);
insert into offers (city_from, city_to, cost) values ('Sieroszewice', 'Lužani', 11463);
insert into offers (city_from, city_to, cost) values ('Arkhaía Kórinthos', 'Ngulahan', 5102);
insert into offers (city_from, city_to, cost) values ('Wangshi', 'Xai-Xai', 15188);
insert into offers (city_from, city_to, cost) values ('San Marcos', 'Bandjoun', 1931);
insert into offers (city_from, city_to, cost) values ('Melbourne', 'Mayuge', 17882);
insert into offers (city_from, city_to, cost) values ('Azenhas do Mar', 'Thị Trấn Pác Miầu', 17799);
insert into offers (city_from, city_to, cost) values ('Tessalit', 'Padangulaktanding', 23786);
insert into offers (city_from, city_to, cost) values ('Pitkyaranta', 'Kolmården', 1848);
insert into offers (city_from, city_to, cost) values ('Guanshan', 'Gaofeng', 1726);
insert into offers (city_from, city_to, cost) values ('Don Matías', 'Comalapa', 5549);
insert into offers (city_from, city_to, cost) values ('Kyankwanzi', 'Neiba', 15847);
insert into offers (city_from, city_to, cost) values ('Chợ Chu', 'Huité', 20201);
insert into offers (city_from, city_to, cost) values ('Xicheng', 'Xiangshun', 20354);
insert into offers (city_from, city_to, cost) values ('Binubusan', 'Aramayuan', 23552);
insert into offers (city_from, city_to, cost) values ('Aţ Ţurrah', 'Muye', 18205);
insert into offers (city_from, city_to, cost) values ('Parzęczew', 'Chinhoyi', 23264);
insert into offers (city_from, city_to, cost) values ('El Paso', 'Mariposa', 14880);
insert into offers (city_from, city_to, cost) values ('Pesek', 'Changtan', 437);
insert into offers (city_from, city_to, cost) values ('Dalonghua', 'Fasi', 20321);
insert into offers (city_from, city_to, cost) values ('Bulgan', 'Juvisy-sur-Orge', 9438);
insert into offers (city_from, city_to, cost) values ('Woto', 'San Eugenio', 9764);
insert into offers (city_from, city_to, cost) values ('Liverpool', 'Čajetina', 17393);
insert into offers (city_from, city_to, cost) values ('Kostryzhivka', 'San Antonio', 4516);
insert into offers (city_from, city_to, cost) values ('Suponevo', 'Harrisburg', 20077);
insert into offers (city_from, city_to, cost) values ('Cosmópolis', 'København', 15350);
insert into offers (city_from, city_to, cost) values ('As Sālimīyah', 'Santo Adrião Vizela', 16007);
insert into offers (city_from, city_to, cost) values ('Runjin', 'Takarazuka', 8967);
insert into offers (city_from, city_to, cost) values ('La Cumbre', 'Riolândia', 17559);
insert into offers (city_from, city_to, cost) values ('Barbosa', 'Šentrupert', 23356);
insert into offers (city_from, city_to, cost) values ('Roanoke', 'Koryukivka', 23478);
insert into offers (city_from, city_to, cost) values ('Baleal', 'Dampol', 11298);
insert into offers (city_from, city_to, cost) values ('Stettler', 'Tourcoing', 3314);
insert into offers (city_from, city_to, cost) values ('Kameoka', 'Moijabana', 16862);
insert into offers (city_from, city_to, cost) values ('Avignon', 'Maisons-Alfort', 23348);
insert into offers (city_from, city_to, cost) values ('Limoeiro de Anadia', 'Palhais', 19375);
insert into offers (city_from, city_to, cost) values ('New York City', 'Jingdezhen', 11746);
insert into offers (city_from, city_to, cost) values ('Efeng', 'Lekas', 10725);
insert into offers (city_from, city_to, cost) values ('Ciechanowiec', 'Rosice', 12734);
insert into offers (city_from, city_to, cost) values ('Emin', 'Agualva de Cima', 15401);
insert into offers (city_from, city_to, cost) values ('Matola', 'Provins', 7954);
insert into offers (city_from, city_to, cost) values ('Jardín', 'Oslo', 11771);
insert into offers (city_from, city_to, cost) values ('Praia', 'Rungis', 1289);
insert into offers (city_from, city_to, cost) values ('Yelabuga', 'Auch', 4321);
insert into offers (city_from, city_to, cost) values ('Shilovo', 'Nunhala', 14897);
insert into offers (city_from, city_to, cost) values ('Kangasala', 'Miura', 14158);
insert into offers (city_from, city_to, cost) values ('La Maná', 'Uarini', 1517);
insert into offers (city_from, city_to, cost) values ('Xinan', 'Gornji Milanovac', 8003);
insert into offers (city_from, city_to, cost) values ('Karobokan', 'Anaco', 14150);
insert into offers (city_from, city_to, cost) values ('Varāmīn', 'Temaiku Village', 20063);
insert into offers (city_from, city_to, cost) values ('Fram', 'Smedjebacken', 3566);
insert into offers (city_from, city_to, cost) values ('Battle Creek', 'Černovice', 23797);
insert into offers (city_from, city_to, cost) values ('Nijiangping', 'Partille', 7926);
insert into offers (city_from, city_to, cost) values ('Sergokala', 'Saint-Dizier', 2878);
insert into offers (city_from, city_to, cost) values ('Kuching', 'Kembé', 10559);
insert into offers (city_from, city_to, cost) values ('Chengui', 'Gunung Talang', 6769);
insert into offers (city_from, city_to, cost) values ('Gostivar', 'Paraparaumu', 5017);
insert into offers (city_from, city_to, cost) values ('Mosta', 'Iporá', 4663);
insert into offers (city_from, city_to, cost) values ('Fukou', 'Coté-Lai', 12376);
insert into offers (city_from, city_to, cost) values ('Nova Olímpia', 'Rulong', 20515);
insert into offers (city_from, city_to, cost) values ('Zhangduangu', 'Baroh', 11132);
insert into offers (city_from, city_to, cost) values ('Tepusteca', 'Deán Funes', 5349);
insert into offers (city_from, city_to, cost) values ('Palanit', 'Krajan Dua Padomasan', 4627);
insert into offers (city_from, city_to, cost) values ('Waterloo', 'Ketang', 4167);
insert into offers (city_from, city_to, cost) values ('Stockholm', 'Boticas', 11755);
insert into offers (city_from, city_to, cost) values ('Santai', 'Kanash', 11681);
insert into offers (city_from, city_to, cost) values ('Locminé', 'Charlottetown', 6242);
insert into offers (city_from, city_to, cost) values ('Cikole', 'Ninh Hòa', 16104);
insert into offers (city_from, city_to, cost) values ('Alua', 'Skokovi', 21965);
insert into offers (city_from, city_to, cost) values ('Caherconlish', 'Barra dos Coqueiros', 726);
insert into offers (city_from, city_to, cost) values ('Villa Mercedes', 'Xike', 22248);
insert into offers (city_from, city_to, cost) values ('Krajan Bakalan', 'Saarbrücken', 11630);
insert into offers (city_from, city_to, cost) values ('Kaiyuan', 'Cincinnati', 17512);
insert into offers (city_from, city_to, cost) values ('Noveleta', 'Ribeiro', 2445);
insert into offers (city_from, city_to, cost) values ('Jialu', 'Mmathubudukwane', 19104);
insert into offers (city_from, city_to, cost) values ('Mabilang', 'Belas', 18912);
insert into offers (city_from, city_to, cost) values ('Dazhou', 'Bègles', 13098);
insert into offers (city_from, city_to, cost) values ('Deqing', 'Barra de Carrasco', 9021);
insert into offers (city_from, city_to, cost) values ('Zhaoqing', 'Miaoshou', 23341);
insert into offers (city_from, city_to, cost) values ('Trąbki Wielkie', 'Armenia', 3015);
insert into offers (city_from, city_to, cost) values ('Nouaseur', 'Kālābāgh', 3039);
insert into offers (city_from, city_to, cost) values ('Shangdian', 'Nanyang', 9796);
insert into offers (city_from, city_to, cost) values ('Santo Tomé', 'Palhais', 20263);
insert into offers (city_from, city_to, cost) values ('Eixo', 'Utan', 11958);
insert into offers (city_from, city_to, cost) values ('Dongfeng', 'Paranapanema', 18851);
insert into offers (city_from, city_to, cost) values ('Semarang', 'Drawno', 18622);
insert into offers (city_from, city_to, cost) values ('Przecław', 'Santa Elena de Uairén', 13616);
insert into offers (city_from, city_to, cost) values ('Maralal', 'Kristianstad', 13482);
insert into offers (city_from, city_to, cost) values ('San Cristóbal', 'Bairro', 20951);
insert into offers (city_from, city_to, cost) values ('Qiziltepa Shahri', 'Černelavci', 8881);
insert into offers (city_from, city_to, cost) values ('Buenavista', 'Musan-ŭp', 12046);
insert into offers (city_from, city_to, cost) values ('Lianghe', 'Hưng Yên', 6034);
insert into offers (city_from, city_to, cost) values ('Biru', 'Amsterdam Noord west', 8857);
insert into offers (city_from, city_to, cost) values ('Hagonoy', 'Candelaria', 847);
insert into offers (city_from, city_to, cost) values ('Umburarameha', 'Brněnec', 16528);
insert into offers (city_from, city_to, cost) values ('Mariel', 'Quillota', 22880);
insert into offers (city_from, city_to, cost) values ('Popayán', 'Criciúma', 16490);
insert into offers (city_from, city_to, cost) values ('Lujing Zhen', 'Daytona Beach', 12292);
insert into offers (city_from, city_to, cost) values ('Reims', 'Cutral-Có', 609);
insert into offers (city_from, city_to, cost) values ('Tunbao', 'Sundbyberg', 8126);
insert into offers (city_from, city_to, cost) values ('Webuye', 'Trzebinia', 12158);
insert into offers (city_from, city_to, cost) values ('Sumber', 'Järfälla', 15943);
insert into offers (city_from, city_to, cost) values ('Juai', 'Genova', 12619);
insert into offers (city_from, city_to, cost) values ('Fenggang', 'Vitória de Santo Antão', 2494);
insert into offers (city_from, city_to, cost) values ('Machachi', 'Tecpán Guatemala', 7575);
insert into offers (city_from, city_to, cost) values ('Lille', 'Karangasem', 6053);
insert into offers (city_from, city_to, cost) values ('Pingtian', 'Deir Ḥannā', 14172);
insert into offers (city_from, city_to, cost) values ('Kapakabisa', 'Tenggong', 9911);
insert into offers (city_from, city_to, cost) values ('Krajan Puru', 'Hekou', 17503);
insert into offers (city_from, city_to, cost) values ('Alburitel', 'Vereshchagino', 10242);
insert into offers (city_from, city_to, cost) values ('Safotulafai', 'Sulechów', 19641);
insert into offers (city_from, city_to, cost) values ('Lakinsk', 'Lycksele', 5354);
insert into offers (city_from, city_to, cost) values ('Shazi', 'Tohautu', 23915);
insert into offers (city_from, city_to, cost) values ('Narva', 'Hecun', 3901);
insert into offers (city_from, city_to, cost) values ('Trondheim', 'Dongmafang', 3883);
insert into offers (city_from, city_to, cost) values ('Alegrete', 'Jianggezhuang', 7565);
insert into offers (city_from, city_to, cost) values ('Masis', 'Fuzhiping', 19900);
insert into offers (city_from, city_to, cost) values ('Haymā’', 'Xiyuan', 1967);
insert into offers (city_from, city_to, cost) values ('Sagaing', 'Minji', 23385);
insert into offers (city_from, city_to, cost) values ('Słupsk', 'Villa Altagracia', 10101);
insert into offers (city_from, city_to, cost) values ('Pogorzyce', 'Viesīte', 22761);
insert into offers (city_from, city_to, cost) values ('Crespo', 'Hamberang Sabrang', 17243);
insert into offers (city_from, city_to, cost) values ('Knin', 'Tranca', 13778);
insert into offers (city_from, city_to, cost) values ('Cotabambas', 'Mayisad', 7797);
insert into offers (city_from, city_to, cost) values ('Ruyigi', 'La Libertad', 13987);
insert into offers (city_from, city_to, cost) values ('Paizhou', 'Bierawa', 12302);
insert into offers (city_from, city_to, cost) values ('Derjan', 'Araranguá', 1919);
insert into offers (city_from, city_to, cost) values ('Shuangzhong', 'Satovcha', 8838);
insert into offers (city_from, city_to, cost) values ('Längelmäki', 'Zhanbei', 5239);
insert into offers (city_from, city_to, cost) values ('Tongole', 'Wanagiri', 21372);
insert into offers (city_from, city_to, cost) values ('Janowiec', 'Wobulenzi', 7853);
insert into offers (city_from, city_to, cost) values ('Triteh', 'Sandaogou', 12766);
insert into offers (city_from, city_to, cost) values ('San Luis', 'Borgustanskaya', 1037);
insert into offers (city_from, city_to, cost) values ('Bankim', 'Samagaltay', 17193);
insert into offers (city_from, city_to, cost) values ('Tall aḑ Ḑamān', 'Bang Kaeo', 964);
insert into offers (city_from, city_to, cost) values ('Krasnyy Yar', 'Józefów', 4077);
insert into offers (city_from, city_to, cost) values ('Bibinje', 'Siem Reap', 15394);
insert into offers (city_from, city_to, cost) values ('Gempol', 'Waepana', 10986);
insert into offers (city_from, city_to, cost) values ('Kedungdowo', 'Qorao’zak', 21727);
insert into offers (city_from, city_to, cost) values ('Trubchevsk', 'Cuenca', 14864);
insert into offers (city_from, city_to, cost) values ('San Francisco', 'Dupnitsa', 2159);
insert into offers (city_from, city_to, cost) values ('Morropón', 'Sirnarasa', 16119);
insert into offers (city_from, city_to, cost) values ('Bururi', 'Radenka', 7769);
insert into offers (city_from, city_to, cost) values ('Balingasag', 'Leiyang', 15464);
insert into offers (city_from, city_to, cost) values ('Colón', 'Tanjungjaya', 4725);
insert into offers (city_from, city_to, cost) values ('Hotaka', 'Dateng', 1670);
insert into offers (city_from, city_to, cost) values ('Maji', 'Hoboksar', 1918);
insert into offers (city_from, city_to, cost) values ('Mirkovci', 'Prienai', 4097);
insert into offers (city_from, city_to, cost) values ('Tunduma', 'Nakhon Sawan', 17219);
insert into offers (city_from, city_to, cost) values ('Malonty', 'Meudon', 7791);
insert into offers (city_from, city_to, cost) values ('Banjar Banyuning Barat', 'Sovetskiy', 6388);
insert into offers (city_from, city_to, cost) values ('Kota Kinabalu', 'Nanguzhuang', 16824);
insert into offers (city_from, city_to, cost) values ('Asahbadung', 'Makadi Bay', 15436);
insert into offers (city_from, city_to, cost) values ('Kinalaglagan', 'Sovetsk', 12574);
insert into offers (city_from, city_to, cost) values ('Chupa', 'Oklahoma City', 23168);
insert into offers (city_from, city_to, cost) values ('Vuokatti', 'Dodoma', 11020);
insert into offers (city_from, city_to, cost) values ('Boconó', 'Selnica', 11726);
insert into offers (city_from, city_to, cost) values ('Ninomiya', 'Göteborg', 2871);
insert into offers (city_from, city_to, cost) values ('Solna', 'Kerrobert', 9585);
insert into offers (city_from, city_to, cost) values ('Bobota', 'Cristóbal', 8574);
insert into offers (city_from, city_to, cost) values ('Sumberngerjat', 'Águas Belas', 6766);
insert into offers (city_from, city_to, cost) values ('Elaiochóri', 'Pirot', 13058);
insert into offers (city_from, city_to, cost) values ('Xiaopu', 'Senglea', 12673);
insert into offers (city_from, city_to, cost) values ('Balaklava', 'Tama', 11547);
insert into offers (city_from, city_to, cost) values ('Apeldoorn', 'Masis', 19124);
insert into offers (city_from, city_to, cost) values ('Lipa City', 'Krzemienica', 12267);
insert into offers (city_from, city_to, cost) values ('San Pedro', 'Vacov', 1232);
insert into offers (city_from, city_to, cost) values ('Bom Jesus do Itabapoana', 'Quemú Quemú', 20602);
insert into offers (city_from, city_to, cost) values ('Bokoro', 'Bác Ái', 3900);
insert into offers (city_from, city_to, cost) values ('Sergiyev Posad', 'Vejprnice', 13587);
insert into offers (city_from, city_to, cost) values ('Cikawunggading', 'Cubará', 12966);
insert into offers (city_from, city_to, cost) values ('Rudnya', 'Duancun', 5653);
insert into offers (city_from, city_to, cost) values ('Honglai', 'Liwu', 3778);
insert into offers (city_from, city_to, cost) values ('Tacoma', 'Supu', 14457);
insert into offers (city_from, city_to, cost) values ('Plalar', 'Wangping', 18169);
insert into offers (city_from, city_to, cost) values ('Veguitas', 'Nanfeng', 701);
insert into offers (city_from, city_to, cost) values ('Cumanayagua', 'Hrodna', 9244);
insert into offers (city_from, city_to, cost) values ('Tiouli', 'Fontana', 8885);
insert into offers (city_from, city_to, cost) values ('Núi Đối', 'Açu', 3048);
insert into offers (city_from, city_to, cost) values ('Wan’an', 'La Libertad', 21625);
insert into offers (city_from, city_to, cost) values ('Huazhou', 'Ribeirão Pires', 18290);
insert into offers (city_from, city_to, cost) values ('Baliuag', 'Bacong', 4065);
insert into offers (city_from, city_to, cost) values ('Kedungwringin', 'Bao’an', 1013);
insert into offers (city_from, city_to, cost) values ('Cisiih', 'Gangtun', 13381);
insert into offers (city_from, city_to, cost) values ('Ketovo', 'Piracuruca', 12168);
insert into offers (city_from, city_to, cost) values ('Mława', 'Arcueil', 9115);
insert into offers (city_from, city_to, cost) values ('Pingshan', 'Campo Viera', 9359);
insert into offers (city_from, city_to, cost) values ('Báguanos', 'Santa Teresa First', 17747);
insert into offers (city_from, city_to, cost) values ('Rasshevatskaya', 'Haokou', 14053);
insert into offers (city_from, city_to, cost) values ('Nelspruit', 'Aizhai', 12838);
